DIRECTORY=MATHS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	analyticalGeometry.C\
	angle.C\
	box3.C\
	circle3.C\
	line3.C\
	matrix44.C\
	plane3.C\
	quaternion.C\
	sphere3.C\
	surface.C\
	vector3.C\
	vector4.C

include ../common.mak
include .Dependencies
