DIRECTORY=VIEW/KERNEL

THISLIB=$(LIBNAME)
	
CPP_SOURCES=\
	client.C\
	colorExtension1.C\
	colorExtension2.C\
	connectionObject.C\
	geometricObject.C\
	message.C\
	normal.C\
	QTTimer.C\
	radius.C\
	logView.C\
	vertex1.C\
	vertex2.C

include ../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)

