DIRECTORY=VIEW/MODELS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	molecularModel.C\
	atomBondModelBaseProcessor.C\
	atomBondModelConnector.C\
	backboneModel.C\
	ballAndStickModel.C\
	baseModelConnector.C\
	cartoonModel.C\
	lineModel.C\
	standardColorProcessor.C\
	surfaceModel.C\
	vanDerWaalsModel.C

include ../../common.mak
include .Dependencies
