# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.8.2.1 2006/01/31 10:34:57 oliver Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/MODELS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atomBondModelBaseProcessor.C\
	backboneModel.C\
	ballAndStickModel.C\
	cartoonModel.C\
	colorProcessor.C\
	forceModel.C\
	HBondModel.C\
	labelModel.C\
	lineModel.C\
	modelProcessor.C\
	standardColorProcessor.C\
	surfaceModel.C\
	vanDerWaalsModel.C

include ../../common.mak
-include .Dependencies
