# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.9.14.1 2007/03/25 22:02:28 oliver Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/MODELS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atomBondModelBaseProcessor.C\
	backboneModel.C\
	ballAndStickModel.C\
	cartoonModel.C\
	colorProcessor.C\
	fieldLineCreator.C\
	forceModel.C\
	HBondModel.C\
	labelModel.C\
	lineModel.C\
	modelProcessor.C\
	standardColorProcessor.C\
	surfaceModel.C\
	vanDerWaalsModel.C

include ../../common.mak
-include .Dependencies
