DIRECTORY=MOLVIEW/GUI/PRIMITIV

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glBackbone.C\
	glTwoColoredLine.C\
	glTwoColoredTube.C

include ../../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)
