# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.9.10.1 2006/02/14 15:03:23 amoll Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/DATATYPE

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	colorExtension2.C\
	colorHSV.C\
	colorRGBA.C\
	colorMap.C\
	colorUnit.C\
	colorUnitHue.C\
	vertex1.C\
	vertex2.C

include ../../common.mak
-include .Dependencies
