DIRECTORY=VIEW/DATATYPE

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	colorExtension2.C\
	colorHSV.C\
	colorRGBA.C\
	colorTable.C\
	colorUnit.C\
	colorUnitHue.C\
	vertex1.C\
	vertex2.C

include ../../common.mak
include .Dependencies
