include(${CMAKE_SOURCE_DIR}/include/BALL/VIEW/DIALOGS/sources.cmake)
include(${CMAKE_SOURCE_DIR}/include/BALL/VIEW/WIDGETS/sources.cmake)
include(${CMAKE_SOURCE_DIR}/include/BALL/VIEW/KERNEL/sources.cmake)
include(${CMAKE_SOURCE_DIR}/include/BALL/VIEW/DATATYPE/sources.cmake)
include(${CMAKE_SOURCE_DIR}/include/BALL/VIEW/RENDERING/sources.cmake)
