 class PersistentObject
 { 
%HeaderCode
#include <BALL/CONCEPT/persistentObject.h>
using namespace BALL;
%End
  public:
  PersistentObject();
	// virtual ~PersistentObject();
  //PersistenceManager& operator >> (PersistenceManager& pm) const;
  //virtual void persistentWrite(PersistenceManager& pm, const char* name = "") const;
  //virtual void persistentRead(PersistenceManager& pm);
  //virtual void finalize()
 };
