#!/bin/sh
cat /dev/null > classes
for i in *-members.html; do
 class=`echo $i | sed "s/.*1_1//g" | sed "s/-members.*//"`
 echo $class           $i  >> classes
done
cat classes | grep -v "struct" > temp
mv temp classes
