#!/bin/sh
cd 
cp $BALL_PATH/lib/$PLATFORM/lib*.so deb-ball/usr/lib/ &&

cp $BALL_PATH/lib/$PLATFORM/BALLmodule.so deb-ball/usr/lib/python2.3/site-packages &&
cp /opt/sip-4.0rc1_gcc-3.3.3/siplib/sip.so deb-ball/usr/lib/python2.3/site-packages &&

cp $BALL_PATH/source/APPLICATIONS/BALLVIEW/BALLView deb-ball/usr/bin/ &&

cp -rf $BALL_PATH/doc/BALLView deb-ball/usr/share/doc &&

cp -r $BALL_PATH/data deb-ball/opt/BALL &&

cp $BALL_PATH/source/config/control deb-ball/DEBIAN &&

for i in `find deb-ball -name "CVS"`; do rm -rf $i; done &&

dpkg -b deb-ball BALLView.deb
