#!/usr/local/bin/bash
WEBDIR=/www/pub/www.mpi-sb.mpg.de/BALL/doc
echo "copying postscript and PDF documentation..."
cp ../doc/BALL.ps ../doc/BALL.pdf ${WEBDIR}
rm -fr ${WEBDIR}/html
echo "copying html documentation..."
(cd ../doc;gtar cf - html)|(cd ${WEBDIR};gtar xf -)
