#!/usr/local/bin/bash
#
#  $Id: makedistribution,v 1.5 2000/05/05 16:25:22 oliver Exp $
#

# check whether the revision number is given as the first argument
# (CVS tag!)
if test $# != 1 ; then
	echo "makdistribution <CVS tag>"
	exit
else
	TAG=$1
fi

# create a dummy directory and extract the current CVS version of BALL
echo "extracting BALL revision $1 from cvs..."
cd /tmp
rm -fr BALL-dist 2>/dev/null
mkdir BALL-dist
cd BALL-dist
cvs -q co -r ${TAG} BALL 1>cvs_extract.log 2>cvs_extract_err.log || echo "cannot extract revision ${TAG} of BALL" >&0 | exit
# remove CVS information
find . -name CVS -exec rm -fr {} \;
cd BALL/source
FILE="BALL-`grep BALL_RELEASE_STRING ../include/BALL/COMMON/version.h | awk '{print $3}'| tr -d \\"`.tar"
mv config/Makefile.dummy .
cd ../../

echo "creating archive ${FILE}..."
tar cf ${FILE} BALL

echo "compressing archive $FILE..."
gzip -9 $FILE
mv ${FILE}.gz ~
