#!/bin/bash -e
# create a version of the BALLView docu for the website...
rm -fr $BALL_PATH/doc/BALLView-website 2>/dev/null 
cp -r $BALL_PATH/doc/BALLView $BALL_PATH/doc/BALLView-website 
cd $BALL_PATH/doc/BALLView-website 

rm -rf CVS 
rm -rf images/CVS 

rename s/\.html/_html/ *.html

for i in `find . -name "*html"`; do sed -i "s/\.html/_html/g" $i; done 

echo running tidy...
tidy -m -i -asxml -q -bare -clean *html 2>/dev/null | true
echo finished running tidy...
cd - > /dev/null
