#!/usr/local/bin/bash
# $Id: maketexdoc,v 1.8 2000/05/05 07:09:11 oliver Exp $

mkdir ../doc 2>/dev/null
mkdir ../doc/tex 2>/dev/null
cp config/docxx.sty ../doc/tex

cd ../include/BALL
/KM/comp-bio/BALL-contrib/doc++-3.4.3/bin/doc++ $OPTS -N -ng -D 3 -ei -m -w -W -u -t -ep amsmath -o ../../doc/tex/BALL.tex BALL.doc
cd ../../doc/tex
latex BALL
latex BALL
dvips BALL
pdflatex BALL
pdflatex BALL
mv BALL.ps BALL.pdf ..
