#!/usr/local/bin/bash

mkdir ../doc 2>/dev/null
mkdir ../doc/tex 2>/dev/null
cp config/docxx.sty ../doc/tex

cd ../include/BALL
/KM/comp-bio/BALL-contrib/docxx/bin/SunOS/doc++ $OPTS -t -o ../../doc/tex/BALL.tex BALL.doc
cd ../../doc/tex
latex BALL
latex BALL
dvips BALL
ps2pdf BALL.ps BALL.pdf
mv BALL.ps BALL.pdf ..
