#!/bin/bash
CONFIGFILE=doxygen.cfg

if [ $# = 1 ] && [ $1 = "-website" ]; then
	CONFIGFILE=doxygen_website.cfg
fi

cd ../doc/ || exit
rm -f doxygen/html/* 
doxygen $CONFIGFILE || exit
cd doxygen/html || exit

# Now walk over all html files and remove
# the annoying BALL:: prefix for all class 
# names to keep things short.
TMPFILE=/tmp/$$.tmp.makedoc
for i in `find . -name "*html"`; do 
	cat $i|sed "s/BALL:://g" > $TMPFILE &&\
		rm $i &&\
		mv $TMPFILE $i
done 

# Remove leftovers if something went wrong above...
if test -f "$TMPFILE" ; then 
	rm $TMPFILE
fi
