#!/bin/sh
#
#  $Id: makedistribution,v 1.2 2000/01/17 09:42:28 oliver Exp $
#

# create a dummy directory and extract the current CVS version of BALL
cd /tmp
rm -fr BALL-dist 2>/dev/null
mkdir BALL-dist 
cd BALL-dist
cvs co BALL
# remove CVS information
find . -name CVS -exec rm -fr {} \;
cd BALL/source
FILE="BALL-`grep BALL_RELEASE_STRING ../include/BALL/COMMON/version.h | awk '{print $3}'| tr -d \\"`.tar"

mv config/Makefile.dummy .
cd ../../

echo "creating archive ${FILE}..."
tar cf ${FILE}

echo "compressing archive $FILE..."
gzip -9 $FILE
mv ${FILE}.gz ~
