#!/usr/local/bin/bash

RELEASE="Release 0.2"




mkdir ../doc 2>/dev/null
mkdir ../doc/html 2>/dev/null
mkdir ../doc/html/BALL 2>/dev/null


cd ../doc/html

# highly non-portable code - but doesn't matter as it is intended for
# the developers only

# extract the realname of the user
USERNAME=`finger ${USER} |grep Login|grep ": ${USER}" | head -1|sed "s/^.*life: //"|sed "s/&/${USER}/"`
DATE=`date +"%a %b %e %Y, %T"`



if test "$1" != "-f" ; then
	echo "collecting header files..."

	HEADER_NAMES=`cd ../../include ; find BALL -name \*.h -print`

	echo "creating directories"

	HEADER_DIRECTORIES=`for i in ${HEADER_NAMES} ; do dirname $i ; done | sort -u`
	for i in ${HEADER_DIRECTORIES} ; do 
		mkdirhier $i 2>/dev/null
	done
	
	echo "copying headers..."

	for i in ${HEADER_NAMES} ; do 
		cat ../../include/$i | gawk -f tools/remove_doc_comments.awk  > $i
	done

	echo "creating start page..."

	cp tools/*.inc tools/*.gif tools/*.html .

	cat tools/INTRO.html |\
		sed "s/@USER@/${USERNAME}/" |\
		sed "s/@RELEASE@/${RELEASE}/" |\
		sed "s/@DATE@/${DATE}/" > INTRO.html

fi

/KM/comp-bio/BALL-contrib/docxx/bin/SunOS/doc++ $OPTS  -B banner.inc -eo 12pt -d . ../../include/BALL/BALL.doc

