#!/usr/local/bin/bash


if test ! -f $1 ; then
	echo "cannot open $1!"
	exit
fi

DIR=/tmp/$$.bindist.tmp
echo "extracting data files from cvs..."
mkdir $DIR
(
	cd $DIR
	mkdir MolVIEW
	cd MolVIEW
	cvs co BALL/data 2>/dev/null >/dev/null
	find . -name CVS -exec rm -fr {} \; 2>/dev/null >/dev/null
	mv BALL/data .
	rmdir BALL
)
echo "copying application..."
cp $1 $DIR/MolVIEW/molview.exe
cp /KM/usr/oliver/BALL/source/APPLICATIONS/MOLVIEW/AlaAla.hin $DIR/MolVIEW
cp /KM/usr/oliver/BALL/source/APPLICATIONS/MOLVIEW/bpti.pdb $DIR/MolVIEW
cp /KM/usr/oliver/BALL/source/config/README.MOLVIEW.bindist $DIR/MolVIEW/README
echo "#!/bin/sh" > $DIR/MolVIEW/molview
echo "BALL_DATA_PATH=\"\`echo \$0|sed s/molview\$/data/\`\"" >> $DIR/MolVIEW/molview
echo "export BALL_DATA_PATH" >> $DIR/MolVIEW/molview
echo "\$0.exe" >> $DIR/MolVIEW/molview
chmod 755 $DIR/MolVIEW/molview
echo "creating archive..."
(
	cd $DIR
	tar cf - MolVIEW
)| gzip -9 -c > $1.tar.gz
echo "cleaning up..."
rm -fr $DIR

echo "done."
