#!/usr/local/bin/bash


if test ! -f $1 ; then
	echo "cannot open $1!"
	exit
fi

DIR=/tmp/$$.bindist.tmp
echo "extracting data files from cvs..."
mkdir $DIR
(
	cd $DIR
	mkdir BALLView
	cd BALLView
	cvs co BALL/data 2>/dev/null >/dev/null
	find . -name CVS -exec rm -fr {} \; 2>/dev/null >/dev/null
	mv BALL/data .
	rmdir BALL
)
echo "copying application..."
cp $1 $DIR/BALLView/BALLView.exe
cp /KM/usr/oliver/BALL/source/APPLICATIONS/BALLVIEW/AlaAla.hin $DIR/BALLView
cp /KM/usr/oliver/BALL/source/APPLICATIONS/BALLVIEW/bpti.pdb $DIR/BALLView
cp /KM/usr/oliver/BALL/source/config/README.BALLVIEW.bindist $DIR/BALLView/README
echo "#!/bin/sh" > $DIR/BALLView/BALLView
echo "BALL_DATA_PATH=\"\`echo \$0|sed s/BALLView\$/data/\`\"" >> $DIR/BALLView/BALLView
echo "export BALL_DATA_PATH" >> $DIR/BALLView/BALLView
echo "\$0.exe \$*" >> $DIR/BALLView/BALLView
chmod 755 $DIR/BALLView/BALLView
echo "creating archive..."
(
	cd $DIR
	tar cf - BALLView
)| gzip -9 -c > $1.tar.gz
echo "cleaning up..."
rm -fr $DIR

echo "done."
