#!/bin/bash
CONFIGFILE=doxygen.cfg

if [ $# = 1 ] && [ $1 = "-website" ]; then
	CONFIGFILE=doxygen_website.cfg
fi

cd ../doc/ && \
rm -f doxygen/html/*;  
doxygen $CONFIGFILE && \
cd doxygen/html && \
for i in `find . -name "*html"`; do sed -i "s/BALL:://g" $i; done 

echo running tidy...
for i in `find . -name "*_html"`; 
do 
	tidy $i > tidy $i;
done
echo finished running tidy...
