#!/usr/local/bin/bash
# $Id: makehtmldoc,v 1.5 2000/05/04 20:07:47 oliver Exp $

# highly non-portable code - but doesn't matter as it is intended for
# the developers only! - OK

# extract teh date for replacing in all html pages
USERNAME=`finger ${USER} |grep Login|grep ": ${USER}" | head -1|sed "s/^.*life: //"|sed "s/&/${USER}/"`
DATE=`date +"%a %b %e %Y"`
RELEASE="`grep BALL_RELEASE_STRING ../include/BALL/COMMON/version.h | awk '{print $3}'|tr -d \\"`"
YEAR=`date +%Y`

mkdir ../doc 2>/dev/null
mkdir ../doc/html 2>/dev/null
mkdir ../doc/html/BALL 2>/dev/null


cd ../doc/html

if test "$1" != "-f" -a "$2" != "-f" ; then
	echo "collecting header files..."

	HEADER_NAMES=`cd ../../include ; find BALL -name \*.h -print`

	echo "creating directories"

	HEADER_DIRECTORIES=`for i in ${HEADER_NAMES} ; do dirname $i ; done | sort -u`
	for i in ${HEADER_DIRECTORIES} ; do 
		mkdirhier $i 2>/dev/null
	done
	
	echo "copying headers..."

	for i in ${HEADER_NAMES} ; do 
		cat ../../include/$i | expand -t 2 | /opt/gnu/bin/gawk -f tools/remove_doc_comments.awk  > $i
	done

fi
cp tools/*.gif  .

echo "creating start page and html include files..."

for i in tools/*.inc tools/*.html ; do
	cat $i |\
		sed "s/@USER@/${USERNAME}/" |\
		sed "s/@RELEASE@/${RELEASE}/" |\
		sed "s/@YEAR@/${YEAR}/" |\
		sed "s/@DATE@/${DATE}/" > `basename $i`
done

#  use -v to turn DOC++ verbose mode on
# 
if test "$1" = "-v" -o "$2" = "-v" ; then 
	OPTS="${OPTS} -v"
fi

#/KM/comp-bio/BALL-contrib/docxx/bin/SunOS/doc++ $OPTS  -B banner.inc -eo 12pt -d . ../../include/BALL/BALL.doc
#/KM/comp-bio/BALL-contrib/doc++-3.4.1/bin/doc++ $OPTS -v -f -u -N -B banner.inc -eo 12pt -d . ../../include/BALL/BALL.doc
/KM/comp-bio/BALL-contrib/doc++-3.4.3/bin/doc++ $OPTS -N -u -m -w -W -G -B banner.inc -eo 11pt -d . ../../include/BALL/BALL.doc
