#!/bin/bash -e 
# Contrib path
CPATH=`echo $0 | sed "s/\/build_contrib//"`
cd $CPATH
CPATH=`pwd`
echo building contrib package from $CPATH ...

DPATH=$CPATH

if [ $# == 1 ]
then
	DPATH=$1
	rm -rf $DPATH/* 2>/dev/null
	install -d $DPATH
	cp -r * $DPATH
	cd $DPATH
fi

mbuild()
{
	make -j2 &> ../build.log 
	make install &> ../build.log
}

echo
echo extracting packages to $DPATH ...
for i in ./*.gz; do tar xzf $i; done;
for i in ./*.tgz; do tar xzf $i; done;

touch build.log
install -d include lib

echo
echo building fftw ...
echo
cd fftw*
# Configure for ppc
./configure CFLAGS="-arch ppc" --with-combined-threads --enable-altivec --enable-threads --with-gcc-arch=G5 --enable-float -q --prefix=$DPATH &> ../build.log
# Clean
make clean  &> ../build.log
mbuild
cd ../lib/
# Rename library
mv ./libfftw3f.a ./libfftw3-ppc.a

cd ../fftw*
# Configure for i386
./configure CFLAGS="-arch i386" --with-combined-threads --enable-sse2 --enable-threads --enable-double -q --prefix=$DPATH &> ../build.log
# Clean
make clean  &> ../build.log
# Make
mbuild
cd ../lib/
# Rename library
mv ./libfftw3.a ./libfftw3-i386.a
# lipo everything together
lipo -create libfftw3-i386.a libfftw3-ppc.a -output libfftw3.a
rm libfftw3-i386.a libfftw3-ppc.a
cd ..

echo
echo building glew ...
echo
cd glew*
export GLEW_DEST=$DPATH
mbuild
cd ..

echo
echo building sip ...
echo
cd sip*
python configure.py -n -b $DPATH/bin -d $DPATH/lib -e $DPATH/include &> ../build.log
mbuild
cd ..

echo
echo building gsl ...
echo
cd gsl*
./configure --disable-dependency-tracking CFLAGS="-isysroot /Developer/SDKs/MacOSX10.5.sdk -arch ppc -arch i386" LDFLAGS="-Wl,-syslibroot,/Developer/SDKs/MacOSX10.5.sdk -arch ppc -arch i386" --prefix=$DPATH &> ../build.log
mbuild
cd ..

echo
echo building Qt ...
echo
cd qt*
./configure -no-qt3support -silent -no-nis -confirm-license -universal --prefix=$DPATH &> ../build.log
mbuild
cd ..

echo
echo cleanup ...
echo

echo
echo Finished building contrib package
echo
