#!/bin/bash 

# Contrib path
CPATH=`echo $0 | sed "s/\/build_contrib//"`
cd $CPATH
CPATH=`pwd`

echo building contrib package from $CPATH ...


tar -xzf newmat.tar.gz;
tar -xzf libsvm.tar.gz;
tar -xzf gsl-1.8.tar.gz;
tar -xzf qwt-5.0.2.tar.gz;

echo
echo building gsl ...
echo
cd gsl-1.8
./configure --prefix=`pwd`/gsl-1.8
make
make install
cd ..

echo
echo building newmat ...
echo 
cd newmat
make
cd ..

echo
echo building libsvm ...
echo
cd libsvm
make
cd ..


echo
echo building Qwt ...
echo
cd qwt-5.0.2
qmake; make;
cd src; make staticlib;
cd ..
make clean
cd ..

echo
echo Finished building QSAR contrib package
echo
