# MOLMEC/CHARMM/Makefile
#
# $Id: Makefile,v 1.6 2005/07/16 21:00:41 oliver Exp $
#

DIRECTORY=MOLMEC/CHARMM

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	charmm.C\
	charmmBend.C\
	charmmImproperTorsion.C\
	charmmNonBonded.C\
	charmmStretch.C\
	charmmTorsion.C

include ../../common.mak
-include .Dependencies
