# MOLMEC/CHARMM/Makefile
#

DIRECTORY=MOLMEC/CHARMM

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	charmm.C\
	charmmBend.C\
	charmmImproperTorsion.C\
	charmmNonBonded.C\
	charmmStretch.C\
	charmmTorsion.C

include ../../common.mak
-include .Dependencies
