INCLUDE (CheckIncludeFiles)


SET(BALL_PATH "BALL_PATH = ${PROJECT_SOURCE_DIR}/..")

if(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
	SET(BALL_OS_DARWIN 1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "SOLARIS")
	SET(BALL_OS_DARWIN 1)
endif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")


SET(BALL_NO_INLINE_FUNCTIONS 1)
SET(BALL_XDRREC_CREATE_CHAR_CHAR_INT 1)
SET(BALL_HAS_ASIO 1)

SET(pid_t 0)
SET(size_t 0)
SET(BALL_USE_GLEW 0)
SET(BALL_PYTHON_SUPPORT 0)
SET(BALL_HAS_VIEW 1)
SET(BALL_QT_HAS_THREADS 1)
SET(BALL_HAS_ANSI_IOSTREAM)
SET(BALL_HAS_SSTREAM 1)
SET(BALL_HAS_UNORDERED_MAP 1)
SET(BALL_HAS_HASH_MAP 0)
SET(BALL_MAP_NAMESPACE "BALL_MAP_NAMESPACE tr1")
SET(BALL_MAP_NAME "BALL_MAP_NAME std::tr1::unordered_map<Key,T>")
SET(BALL_HAS_ASIO 1)
SET(BALL_HAS_BOOST_ASIO 1)
SET(BALL_HAS_SYS_TIME_H 1)
SET(BALL_HAS_TIME_H 1)
SET(BALL_HAS_SYS_TYPES_H 1)
SET(BALL_HAS_FLOAT_H 1)
SET(BALL_HAS_REGEX_H 1)





message(STATUS "BALL_PATH="${BALL_PATH})
CONFIGURE_FILE(cmake/config.h.in ../include/BALL/CONFIG/config.h)
