# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# Author:
#   Stefan Nickels
#

DIRECTORY=XRAY

include ../config.mak

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	crystalInfo.C

#ifeq ($(BALL_HAS_VIEW),true)
#	CPP_SOURCES+=DBInterface.C
#endif

include ../common.mak
include .Dependencies

