DIRECTORY=MOLMEC/FRESNO

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	fresno.C\
	fresnoHydrogenBond.C\
	fresnoLipophilic.C\
	fresnoBuriedPolar.C\
	fresnoRotation.C\
	fresnoDesolvation.C

include ../../common.mak
include .Dependencies
