# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.4.4.1 2006/02/14 15:03:49 amoll Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/RENDERING

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glDisplayList.C\
	glRenderer.C\
	renderer.C\
	POVRenderer.C\
	VRMLRenderer.C\
	vertexBuffer.C

include ../../common.mak
-include .Dependencies
