# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.7 2006/01/26 16:12:55 oliver Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/RENDERING

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glDisplayList.C\
	glRenderer.C\
	renderer.C\
	POVRenderer.C\
	VRMLRenderer.C\
	vertexBuffer.C

include ../../common.mak
-include .Dependencies
