DIRECTORY=VIEW/RENDERING

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glDisplayList.C\
	glQuadricObject.C\
	glRenderer.C\
	renderer.C\
	POVRenderer.C

include ../../common.mak
include .Dependencies

BALL_INCLUDES=$(VIEW_INCLUDES)

