DIRECTORY=MOLMEC/MMFF94

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	MMFF94.C\
	MMFF94Bend.C\
	MMFF94NonBonded.C\
	MMFF94Stretch.C\
	MMFF94Torsion.C\
	MMFF94Parameters.C

include ../../common.mak
include .Dependencies
