DIRECTORY=MOLMEC/MMFF94

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	MMFF94.C\
	MMFF94StretchBend.C\
	MMFF94Torsion.C\
	MMFF94Parameters.C\
	MMFF94OutOfPlaneBend.C\
	MMFF94Processors.C\
	MMFF94NonBonded.C

include ../../common.mak
-include .Dependencies
