// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Tue Jul 18 11:27:59 2000

#ifndef _BALLFile_H
#define	_BALLFile_H

#include "sipBALLString.h"
#include "sipBALLOpenMode.h"
#include "sipBALLSize.h"

#line 6 "file.sip"
	#include <BALL/SYSTEM/file.h>
	using namespace BALL;
	typedef File::OpenMode OpenMode;
#line 17 "./sipBALLFile.h"

extern SIP_EXPORT PyObject *sipClass_File;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_File[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_File[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_File[];

extern SIP_EXPORT const void *sipCast_File Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_File Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_File Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_File Py_PROTO((PyObject *,File **,int,int *));
extern SIP_EXPORT File *sipForceConvertTo_File Py_PROTO((PyObject *,int *));

#endif
