DIRECTORY=MOLVIEW/KERNEL

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	extendedProperty.C\
	geometricConvertor.C\
	molecularMessage.C\
	windowEventTimer.C

include ../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)
