# $Id: Makefile,v 1.2 2006/02/21 16:25:24 anker Exp $

DIRECTORY=SCORING/COMMON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	baseFunction.C \
	linearBaseFunction.C \
	fermiBaseFunction.C \
	scoringComponent.C \
	scoringFunction.C \
	scoringTypes.C

include ../../common.mak
include .Dependencies
