# $Id: Makefile,v 1.1 2005/11/21 19:27:07 anker Exp $

DIRECTORY=SCORING/COMMON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	baseFunction.C\
	linearBaseFunction.C\
	fermiBaseFunction.C\
	scoringComponent.C\
	scoringFunction.C

include ../../common.mak
include .Dependencies
