mc = MainControl.getInstance(0)
ms = MolecularStructure.getInstance(0)
ff = ms.getForceField()
cm = mc.getCompositeManager()
c = cm.getComposites()
system = c[0]
mds = CanonicalMD()
o = Options()
ssm = SnapShotManager()
mds.setup(ff, ssm, o)
ff.setup(system)
mds.setup(ff, ssm, o)
mds.simulateIterations(5)
mds.setTimeStep(0.001)
mds.setReferenceTemperature(222)
mds.simulateIterations(500)
mc.update(system)
