DIRECTORY=STRUCTURE

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	analyticalSES.C\
	connolly.C\
	geometricProperties.C\
	geometricTransformations.C\
	numericalSAS.C\
	rotamerLibrary.C\
	structureMapper.C

include ../common.mak
