# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# Author:
#  Daniel Stoeckel
#

DIRECTORY=PLUGIN

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	BALLPlugin.C\
	pluginManager.C\
	pluginHandler.C

include ../common.mak
-include .Dependencies

.PHONY: all clean depend subdirs
