# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# Author:
#  Anne Dehof
#

.PHONY: all clean depend

DIRECTORY=EXTENSIONS/MULTITOUCH

all:
	@cd source; make all;

depend:
	@cd source; make depend;

clean:
	@cd source; make clean;

