DIRECTORY=KERNEL

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atom.C\
	atomContainer.C\
	bond.C\
	chain.C\
	expression.C\
	fragment.C\
	global.C\
	molecule.C\
	nucleicAcid.C\
	nucleotide.C\
	PDBAtom.C\
	protein.C\
	PTE.C\
	residue.C\
	secondaryStructure.C\
	selector.C\
	standardPredicates.C\
	system.C

include ../common.mak
include .Dependencies
