DIRECTORY=KERNEL

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atom.C\
	baseFragment.C\
	bond.C\
	chain.C\
	fragment.C\
	global.C\
	molecule.C\
	PDBAtom.C\
	protein.C\
	PSE.C\
	residue.C\
	secondaryStructure.C\
	selector.C\
	system.C

include ../common.mak
