# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
#
# Author:
#   Oliver Kohlbacher
#   Andreas Moll
#

DIRECTORY=VIEW/SOAP

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	soapC.C\
	soapClient.C\
	stdsoap2.C

#clean: 
#	@$(RM) -f *.o *moc*

include ../../common.mak
-include .Dependencies
