BALLVIEW_PATH = ..\..\..\source\Applications\BALLView

OBJS = \
$(BALLVIEW_PATH)\aboutDialog.obj\
$(BALLVIEW_PATH)\aboutDialog_moc.obj\
$(BALLVIEW_PATH)\demoTutorialDialog.obj\
$(BALLVIEW_PATH)\demoTutorialDialogData.obj\
$(BALLVIEW_PATH)\demoTutorialDialog_moc.obj\
$(BALLVIEW_PATH)\demoTutorialDialogData_moc.obj\
$(BALLVIEW_PATH)\mainframe.obj\
$(BALLVIEW_PATH)\mainframe_moc.obj\
$(BALLVIEW_PATH)\icons.obj\
$(BALLVIEW_PATH)\main.obj

UICS = \
$(BALLVIEW_PATH)\demoTutorialDialog.myui\
$(BALLVIEW_PATH)\aboutDialog.myui

MOCS = \
$(BALLVIEW_PATH)\aboutDialog.mymoc\
$(BALLVIEW_PATH)\demoTutorialDialog.mymoc\
$(BALLVIEW_PATH)\demoTutorialDialogData.mymoc\
$(BALLVIEW_PATH)\mainframe.mymoc