// $Id: common.h,v 1.2 1999/09/01 12:59:29 hekl Exp $

#ifndef BALL_MOLVIEW_COMMON_COMMON_H
#define BALL_MOLVIEW_COMMON_COMMON_H

#include <iostream.h>

#ifndef BALL_COMMON_H
#	include <BALL/common.h>
#endif

#ifndef BALL_VIEW_KERNEL_GEOMETRICOBJECT_H
#	include <BALL/VIEW/KERNEL/geometricObject.h>
#endif


#define BALL_MOLVIEW_PRINT_PROPERTY(property) \
	(hasProperty(property) ? "yes" : "no")

namespace BALL
{
	
	namespace MOLVIEW
	{
		enum Address
		{
			ADDRESS__UNKOWN                    = 0,
			ADDRESS__STATIC_MODEL              = 1,
			ADDRESS__DYNAMIC_MODEL             = 2,
			ADDRESS__TRANSPARENT_MODEL         = 3,
			ADDRESS__STATIC_DRAWING_PRECISION  = 4,
			ADDRESS__STATIC_DRAWING_MODE       = 5,
			ADDRESS__DYNAMIC_DRAWING_PRECISION = 6,
			ADDRESS__DYNAMIC_DRAWING_MODE      = 7
		};		

		enum Value
		{
			VALUE__MODEL_UNKOWN         = 0,
			VALUE__MODEL_LINES          = 1,
			VALUE__MODEL_STICK          = 2,
			VALUE__MODEL_BALL_AND_STICK = 3,
			VALUE__MODEL_VAN_DER_WAALS  = 4,

			VALUE__DRAWING_PRECISION_LOW    = 0,
			VALUE__DRAWING_PRECISION_MEDIUM = 1,
			VALUE__DRAWING_PRECISION_HIGH   = 2,
			VALUE__DRAWING_PRECISION_ULTRA  = 3,

			VALUE__DRAWING_MODE_DOTS      = 0,
			VALUE__DRAWING_MODE_WIREFRAME = 1,
			VALUE__DRAWING_MODE_SOLID     = 2
		};

		struct GeometricObject
		{
			enum Property
			{
				// Object Properties
				PROPERTY__OBJECT_STATIC = VIEW::GeometricObject::PROPERTY__OBJECT_STATIC,     // Default
				PROPERTY__OBJECT_DYNAMIC = VIEW::GeometricObject::PROPERTY__OBJECT_DYNAMIC,
				PROPERTY__OBJECT_TRANSPARENT = VIEW::GeometricObject::PROPERTY__OBJECT_TRANSPARENT,
				PROPERTY__OBJECT_OPAQUE = VIEW::GeometricObject::PROPERTY__OBJECT_OPAQUE,
				PROPERTY__OBJECT_VISIBLE = VIEW::GeometricObject::PROPERTY__OBJECT_VISIBLE,
				PROPERTY__OBJECT_HIDDEN = VIEW::GeometricObject::PROPERTY__OBJECT_HIDDEN,
				PROPERTY__OBJECT_OPENED = VIEW::GeometricObject::PROPERTY__OBJECT_OPENED,
				PROPERTY__OBJECT_CLOSED = VIEW::GeometricObject::PROPERTY__OBJECT_CLOSED,
				
				// DrawingMode Properties
				PROPERTY__DRAWING_MODE_DOTS = VIEW::GeometricObject::PROPERTY__DRAWING_MODE_DOTS,
				PROPERTY__DRAWING_MODE_WIREFRAME = VIEW::GeometricObject::PROPERTY__DRAWING_MODE_WIREFRAME,
				PROPERTY__DRAWING_MODE_SOLID = VIEW::GeometricObject::PROPERTY__DRAWING_MODE_SOLID,  // Default
				
				// DrawingPrecision Properties
				PROPERTY__DRAWING_PRECISION_LOW = VIEW::GeometricObject::PROPERTY__DRAWING_PRECISION_LOW,
				PROPERTY__DRAWING_PRECISION_MEDIUM = VIEW::GeometricObject::PROPERTY__DRAWING_PRECISION_MEDIUM,
				PROPERTY__DRAWING_PRECISION_HIGH = VIEW::GeometricObject::PROPERTY__DRAWING_PRECISION_HIGH,  // Default
				PROPERTY__DRAWING_PRECISION_ULTRA = VIEW::GeometricObject::PROPERTY__DRAWING_PRECISION_ULTRA,
				PROPERTY__DRAWING_PRECISION_USER_DEFINED = VIEW::GeometricObject::PROPERTY__DRAWING_PRECISION_USER_DEFINED,

				PROPERTY__FIRST_MODEL            = VIEW::GeometricObject::NUMBER_OF_PROPERTIES,
				PROPERTY__MODEL_VDW              = PROPERTY__FIRST_MODEL,
				PROPERTY__MODEL_DOTS,
				PROPERTY__MODEL_STARS,
				PROPERTY__MODELBALL_AND_STICK,
				PROPERTY__MODEL_LINES,
				PROPERTY__LAST_MODEL             = PROPERTY__MODEL_LINES,

				NUMBER_OF_PROPERTIES
			};
		};

#			ifndef BALL_NO_INLINE_FUNCTIONS
#				include <BALL/MOLVIEW/COMMON/common.iC>
#			endif

	} // namespace MOLVIEW

} // namespace BALL

#endif // BALL_MOLVIEW_COMMON_COMMON_H
