DIRECTORY=DATATYPE

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	binarySearchTree.C\
	bitVector.C\
	string.C\
	hashGrid.C\
	options.C\
	pointGrid.C\
	regExp.C\
	splayTree.C

include ../common.mak
include .Dependencies
