DIRECTORY=DATATYPE

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	bitVector.C\
	string.C\
	hashGrid.C\
	options.C\
	regExp.C\
	regularData1D.C\
	regularData2D.C\
	regularData3D.C

include ../common.mak
include .Dependencies
