# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
#
# Author:
#   Daniel Stoeckel
#

DIRECTORY=VIEW/PLUGIN

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	VIEWPlugin.C

include ../../common.mak
-include .Dependencies

