// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 07:14:17 2001

#ifndef _BALLInvalidRange_h
#define	_BALLInvalidRange_h


#include "sipBALLGeneralException.h"

#line 68 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLInvalidRange.h"

extern SIP_EXPORT PyObject *sipClass_InvalidRange;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_InvalidRange[];

extern "C" SIP_EXPORT const void *sipCast_InvalidRange Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_InvalidRange Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_InvalidRange Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_InvalidRange Py_PROTO((PyObject *,InvalidRange **,int,int *));
extern SIP_EXPORT InvalidRange *sipForceConvertTo_InvalidRange Py_PROTO((PyObject *,int *));

#endif
