// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug  7 17:20:37 2000

#ifndef _BALLAtomType_H
#define	_BALLAtomType_H


#line 115 "atom.sip"
	#include <BALL/KERNEL/atom.h>
	using namespace BALL;
	typedef Atom::Type AtomType;
#line 14 "../CPP/sipBALLAtomType.h"

extern SIP_EXPORT PyObject *sipClass_AtomType;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_AtomType[];

extern SIP_EXPORT const void *sipCast_AtomType Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_AtomType Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_AtomType Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_AtomType Py_PROTO((PyObject *,AtomType **,int,int *));
extern SIP_EXPORT AtomType *sipForceConvertTo_AtomType Py_PROTO((PyObject *,int *));

#endif
