// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Tue Jul 25 16:53:42 2000

#ifndef _BALLPeriodicBoundary_H
#define	_BALLPeriodicBoundary_H

#include "sipBALLForceField.h"
#include "sipBALLBox3.h"
#include "sipBALLString.h"
#include "sipBALLOptions.h"

#line 4 "periodicBoundary.sip"
#include <BALL/MOLMEC/COMMON/periodicBoundary.h>
using namespace BALL;
#line 17 "../CPP/sipBALLPeriodicBoundary.h"

extern SIP_EXPORT PyObject *sipClass_PeriodicBoundary;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_PeriodicBoundary[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_PeriodicBoundary[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_PeriodicBoundary[];

extern SIP_EXPORT const void *sipCast_PeriodicBoundary Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_PeriodicBoundary Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_PeriodicBoundary Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_PeriodicBoundary Py_PROTO((PyObject *,PeriodicBoundary **,int,int *));
extern SIP_EXPORT PeriodicBoundary *sipForceConvertTo_PeriodicBoundary Py_PROTO((PyObject *,int *));

#endif
