// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug 28 17:40:26 2000

#ifndef _BALLPyMoleculeList_H
#define	_BALLPyMoleculeList_H


#line 6 "pyMoleculeList.sip"
	#include <BALL/PYTHON/pyMoleculeList.h>
	#include "sipBALLMolecule.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 14 "../CPP/sipBALLPyMoleculeList.h"

extern SIP_EXPORT int sipCanConvertTo_PyMoleculeList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyMoleculeList Py_PROTO((PyObject *,PyMoleculeList **,int,int *));
extern SIP_EXPORT PyMoleculeList *sipForceConvertTo_PyMoleculeList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyMoleculeList Py_PROTO((const PyMoleculeList *));

#endif
