// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Tue Jul 25 00:09:32 2000

#ifndef _BALLGradient_H
#define	_BALLGradient_H

#include "sipBALLAtomVector.h"

#line 4 "gradient.sip"
#include <BALL/MOLMEC/COMMON/gradient.h>
using namespace BALL;
#line 14 "../CPP/sipBALLGradient.h"

extern SIP_EXPORT PyObject *sipClass_Gradient;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Gradient[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Gradient[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Gradient[];

extern SIP_EXPORT const void *sipCast_Gradient Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Gradient Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Gradient Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Gradient Py_PROTO((PyObject *,Gradient **,int,int *));
extern SIP_EXPORT Gradient *sipForceConvertTo_Gradient Py_PROTO((PyObject *,int *));

#endif
