// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:42 2001

#ifndef _BALLOptions_h
#define	_BALLOptions_h


#include "sipBALLIllegalKey.h"
#include "sipBALLString.h"
#include "sipBALLVector3.h"

#line 19 "options.sip"
	#include <BALL/DATATYPE/options.h>
	using namespace BALL;
#line 17 "sipBALLOptions.h"

extern SIP_EXPORT PyObject *sipClass_Options;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Options[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Options[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Options[];

extern "C" SIP_EXPORT const void *sipCast_Options Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Options Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Options Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Options Py_PROTO((PyObject *,Options **,int,int *));
extern SIP_EXPORT Options *sipForceConvertTo_Options Py_PROTO((PyObject *,int *));

#endif
