// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 20:01:05 2001

#ifndef _BALLFragmentDB_h
#define	_BALLFragmentDB_h


#include "sipBALLResourceEntry.h"
#include "sipBALLBuildBondsProcessor.h"
#include "sipBALLAddHydrogensProcessor.h"
#include "sipBALLNormalizeNamesProcessor.h"
#include "sipBALLString.h"
#include "sipBALLFragment.h"
#include "sipBALLResidue.h"
#include "sipBALLMolecule.h"

#line 6 "fragmentDB.sip"
	#include <BALL/STRUCTURE/fragmentDB.h>
	using namespace BALL;
#line 22 "sipBALLFragmentDB.h"

extern SIP_EXPORT PyObject *sipClass_FragmentDB;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_FragmentDB[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_FragmentDB[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_FragmentDB[];

extern "C" SIP_EXPORT const void *sipCast_FragmentDB Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_FragmentDB Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_FragmentDB Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_FragmentDB Py_PROTO((PyObject *,FragmentDB **,int,int *));
extern SIP_EXPORT FragmentDB *sipForceConvertTo_FragmentDB Py_PROTO((PyObject *,int *));

#endif
