// C++ interface header file.
//
// Generated by SIP v2.5pre4 on Sun Jul 29 13:00:58 2001

#ifndef _BALLBitVector_h
#define	_BALLBitVector_h


#include "sipBALLOutOfMemory.h"
#include "sipBALLIndexUnderflow.h"
#include "sipBALLIndexOverflow.h"
#include "sipBALLIndex.h"

#line 31 "bitVector.sip"
	#include <BALL/DATATYPE/bitVector.h>
	using namespace BALL;
	using namespace BALL::Exception;
	typedef unsigned char BlockType;
#line 20 "sipBALLBitVector.h"

extern SIP_EXPORT PyObject *sipClass_BitVector;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_BitVector[];

extern SIP_EXPORT const void *sipCast_BitVector Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_BitVector Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_BitVector Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_BitVector Py_PROTO((PyObject *,BitVector **,int,int *));
extern SIP_EXPORT BitVector *sipForceConvertTo_BitVector Py_PROTO((PyObject *,int *));

#endif
