// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:41 2001

#ifndef _BALLPlane3_h
#define	_BALLPlane3_h


#include "sipBALLVector3.h"
#include "sipBALLLine3.h"

#line 6 "plane3.sip"
	#include <BALL/MATHS/plane3.h>
	using namespace BALL;
#line 16 "sipBALLPlane3.h"

extern SIP_EXPORT PyObject *sipClass_Plane3;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Plane3[];

extern "C" SIP_EXPORT const void *sipCast_Plane3 Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Plane3 Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Plane3 Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Plane3 Py_PROTO((PyObject *,Plane3 **,int,int *));
extern SIP_EXPORT Plane3 *sipForceConvertTo_Plane3 Py_PROTO((PyObject *,int *));

#endif
