// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug  7 17:20:37 2000

#ifndef _BALLPyFragmentList_H
#define	_BALLPyFragmentList_H


#line 6 "pyFragmentList.sip"
	#include <BALL/PYTHON/pyFragmentList.h>
	#include "sipBALLFragment.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 14 "../CPP/sipBALLPyFragmentList.h"

extern SIP_EXPORT int sipCanConvertTo_PyFragmentList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyFragmentList Py_PROTO((PyObject *,PyFragmentList **,int,int *));
extern SIP_EXPORT PyFragmentList *sipForceConvertTo_PyFragmentList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyFragmentList Py_PROTO((const PyFragmentList *));

#endif
