// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLPropertyManager_H
#define	_BALLPropertyManager_H

#include "sipBALLNamedProperty.h"
#include "sipBALLString.h"
#include "sipBALLPersistentObject.h"


extern SIP_EXPORT PyObject *sipClass_PropertyManager;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_PropertyManager[];

extern SIP_EXPORT const void *sipCast_PropertyManager Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_PropertyManager Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_PropertyManager Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_PropertyManager Py_PROTO((PyObject *,PropertyManager **,int,int *));
extern SIP_EXPORT PropertyManager *sipForceConvertTo_PropertyManager Py_PROTO((PyObject *,int *));

#endif
