// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 20:01:05 2001

#ifndef _BALLPyResidueList_h
#define	_BALLPyResidueList_h

#line 6 "pyResidueList.sip"
	#include <BALL/PYTHON/pyResidueList.h>
	#include "sipBALLResidue.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 13 "sipBALLPyResidueList.h"

extern SIP_EXPORT int sipCanConvertTo_PyResidueList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyResidueList Py_PROTO((PyObject *,PyResidueList **,int,int *));
extern SIP_EXPORT PyResidueList *sipForceConvertTo_PyResidueList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyResidueList Py_PROTO((const PyResidueList *));

#endif
