// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 21:25:05 2001

#ifndef _BALLChargeRuleProcessor_h
#define	_BALLChargeRuleProcessor_h


#include "sipBALLRuleProcessor.h"
#include "sipBALLINIFile.h"
#include "sipBALLString.h"
#include "sipBALLAtom.h"

#line 8 "chargeRuleProcessor.sip"
	#include <BALL/MOLMEC/COMMON/chargeRuleProcessor.h>
#line 17 "sipBALLChargeRuleProcessor.h"

extern SIP_EXPORT PyObject *sipClass_ChargeRuleProcessor;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_ChargeRuleProcessor[];

extern "C" SIP_EXPORT const void *sipCast_ChargeRuleProcessor Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_ChargeRuleProcessor Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipChargeRuleProcessor : public ChargeRuleProcessor
{
public:
	sipChargeRuleProcessor();
	sipChargeRuleProcessor(INIFile&,const String&);
	sipChargeRuleProcessor(const ChargeRuleProcessor&);
	~sipChargeRuleProcessor();
	bool finish();
	bool start();
	Processor::Result operator()(Atom&);

	sipThisType *sipPyThis;

private:
	sipChargeRuleProcessor(const sipChargeRuleProcessor &);
	sipChargeRuleProcessor &operator = (const sipChargeRuleProcessor &);

	sipMethodCache sipPyMethods[3];
};

extern SIP_EXPORT int sipCanConvertTo_ChargeRuleProcessor Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_ChargeRuleProcessor Py_PROTO((PyObject *,ChargeRuleProcessor **,int,int *));
extern SIP_EXPORT ChargeRuleProcessor *sipForceConvertTo_ChargeRuleProcessor Py_PROTO((PyObject *,int *));

#endif
