// C++ interface header file.
//
// Generated by SIP v2.5pre4 on Sun Jul 29 13:00:59 2001

#ifndef _BALLSizeUnderflow_h
#define	_BALLSizeUnderflow_h


#include "sipBALLGeneralException.h"

#line 45 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLSizeUnderflow.h"

extern SIP_EXPORT PyObject *sipClass_SizeUnderflow;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_SizeUnderflow[];

extern SIP_EXPORT const void *sipCast_SizeUnderflow Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_SizeUnderflow Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_SizeUnderflow Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_SizeUnderflow Py_PROTO((PyObject *,SizeUnderflow **,int,int *));
extern SIP_EXPORT SizeUnderflow *sipForceConvertTo_SizeUnderflow Py_PROTO((PyObject *,int *));

#endif
