// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 20:01:05 2001

#ifndef _BALLAmberBend_h
#define	_BALLAmberBend_h


#include "sipBALLForceFieldComponent.h"
#include "sipBALLForceField.h"

#line 7 "amberBend.sip"
	#include <BALL/MOLMEC/AMBER/amberBend.h>
	using namespace BALL;
#line 16 "sipBALLAmberBend.h"

extern SIP_EXPORT PyObject *sipClass_AmberBend;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_AmberBend[];

extern "C" SIP_EXPORT const void *sipCast_AmberBend Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_AmberBend Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipAmberBend : public AmberBend
{
public:
	sipAmberBend();
	sipAmberBend(ForceField&);
	sipAmberBend(const AmberBend&,bool);
	sipAmberBend(const AmberBend&);
	~sipAmberBend();
	double getEnergy() const;
	void updateForces();
	double updateEnergy();
	bool setup();

	sipThisType *sipPyThis;

private:
	sipAmberBend(const sipAmberBend &);
	sipAmberBend &operator = (const sipAmberBend &);

	sipMethodCache sipPyMethods[4];
};

extern SIP_EXPORT int sipCanConvertTo_AmberBend Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_AmberBend Py_PROTO((PyObject *,AmberBend **,int,int *));
extern SIP_EXPORT AmberBend *sipForceConvertTo_AmberBend Py_PROTO((PyObject *,int *));

#endif
