// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 07:14:17 2001

#ifndef _BALLOutOfMemory_h
#define	_BALLOutOfMemory_h


#include "sipBALLGeneralException.h"

#line 152 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLOutOfMemory.h"

extern SIP_EXPORT PyObject *sipClass_OutOfMemory;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_OutOfMemory[];

extern "C" SIP_EXPORT const void *sipCast_OutOfMemory Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_OutOfMemory Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_OutOfMemory Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_OutOfMemory Py_PROTO((PyObject *,OutOfMemory **,int,int *));
extern SIP_EXPORT OutOfMemory *sipForceConvertTo_OutOfMemory Py_PROTO((PyObject *,int *));

#endif
