// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Mon Aug 20 19:50:40 2001

#ifndef _BALLGradient_h
#define	_BALLGradient_h


#include "sipBALLAtomVector.h"

#line 4 "gradient.sip"
#include <BALL/MOLMEC/COMMON/gradient.h>
using namespace BALL;
#line 15 "sipBALLGradient.h"

extern SIP_EXPORT PyObject *sipClass_Gradient;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Gradient[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Gradient[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Gradient[];

extern "C" SIP_EXPORT const void *sipCast_Gradient Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Gradient Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Gradient Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Gradient Py_PROTO((PyObject *,Gradient **,int,int *));
extern SIP_EXPORT Gradient *sipForceConvertTo_Gradient Py_PROTO((PyObject *,int *));

#endif
