// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 21:25:05 2001

#ifndef _BALLElement_h
#define	_BALLElement_h


#include "sipBALLPropertyManager.h"
#include "sipBALLString.h"

#line 5 "PTE.sip"
	#include <BALL/KERNEL/PTE.h>
	using namespace BALL;
#line 16 "sipBALLElement.h"

extern SIP_EXPORT PyObject *sipClass_Element;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Element[];

extern "C" SIP_EXPORT const void *sipCast_Element Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Element Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Element Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Element Py_PROTO((PyObject *,Element **,int,int *));
extern SIP_EXPORT Element *sipForceConvertTo_Element Py_PROTO((PyObject *,int *));

#endif
