// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:41 2001

#ifndef _BALLFragment_h
#define	_BALLFragment_h


#include "sipBALLAtomContainer.h"
#include "sipBALLString.h"

#line 7 "fragment.sip"
	#include <BALL/KERNEL/fragment.h>
	using namespace BALL;
#line 16 "sipBALLFragment.h"

extern SIP_EXPORT PyObject *sipClass_Fragment;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Fragment[];

extern "C" SIP_EXPORT const void *sipCast_Fragment Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Fragment Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipFragment : public Fragment
{
public:
	sipFragment();
	sipFragment(const Fragment&,bool);
	sipFragment(const String&);
	sipFragment(const Fragment&);
	~sipFragment() throw();
	void deselect() throw();
	void select() throw();
	bool isValid() const throw();
	void destroy() throw();
	void clear() throw();

	sipThisType *sipPyThis;

private:
	sipFragment(const sipFragment &);
	sipFragment &operator = (const sipFragment &);

	sipMethodCache sipPyMethods[5];
};

extern SIP_EXPORT int sipCanConvertTo_Fragment Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Fragment Py_PROTO((PyObject *,Fragment **,int,int *));
extern SIP_EXPORT Fragment *sipForceConvertTo_Fragment Py_PROTO((PyObject *,int *));

#endif
