// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Mon Aug 20 19:50:40 2001

#ifndef _BALLPyAtomDict_h
#define	_BALLPyAtomDict_h

#line 6 "pyAtomDict.sip"
	#include <BALL/DATATYPE/hashMap.h>
	#include "sipBALLAtom.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
	typedef HashMap<const Atom*, float> PyAtomDict;
#line 14 "sipBALLPyAtomDict.h"

extern SIP_EXPORT int sipCanConvertTo_PyAtomDict Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyAtomDict Py_PROTO((PyObject *,PyAtomDict **,int,int *));
extern SIP_EXPORT PyAtomDict *sipForceConvertTo_PyAtomDict Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyAtomDict Py_PROTO((const PyAtomDict *));

#endif
