// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 19:54:49 2001

#ifndef _BALLConstants_h
#define	_BALLConstants_h



#line 5 "constants.sip"
	#include <BALL/COMMON/constants.h>
	using namespace BALL;
#line 14 "sipBALLConstants.h"

extern SIP_EXPORT PyObject *sipClass_Constants;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Constants[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Constants[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Constants[];

extern "C" SIP_EXPORT const void *sipCast_Constants Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Constants Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Constants Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Constants Py_PROTO((PyObject *,Constants **,int,int *));
extern SIP_EXPORT Constants *sipForceConvertTo_Constants Py_PROTO((PyObject *,int *));

#endif
