// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug  7 17:20:37 2000

#ifndef _BALLResidue_H
#define	_BALLResidue_H

#include "sipBALLFragment.h"
#include "sipBALLString.h"
#include "sipBALLProtein.h"
#include "sipBALLChain.h"
#include "sipBALLPDBAtom.h"
#include "sipBALLComposite.h"

#line 7 "residue.sip"
	#include <BALL/KERNEL/residue.h>
	using namespace BALL;
#line 19 "../CPP/sipBALLResidue.h"

extern SIP_EXPORT PyObject *sipClass_Residue;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Residue[];

extern SIP_EXPORT const void *sipCast_Residue Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Residue Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipResidue : public Residue
{
public:
	sipResidue();
	sipResidue(const Residue&,bool);
	sipResidue(const String&,const String&,char);
	sipResidue(const Residue&);
	~sipResidue();

       // There is a catcher function for every virtual member function in
       // the class hierachy.

	void select();
	void deselect();
	void clear();
	void destroy();
	bool isValid() const;

	sipThisType *sipPyThis;

private:
	sipMethodCache sipPyMethods[5];
};

extern SIP_EXPORT int sipCanConvertTo_Residue Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Residue Py_PROTO((PyObject *,Residue **,int,int *));
extern SIP_EXPORT Residue *sipForceConvertTo_Residue Py_PROTO((PyObject *,int *));

#endif
