// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLPDBFile_H
#define	_BALLPDBFile_H

#include "sipBALLString.h"
#include "sipBALLstd__openmode.h"
#include "sipBALLProtein.h"
#include "sipBALLSystem.h"

#line 6 "PDBFile.sip"
	#include <BALL/FORMAT/PDBFile.h>
	using namespace BALL;
#line 17 "sipBALLPDBFile.h"

extern SIP_EXPORT PyObject *sipClass_PDBFile;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_PDBFile[];

extern SIP_EXPORT const void *sipCast_PDBFile Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_PDBFile Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipPDBFile : public PDBFile
{
public:
	sipPDBFile();
	sipPDBFile(const String&,std__openmode);
	sipPDBFile(const PDBFile&);
	~sipPDBFile() throw();
	void write(const System&);
	static void sipVH_write(const sipMethodCache *,sipThisType *,int,const System&);
	void write(const Protein&);
	static void sipVH_write(const sipMethodCache *,sipThisType *,int,const Protein&);
	void read(System&);
	static void sipVH_read(const sipMethodCache *,sipThisType *,int,System&);
	void read(Protein&);
	static void sipVH_read(const sipMethodCache *,sipThisType *,int,Protein&);

	sipThisType *sipPyThis;

private:
	sipPDBFile(const sipPDBFile &);
	sipPDBFile &operator = (const sipPDBFile &);

	sipMethodCache sipPyMethods[4];
};

extern SIP_EXPORT int sipCanConvertTo_PDBFile Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_PDBFile Py_PROTO((PyObject *,PDBFile **,int,int *));
extern SIP_EXPORT PDBFile *sipForceConvertTo_PDBFile Py_PROTO((PyObject *,int *));

#endif
