// C++ interface wrapper code.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 18:57:03 2001

#include "sipBALLDeclBALL.h"
#include "sipBALLIndex.h"


int sipCanConvertTo_Index(PyObject *sipPy)
{
#line 11 "global.sip"
	// automatic conversion of Py integers to Position 
	return PyInt_Check(sipPy);
#line 15 "sipBALLIndex.cpp"
}

int sipConvertTo_Index(PyObject *sipPy,Index **sipCppPtr,int sipWillDeref,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return 0;

#line 15 "global.sip"
	if (PyInt_Check(sipPy))
	{
		*sipCppPtr = new Index(PyInt_AS_LONG(sipPy));
	
		return 1;
	}
	
	return 0;
#line 32 "sipBALLIndex.cpp"
}

Index *sipForceConvertTo_Index(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_Index(valobj))
	{
		Index *val;

		sipConvertTo_Index(valobj,&val,0,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_Index);

	*iserrp = 1;

	return NULL;
}

PyObject *sipConvertFrom_Index(const Index *sipCpp)
{
#line 25 "global.sip"
	return NULL;
#line 60 "sipBALLIndex.cpp"
}
