// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 20:01:05 2001

#ifndef _BALLOutOfGrid_h
#define	_BALLOutOfGrid_h


#include "sipBALLGeneralException.h"

#line 165 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLOutOfGrid.h"

extern SIP_EXPORT PyObject *sipClass_OutOfGrid;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_OutOfGrid[];

extern "C" SIP_EXPORT const void *sipCast_OutOfGrid Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_OutOfGrid Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_OutOfGrid Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_OutOfGrid Py_PROTO((PyObject *,OutOfGrid **,int,int *));
extern SIP_EXPORT OutOfGrid *sipForceConvertTo_OutOfGrid Py_PROTO((PyObject *,int *));

#endif
