// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLTimeStamp_H
#define	_BALLTimeStamp_H

#include "sipBALLPreciseTime.h"

#line 49 "timeStamp.sip"
	#include <BALL/CONCEPT/timeStamp.h>
	using namespace BALL;
#line 14 "sipBALLTimeStamp.h"

extern SIP_EXPORT PyObject *sipClass_TimeStamp;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_TimeStamp[];

extern SIP_EXPORT const void *sipCast_TimeStamp Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_TimeStamp Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipTimeStamp : public TimeStamp
{
public:
	sipTimeStamp() throw();
	sipTimeStamp(const TimeStamp&);
	~sipTimeStamp() throw();
	void stamp(const PreciseTime&) throw();
	static void sipVH_stamp(const sipMethodCache *,sipThisType *,int,const PreciseTime&);

	sipThisType *sipPyThis;

private:
	sipTimeStamp(const sipTimeStamp &);
	sipTimeStamp &operator = (const sipTimeStamp &);

	sipMethodCache sipPyMethods[1];
};

extern SIP_EXPORT int sipCanConvertTo_TimeStamp Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_TimeStamp Py_PROTO((PyObject *,TimeStamp **,int,int *));
extern SIP_EXPORT TimeStamp *sipForceConvertTo_TimeStamp Py_PROTO((PyObject *,int *));

#endif
