// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Sat Jul 15 18:37:07 2000

#ifndef _BALLPointGrid_H
#define	_BALLPointGrid_H

#include "sipBALLSize.h"
#include "sipBALLVector3.h"
#include "sipBALLGridIndex.h"
#include "sipBALLPosition.h"

#line 20 "pointGrid.sip"
	#include <BALL/DATATYPE/pointGrid.h>
	typedef BALL::PointGrid<float> PointGrid;
#line 17 "./sipBALLPointGrid.h"

extern SIP_EXPORT PyObject *sipClass_PointGrid;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_PointGrid[];

extern SIP_EXPORT const void *sipCast_PointGrid Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_PointGrid Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_PointGrid Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_PointGrid Py_PROTO((PyObject *,PointGrid **,int,int *));
extern SIP_EXPORT PointGrid *sipForceConvertTo_PointGrid Py_PROTO((PyObject *,int *));

#endif
