// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLSurface_H
#define	_BALLSurface_H

#include "sipBALLString.h"

#line 6 "surface.sip"
	#include <BALL/MATHS/surface.h>
	using namespace BALL;
#line 14 "sipBALLSurface.h"

extern SIP_EXPORT PyObject *sipClass_Surface;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Surface[];

extern SIP_EXPORT const void *sipCast_Surface Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Surface Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Surface Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Surface Py_PROTO((PyObject *,Surface **,int,int *));
extern SIP_EXPORT Surface *sipForceConvertTo_Surface Py_PROTO((PyObject *,int *));

#endif
