// C++ interface header file.
//
// Generated by SIP v2.5pre4 on Sun Jul 29 13:00:59 2001

#ifndef _BALLIndexOverflow_h
#define	_BALLIndexOverflow_h


#include "sipBALLGeneralException.h"
#include "sipBALLIndex.h"

#line 56 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 17 "sipBALLIndexOverflow.h"

extern SIP_EXPORT PyObject *sipClass_IndexOverflow;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_IndexOverflow[];

extern SIP_EXPORT const void *sipCast_IndexOverflow Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_IndexOverflow Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_IndexOverflow Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_IndexOverflow Py_PROTO((PyObject *,IndexOverflow **,int,int *));
extern SIP_EXPORT IndexOverflow *sipForceConvertTo_IndexOverflow Py_PROTO((PyObject *,int *));

#endif
