// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 07:14:16 2001

#ifndef _BALLNormalizeNamesProcessor_h
#define	_BALLNormalizeNamesProcessor_h


#include "sipBALLFragmentProcessor.h"
#include "sipBALLFragmentDB.h"
#include "sipBALLString.h"
#include "sipBALLFragment.h"

#line 68 "fragmentDB.sip"
	#include <BALL/STRUCTURE/fragmentDB.h>
	typedef FragmentDB::NormalizeNamesProcessor NormalizeNamesProcessor;
	using namespace BALL;
#line 19 "sipBALLNormalizeNamesProcessor.h"

extern SIP_EXPORT PyObject *sipClass_NormalizeNamesProcessor;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_NormalizeNamesProcessor[];

extern "C" SIP_EXPORT const void *sipCast_NormalizeNamesProcessor Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_NormalizeNamesProcessor Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipNormalizeNamesProcessor : public NormalizeNamesProcessor
{
public:
	sipNormalizeNamesProcessor();
	sipNormalizeNamesProcessor(FragmentDB&);
	sipNormalizeNamesProcessor(const NormalizeNamesProcessor&);
	~sipNormalizeNamesProcessor();
	Processor::Result operator()(Fragment&);
	bool finish();
	static bool sipVH_finish(const sipMethodCache *,sipThisType *,int);
	bool start();
	static bool sipVH_start(const sipMethodCache *,sipThisType *,int);

	sipThisType *sipPyThis;

private:
	sipNormalizeNamesProcessor(const sipNormalizeNamesProcessor &);
	sipNormalizeNamesProcessor &operator = (const sipNormalizeNamesProcessor &);

	sipMethodCache sipPyMethods[3];
};

extern SIP_EXPORT int sipCanConvertTo_NormalizeNamesProcessor Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_NormalizeNamesProcessor Py_PROTO((PyObject *,NormalizeNamesProcessor **,int,int *));
extern SIP_EXPORT NormalizeNamesProcessor *sipForceConvertTo_NormalizeNamesProcessor Py_PROTO((PyObject *,int *));

#endif
