// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLTransformationProcessor_H
#define	_BALLTransformationProcessor_H

#include "sipBALLAtomProcessor.h"
#include "sipBALLMatrix4x4.h"
#include "sipBALLAtom.h"

#line 25 "geometricTransformations.sip"
	#include <BALL/STRUCTURE/geometricTransformations.h>
	using namespace BALL;
	typedef UnaryProcessor<Atom> AtomProcessor;
#line 17 "sipBALLTransformationProcessor.h"

extern SIP_EXPORT PyObject *sipClass_TransformationProcessor;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_TransformationProcessor[];

extern SIP_EXPORT const void *sipCast_TransformationProcessor Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_TransformationProcessor Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipTransformationProcessor : public TransformationProcessor
{
public:
	sipTransformationProcessor();
	sipTransformationProcessor(const Matrix4x4&);
	sipTransformationProcessor(const TransformationProcessor&);
	~sipTransformationProcessor();
	Processor::Result operator ()(Atom&);

	sipThisType *sipPyThis;

private:
	sipTransformationProcessor(const sipTransformationProcessor &);
	sipTransformationProcessor &operator = (const sipTransformationProcessor &);

	sipMethodCache sipPyMethods[1];
};

extern SIP_EXPORT int sipCanConvertTo_TransformationProcessor Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_TransformationProcessor Py_PROTO((PyObject *,TransformationProcessor **,int,int *));
extern SIP_EXPORT TransformationProcessor *sipForceConvertTo_TransformationProcessor Py_PROTO((PyObject *,int *));

#endif
