// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug 28 17:40:28 2000

#ifndef _BALLProcessor_H
#define	_BALLProcessor_H


#line 6 "processor.sip"
	#include <BALL/CONCEPT/processor.h>
	using namespace BALL;
#line 13 "../CPP/sipBALLProcessor.h"

extern SIP_EXPORT PyObject *sipClass_Processor;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Processor[];

extern SIP_EXPORT const void *sipCast_Processor Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Processor Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Processor Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Processor Py_PROTO((PyObject *,Processor **,int,int *));
extern SIP_EXPORT Processor *sipForceConvertTo_Processor Py_PROTO((PyObject *,int *));

#endif
