// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Mon Aug  7 19:45:42 2000

#ifndef _BALLAngle_H
#define	_BALLAngle_H


#line 4 "angle.sip"
#include <BALL/MATHS/angle.h>
using namespace BALL;
#line 13 "../CPP/sipBALLAngle.h"

extern SIP_EXPORT PyObject *sipClass_Angle;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Angle[];

extern SIP_EXPORT const void *sipCast_Angle Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Angle Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Angle Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Angle Py_PROTO((PyObject *,Angle **,int,int *));
extern SIP_EXPORT Angle *sipForceConvertTo_Angle Py_PROTO((PyObject *,int *));

#endif
