// C++ interface wrapper code.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 18:57:03 2001

#include "sipBALLDeclBALL.h"
#include "sipBALLAtomVector.h"


PyObject *sipClass_AtomVector;

static void sipDealloc_AtomVector(sipThisType *);

static PyTypeObject sipType_AtomVector = {
	PyObject_HEAD_INIT(&PyType_Type)
	0,
	sipName_BALL_AtomVector,
	sizeof (sipThisType),
	0,
	(destructor)sipDealloc_AtomVector,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	Py_TPFLAGS_DEFAULT,
	0,
	0,
	0,
};

extern "C" PyObject *sipDo_AtomVector_clear(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,""))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

   try
   {
			ptr -> AtomVector::clear();
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_clear);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_set(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		const AtomVector * a0;
		PyObject *a0obj;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"I",sipCanConvertTo_AtomVector,&a0obj))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_AtomVector(a0obj,(AtomVector **)&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			ptr -> AtomVector::set(* a0);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	{
		const Composite * a0;
		PyObject *a0obj;
		long a1;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"Il",sipCanConvertTo_Composite,&a0obj,&a1))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Composite(a0obj,(Composite **)&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			ptr -> AtomVector::set(* a0, (bool)a1);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_set);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_size(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,""))
		{
			int res;
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

   try
   {
			res = ptr -> AtomVector::size();
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_size);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_savePositions(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,""))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

   try
   {
			ptr -> AtomVector::savePositions();
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_savePositions);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_resetPositions(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,""))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

   try
   {
			ptr -> AtomVector::resetPositions();
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_resetPositions);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_moveTo(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		const Gradient * a0;
		PyObject *a0obj;
		float a1;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"If",sipCanConvertTo_Gradient,&a0obj,&a1))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Gradient(a0obj,(Gradient **)&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			ptr -> AtomVector::moveTo(* a0, a1);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_moveTo);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_push_back(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		Atom * a0;
		PyObject *a0obj;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"I",sipCanConvertTo_Atom,&a0obj))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,0,&iserr);

			if (iserr)
				return NULL;

   try
   {
			ptr -> AtomVector::push_back( a0);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_push_back);

	return NULL;
}

extern "C" PyObject *sipDo_AtomVector_resize(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;
	int sipArgsParsed = 0;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_AtomVector)) == NULL)
		return NULL;

	{
		int a0;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"i",&a0))
		{
			AtomVector *ptr;

			if ((ptr = (AtomVector *)sipGetCppPtr(sipThis,sipClass_AtomVector)) == NULL)
				return NULL;

   try
   {
			ptr -> AtomVector::resize( a0);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipArgsParsed,sipName_BALL_AtomVector,sipName_BALL_resize);

	return NULL;
}

// Cast a pointer to a type somewhere in its superclass hierachy.

extern "C" const void *sipCast_AtomVector(const void *ptr,PyObject *targetClass)
{
	if (targetClass == sipClass_AtomVector)
		return ptr;

	return NULL;
}

static void sipDealloc_AtomVector(sipThisType *sipThis)
{
	if (sipThis -> u.cppPtr != NULL)
	{
		if (sipIsPyOwned(sipThis))
			delete (AtomVector *)sipThis -> u.cppPtr;
	}

	sipDeleteThis(sipThis);
}

PyObject *sipNew_AtomVector(PyObject *sipSelf,PyObject *sipArgs)
{
	static sipExtraType et = {
		sipCast_AtomVector
	};

	sipThisType *sipThis = NULL;
	const void *sipNew = NULL;
	int sipFlags = SIP_PY_OWNED;
	int sipArgsParsed = 0;

	// See if there is something pending.

	sipNew = sipGetPending(&sipFlags);

	if (sipNew == NULL)
	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,"-"))
		{
   try
   {
			sipNew = new AtomVector();
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}
		}
	}

	if (sipNew == NULL)
	{
		Composite * a0;
		PyObject *a0obj;
		long a1;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"-Il",sipCanConvertTo_Composite,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_Composite(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			sipNew = new AtomVector(* a0, (bool)a1);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}
		}
	}

	if (sipNew == NULL)
	{
		AtomVector * a0;
		PyObject *a0obj;
		long a1;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"-Il",sipCanConvertTo_AtomVector,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_AtomVector(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			sipNew = new AtomVector(* a0, (bool)a1);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}
		}
	}

	if (sipNew == NULL)
	{
		const AtomVector * a0;
		PyObject *a0obj;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"-I",sipCanConvertTo_AtomVector,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_AtomVector(a0obj,(AtomVector **)&a0,1,&iserr);

			if (iserr)
				return NULL;

   try
   {
			sipNew = new AtomVector(* a0);
   }
   catch (...)
    {
      PyErr_SetString(PyExc_Exception, "unknown");
      return NULL;
		}
		}
	}

	if (sipNew == NULL)
	{
		sipNoCtor(sipArgsParsed,sipName_BALL_AtomVector);
		return NULL;
	}

	// Wrap the object.

	if ((sipThis = sipCreateThis(sipSelf,sipNew,&sipType_AtomVector,sipFlags,&et)) == NULL)
	{
		if (sipFlags & SIP_PY_OWNED)
			delete (AtomVector *)sipNew;

		return NULL;
	}

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef sipClassAttrTab_AtomVector[] = {
	{sipName_BALL_clear, sipDo_AtomVector_clear, METH_VARARGS, NULL},
	{sipName_BALL_set, sipDo_AtomVector_set, METH_VARARGS, NULL},
	{sipName_BALL_size, sipDo_AtomVector_size, METH_VARARGS, NULL},
	{sipName_BALL_savePositions, sipDo_AtomVector_savePositions, METH_VARARGS, NULL},
	{sipName_BALL_resetPositions, sipDo_AtomVector_resetPositions, METH_VARARGS, NULL},
	{sipName_BALL_moveTo, sipDo_AtomVector_moveTo, METH_VARARGS, NULL},
	{sipName_BALL_push_back, sipDo_AtomVector_push_back, METH_VARARGS, NULL},
	{sipName_BALL_resize, sipDo_AtomVector_resize, METH_VARARGS, NULL},
	{NULL}
};

int sipCanConvertTo_AtomVector(PyObject *sipPy)
{
	return sipIsSubClassInstance(sipPy,sipClass_AtomVector);
}

void sipConvertTo_AtomVector(PyObject *sipPy,AtomVector **sipCppPtr,int sipWillDeref,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return;

	if (sipPy == Py_None)
	{
		sipCheckNone(sipWillDeref,sipIsErr,sipName_BALL_AtomVector);
		*sipCppPtr = NULL;

		return;
	}

	*sipCppPtr = (AtomVector *)sipConvertToCpp(sipPy,sipClass_AtomVector,sipIsErr);
}

AtomVector *sipForceConvertTo_AtomVector(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_AtomVector(valobj))
	{
		AtomVector *val;

		sipConvertTo_AtomVector(valobj,&val,0,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_AtomVector);

	*iserrp = 1;

	return NULL;
}
