// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Thu Jan 11 16:41:23 2001

#ifndef _BALLBond_H
#define	_BALLBond_H

#include "sipBALLComposite.h"
#include "sipBALLPropertyManager.h"
#include "sipBALLString.h"
#include "sipBALLAtom.h"
#include "sipBALLAtomContainer.h"
#include "sipBALLSystem.h"

#line 8 "bond.sip"
	#include <BALL/KERNEL/bond.h>
	#include <BALL/KERNEL/atom.h>
	using namespace BALL;
#line 20 "../CPP/sipBALLBond.h"

extern SIP_EXPORT PyObject *sipClass_Bond;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Bond[];

extern SIP_EXPORT const void *sipCast_Bond Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Bond Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipBond : public Bond
{
public:
	sipBond();
	sipBond(const Bond&,bool);
	sipBond(const String&,Atom&,Atom&,short,short);
	sipBond(const Bond&);
	~sipBond();

       // There is a catcher function for every virtual member function in
       // the class hierachy.

	void select();
	void deselect();
	void clear();
	void destroy();
	bool isValid() const;

	sipThisType *sipPyThis;

private:
	sipMethodCache sipPyMethods[5];
};

extern SIP_EXPORT int sipCanConvertTo_Bond Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Bond Py_PROTO((PyObject *,Bond **,int,int *));
extern SIP_EXPORT Bond *sipForceConvertTo_Bond Py_PROTO((PyObject *,int *));

#endif
