// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:42 2001

#ifndef _BALLGlobalExceptionHandler_h
#define	_BALLGlobalExceptionHandler_h


#include "sipBALLString.h"

#line 215 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLGlobalExceptionHandler.h"

extern SIP_EXPORT PyObject *sipClass_GlobalExceptionHandler;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_GlobalExceptionHandler[];

extern "C" SIP_EXPORT const void *sipCast_GlobalExceptionHandler Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_GlobalExceptionHandler Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_GlobalExceptionHandler Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_GlobalExceptionHandler Py_PROTO((PyObject *,GlobalExceptionHandler **,int,int *));
extern SIP_EXPORT GlobalExceptionHandler *sipForceConvertTo_GlobalExceptionHandler Py_PROTO((PyObject *,int *));

#endif
