// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Fri Jan 26 17:38:00 2001

#ifndef _BALLPyNucleotideList_H
#define	_BALLPyNucleotideList_H


#line 6 "pyNucleotideList.sip"
	#include <BALL/PYTHON/pyNucleotideList.h>
	#include "sipBALLNucleotide.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 14 "../CPP/sipBALLPyNucleotideList.h"

extern SIP_EXPORT int sipCanConvertTo_PyNucleotideList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyNucleotideList Py_PROTO((PyObject *,PyNucleotideList **,int,int *));
extern SIP_EXPORT PyNucleotideList *sipForceConvertTo_PyNucleotideList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyNucleotideList Py_PROTO((const PyNucleotideList *));

#endif
