// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:41 2001

#ifndef _BALLCharmmImproperTorsion_h
#define	_BALLCharmmImproperTorsion_h


#include "sipBALLForceFieldComponent.h"
#include "sipBALLForceField.h"

#line 7 "charmmImproperTorsion.sip"
	#include <BALL/MOLMEC/CHARMM/charmmImproperTorsion.h>
	using namespace BALL;
#line 16 "sipBALLCharmmImproperTorsion.h"

extern SIP_EXPORT PyObject *sipClass_CharmmImproperTorsion;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_CharmmImproperTorsion[];

extern "C" SIP_EXPORT const void *sipCast_CharmmImproperTorsion Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_CharmmImproperTorsion Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipCharmmImproperTorsion : public CharmmImproperTorsion
{
public:
	sipCharmmImproperTorsion();
	sipCharmmImproperTorsion(ForceField&);
	sipCharmmImproperTorsion(const CharmmImproperTorsion&,bool);
	sipCharmmImproperTorsion(const CharmmImproperTorsion&);
	~sipCharmmImproperTorsion();
	double getEnergy() const;
	void updateForces();
	double updateEnergy();
	bool setup();

	sipThisType *sipPyThis;

private:
	sipCharmmImproperTorsion(const sipCharmmImproperTorsion &);
	sipCharmmImproperTorsion &operator = (const sipCharmmImproperTorsion &);

	sipMethodCache sipPyMethods[4];
};

extern SIP_EXPORT int sipCanConvertTo_CharmmImproperTorsion Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_CharmmImproperTorsion Py_PROTO((PyObject *,CharmmImproperTorsion **,int,int *));
extern SIP_EXPORT CharmmImproperTorsion *sipForceConvertTo_CharmmImproperTorsion Py_PROTO((PyObject *,int *));

#endif
