// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:42 2001

#ifndef _BALLFileNotFound_h
#define	_BALLFileNotFound_h


#include "sipBALLGeneralException.h"
#include "sipBALLString.h"

#line 203 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 17 "sipBALLFileNotFound.h"

extern SIP_EXPORT PyObject *sipClass_FileNotFound;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_FileNotFound[];

extern "C" SIP_EXPORT const void *sipCast_FileNotFound Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_FileNotFound Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_FileNotFound Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_FileNotFound Py_PROTO((PyObject *,FileNotFound **,int,int *));
extern SIP_EXPORT FileNotFound *sipForceConvertTo_FileNotFound Py_PROTO((PyObject *,int *));

#endif
