// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLGridIndex2D_H
#define	_BALLGridIndex2D_H

#include "sipBALLPosition.h"

#line 7 "regularData2D.sip"
  #include <BALL/DATATYPE/regularData2D.h>
  using namespace BALL;
  typedef BALL::RegularData2D<float>::GridIndex GridIndex2D;
#line 15 "sipBALLGridIndex2D.h"

extern SIP_EXPORT PyObject *sipClass_GridIndex2D;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_GridIndex2D[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_GridIndex2D[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_GridIndex2D[];

extern SIP_EXPORT const void *sipCast_GridIndex2D Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_GridIndex2D Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_GridIndex2D Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_GridIndex2D Py_PROTO((PyObject *,GridIndex2D **,int,int *));
extern SIP_EXPORT GridIndex2D *sipForceConvertTo_GridIndex2D Py_PROTO((PyObject *,int *));

#endif
