// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Wed Aug 30 21:44:02 2000

#ifndef _BALLPyBondList_H
#define	_BALLPyBondList_H


#line 6 "pyBondList.sip"
	#include <BALL/PYTHON/pyBondList.h>
	#include "sipBALLBond.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 14 "../CPP/sipBALLPyBondList.h"

extern SIP_EXPORT int sipCanConvertTo_PyBondList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyBondList Py_PROTO((PyObject *,PyBondList **,int,int *));
extern SIP_EXPORT PyBondList *sipForceConvertTo_PyBondList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyBondList Py_PROTO((const PyBondList *));

#endif
