// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 07:14:16 2001

#ifndef _BALLSubstring_h
#define	_BALLSubstring_h


#include "sipBALLString.h"
#include "sipBALLIndex.h"

#line 6 "string.sip"
	#include <BALL/DATATYPE/string.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 17 "sipBALLSubstring.h"

extern SIP_EXPORT PyObject *sipClass_Substring;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Substring[];

extern "C" SIP_EXPORT const void *sipCast_Substring Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_Substring Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Substring Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Substring Py_PROTO((PyObject *,Substring **,int,int *));
extern SIP_EXPORT Substring *sipForceConvertTo_Substring Py_PROTO((PyObject *,int *));

#endif
