// C++ interface header file.
//
// Generated by SIP v2.5pre4cvs on Tue Jul 31 20:01:05 2001

#ifndef _BALLINIFile_h
#define	_BALLINIFile_h


#include "sipBALLString.h"

#line 23 "INIFile.sip"
  #include <BALL/FORMAT/INIFile.h>
  using namespace BALL;
#line 15 "sipBALLINIFile.h"

extern SIP_EXPORT PyObject *sipClass_INIFile;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_INIFile[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_INIFile[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_INIFile[];

extern "C" SIP_EXPORT const void *sipCast_INIFile Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_INIFile Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_INIFile Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_INIFile Py_PROTO((PyObject *,INIFile **,int,int *));
extern SIP_EXPORT INIFile *sipForceConvertTo_INIFile Py_PROTO((PyObject *,int *));

#endif
