// C++ interface header file.
//
// Generated by SIP v2.5 on Thu Aug 23 07:14:16 2001

#ifndef _BALLMicroCanonicalMD_h
#define	_BALLMicroCanonicalMD_h


#include "sipBALLMolecularDynamics.h"
#include "sipBALLForceField.h"
#include "sipBALLSnapShotManager.h"
#include "sipBALLOptions.h"

#line 7 "microCanonicalMD.sip"
  #include <BALL/MOLMEC/MDSIMULATION/microCanonicalMD.h>
  using namespace BALL;
#line 18 "sipBALLMicroCanonicalMD.h"

extern SIP_EXPORT PyObject *sipClass_MicroCanonicalMD;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_MicroCanonicalMD[];

extern "C" SIP_EXPORT const void *sipCast_MicroCanonicalMD Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_MicroCanonicalMD Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipMicroCanonicalMD : public MicroCanonicalMD
{
public:
	sipMicroCanonicalMD();
	sipMicroCanonicalMD(ForceField&);
	sipMicroCanonicalMD(ForceField&,SnapShotManager *);
	sipMicroCanonicalMD(ForceField&,SnapShotManager *,const Options&);
	sipMicroCanonicalMD(const MicroCanonicalMD&,bool);
	sipMicroCanonicalMD(const MicroCanonicalMD&);
	~sipMicroCanonicalMD();
	void simulateTime(double,bool);
	void simulateIterations(int,bool);
	void simulate(bool);
	void setTimeStep(double);
	bool specificSetup();
	bool setup(ForceField&,SnapShotManager *,const Options&);
	bool setup(ForceField&,SnapShotManager *);

	sipThisType *sipPyThis;

private:
	sipMicroCanonicalMD(const sipMicroCanonicalMD &);
	sipMicroCanonicalMD &operator = (const sipMicroCanonicalMD &);

	sipMethodCache sipPyMethods[7];
};

extern SIP_EXPORT int sipCanConvertTo_MicroCanonicalMD Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_MicroCanonicalMD Py_PROTO((PyObject *,MicroCanonicalMD **,int,int *));
extern SIP_EXPORT MicroCanonicalMD *sipForceConvertTo_MicroCanonicalMD Py_PROTO((PyObject *,int *));

#endif
