// C++ interface header file.
//
// Generated by SIP v2.5pre4 on Sun Jul 29 13:00:58 2001

#ifndef _BALLVector3_h
#define	_BALLVector3_h


#include "sipBALLPersistentObject.h"
#include "sipBALLAngle.h"
#include "sipBALLIndex.h"


extern SIP_EXPORT PyObject *sipClass_Vector3;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Vector3[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Vector3[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Vector3[];

extern SIP_EXPORT const void *sipCast_Vector3 Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Vector3 Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Vector3 Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Vector3 Py_PROTO((PyObject *,Vector3 **,int,int *));
extern SIP_EXPORT Vector3 *sipForceConvertTo_Vector3 Py_PROTO((PyObject *,int *));

#endif
