// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:42 2001

#ifndef _BALLIncompatibleIterators_h
#define	_BALLIncompatibleIterators_h


#include "sipBALLGeneralException.h"

#line 128 "exception.sip"
	#include <BALL/COMMON/exception.h>
	using namespace BALL;
	using namespace BALL::Exception;
#line 16 "sipBALLIncompatibleIterators.h"

extern SIP_EXPORT PyObject *sipClass_IncompatibleIterators;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_IncompatibleIterators[];

extern "C" SIP_EXPORT const void *sipCast_IncompatibleIterators Py_PROTO((const void *,PyObject *));
extern "C" SIP_EXPORT PyObject *sipNew_IncompatibleIterators Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_IncompatibleIterators Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_IncompatibleIterators Py_PROTO((PyObject *,IncompatibleIterators **,int,int *));
extern SIP_EXPORT IncompatibleIterators *sipForceConvertTo_IncompatibleIterators Py_PROTO((PyObject *,int *));

#endif
