// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Tue Jan 23 19:05:43 2001

#ifndef _BALLFloatRegularData1D_H
#define	_BALLFloatRegularData1D_H


#line 4 "regularData1D.sip"
	#include <BALL/DATATYPE/regularData1D.h>
	using namespace BALL;
	typedef TRegularData1D<float> FloatRegularData1D;
#line 14 "../CPP/sipBALLFloatRegularData1D.h"

extern SIP_EXPORT PyObject *sipClass_FloatRegularData1D;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_FloatRegularData1D[];

extern SIP_EXPORT const void *sipCast_FloatRegularData1D Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_FloatRegularData1D Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipFloatRegularData1D : public FloatRegularData1D
{
public:
	sipFloatRegularData1D();
	sipFloatRegularData1D(const FloatRegularData1D&);
	~sipFloatRegularData1D();

       // There is a catcher function for every virtual member function in
       // the class hierachy.

	void clear();
	void destroy();
	static void sipVH_clear(const sipMethodCache *,sipThisType *,int);
	static void sipVH_destroy(const sipMethodCache *,sipThisType *,int);

	sipThisType *sipPyThis;

private:
	sipMethodCache sipPyMethods[2];
};

extern SIP_EXPORT int sipCanConvertTo_FloatRegularData1D Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_FloatRegularData1D Py_PROTO((PyObject *,FloatRegularData1D **,int,int *));
extern SIP_EXPORT FloatRegularData1D *sipForceConvertTo_FloatRegularData1D Py_PROTO((PyObject *,int *));

#endif
