// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Fri Jan 26 17:37:59 2001

#ifndef _BALLFragmentDB_H
#define	_BALLFragmentDB_H

#include "sipBALLString.h"
#include "sipBALLFragment.h"
#include "sipBALLResidue.h"
#include "sipBALLMolecule.h"
#include "sipBALLNormalizeNamesProcessor.h"
#include "sipBALLAddHydrogensProcessor.h"
#include "sipBALLBuildBondsProcessor.h"
#include "sipBALLResourceEntry.h"

#line 6 "fragmentDB.sip"
	#include <BALL/STRUCTURE/fragmentDB.h>
	using namespace BALL;
#line 21 "../CPP/sipBALLFragmentDB.h"

extern SIP_EXPORT PyObject *sipClass_FragmentDB;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_FragmentDB[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_FragmentDB[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_FragmentDB[];

extern SIP_EXPORT const void *sipCast_FragmentDB Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_FragmentDB Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_FragmentDB Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_FragmentDB Py_PROTO((PyObject *,FragmentDB **,int,int *));
extern SIP_EXPORT FragmentDB *sipForceConvertTo_FragmentDB Py_PROTO((PyObject *,int *));

#endif
