// C++ interface header file.
//
// Generated by SIP v2.5pre4 on Sun Jul 29 13:00:58 2001

#ifndef _BALLPyPDBAtomList_h
#define	_BALLPyPDBAtomList_h

#line 6 "pyPDBAtomList.sip"
	#include <BALL/PYTHON/pyPDBAtomList.h>
	#include "sipBALLPDBAtom.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 13 "sipBALLPyPDBAtomList.h"

extern SIP_EXPORT int sipCanConvertTo_PyPDBAtomList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyPDBAtomList Py_PROTO((PyObject *,PyPDBAtomList **,int,int *));
extern SIP_EXPORT PyPDBAtomList *sipForceConvertTo_PyPDBAtomList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyPDBAtomList Py_PROTO((const PyPDBAtomList *));

#endif
