// C++ interface header file.
//
// Generated by SIP v2.5 on Wed Aug 22 06:12:41 2001

#ifndef _BALLPyProteinList_h
#define	_BALLPyProteinList_h

#line 6 "pyProteinList.sip"
	#include <BALL/PYTHON/pyProteinList.h>
	#include "sipBALLProtein.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 13 "sipBALLPyProteinList.h"

extern SIP_EXPORT int sipCanConvertTo_PyProteinList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyProteinList Py_PROTO((PyObject *,PyProteinList **,int,int *));
extern SIP_EXPORT PyProteinList *sipForceConvertTo_PyProteinList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyProteinList Py_PROTO((const PyProteinList *));

#endif
