// C++ wrapper class header file.
//
// Generated by SIP v2.4 on Wed Jul 25 07:17:27 2001

#ifndef _BALLSphere3_H
#define	_BALLSphere3_H

#include "sipBALLVector3.h"

#line 4 "sphere3.sip"
	#include <BALL/MATHS/sphere3.h>
	using namespace BALL;
#line 14 "sipBALLSphere3.h"

extern SIP_EXPORT PyObject *sipClass_Sphere3;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Sphere3[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_Sphere3[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_Sphere3[];

extern SIP_EXPORT const void *sipCast_Sphere3 Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Sphere3 Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Sphere3 Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Sphere3 Py_PROTO((PyObject *,Sphere3 **,int,int *));
extern SIP_EXPORT Sphere3 *sipForceConvertTo_Sphere3 Py_PROTO((PyObject *,int *));

#endif
