/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgAmberMinimizationData.h
	Last generated: Sun Apr 2 17:32:12 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DlgAmberMinimizationData_included
#define DlgAmberMinimizationData_included

#include <qdialog.h>
#include <qradiobutton.h>
#include <qlineedit.h>

class DlgAmberMinimizationData : public QDialog
{
    Q_OBJECT

public:

    DlgAmberMinimizationData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~DlgAmberMinimizationData();

    protected slots:

    virtual void browseParameterFiles() =0;

    protected:

    QRadioButton *cg_minimizer_button_;
    QLineEdit *max_iterations_lineedit_;
    QLineEdit *refresh_iterations_lineedit_;
    QLineEdit *max_grad_lineedit_;
    QRadioButton *distance_dependent_button_;
    QLineEdit *parameter_file_edit_;
    QLineEdit *energy_difference_lineedit_;
};

#endif // DlgAmberMinimizationData_included
