/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgAmberMinimizationData.C
	Last generated: Sat Apr 1 09:06:01 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "DlgAmberMinimizationData.h"

#include <qlabel.h>
#include <qradiobutton.h>
#include <qvbuttongroup.h>
#include <qpushbutton.h>
#include <qgroupbox.h>
#include <qlineedit.h>

DlgAmberMinimizationData::DlgAmberMinimizationData(QWidget *parent, const char *name)
                         : QDialog(parent, name, TRUE, 0)
{
    QGroupBox *qtarch_GroupBox_2 = new QGroupBox(this, "GroupBox_2");
    qtarch_GroupBox_2->setGeometry(20, 120, 230, 90);
    qtarch_GroupBox_2->setMinimumSize(0, 0);
    qtarch_GroupBox_2->setMaximumSize(32767, 32767);
    qtarch_GroupBox_2->setFocusPolicy(QWidget::NoFocus);
    qtarch_GroupBox_2->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_GroupBox_2->setFontPropagation(QWidget::SameFont);
    qtarch_GroupBox_2->setPalettePropagation(QWidget::SameFont);
    qtarch_GroupBox_2->setFrameStyle( 49 );
    qtarch_GroupBox_2->setLineWidth( 1 );
    qtarch_GroupBox_2->setMidLineWidth( 0 );
    qtarch_GroupBox_2->QFrame::setMargin( 0 );
    qtarch_GroupBox_2->setTitle( tr( "minimization algorithm" ) );
    qtarch_GroupBox_2->setAlignment( AlignHCenter );

    QLabel *qtarch_Label_4 = new QLabel(this, "Label_4");
    qtarch_Label_4->setGeometry(20, 20, 200, 30);
    qtarch_Label_4->setMinimumSize(0, 0);
    qtarch_Label_4->setMaximumSize(32767, 32767);
    qtarch_Label_4->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_4->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_4->setFontPropagation(QWidget::SameFont);
    qtarch_Label_4->setPalettePropagation(QWidget::SameFont);
    qtarch_Label_4->setFrameStyle( 0 );
    qtarch_Label_4->setLineWidth( 1 );
    qtarch_Label_4->setMidLineWidth( 0 );
    qtarch_Label_4->QFrame::setMargin( 0 );
    qtarch_Label_4->setText( tr( "maximum number of iterations" ) );
    qtarch_Label_4->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_4->setMargin( 0 );

    QLabel *qtarch_Label_5 = new QLabel(this, "Label_5");
    qtarch_Label_5->setGeometry(20, 50, 260, 30);
    qtarch_Label_5->setMinimumSize(0, 0);
    qtarch_Label_5->setMaximumSize(32767, 32767);
    qtarch_Label_5->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_5->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_5->setFontPropagation(QWidget::SameFont);
    qtarch_Label_5->setPalettePropagation(QWidget::SameFont);
    qtarch_Label_5->setFrameStyle( 0 );
    qtarch_Label_5->setLineWidth( 1 );
    qtarch_Label_5->setMidLineWidth( 0 );
    qtarch_Label_5->QFrame::setMargin( 0 );
    qtarch_Label_5->setText( tr( "number iterations before screen refresh" ) );
    qtarch_Label_5->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_5->setMargin( 0 );

    QLabel *qtarch_Label_6 = new QLabel(this, "Label_6");
    qtarch_Label_6->setGeometry(20, 80, 240, 30);
    qtarch_Label_6->setMinimumSize(0, 0);
    qtarch_Label_6->setMaximumSize(32767, 32767);
    qtarch_Label_6->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_6->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_6->setFontPropagation(QWidget::SameFont);
    qtarch_Label_6->setPalettePropagation(QWidget::SameFont);
    qtarch_Label_6->setFrameStyle( 0 );
    qtarch_Label_6->setLineWidth( 1 );
    qtarch_Label_6->setMidLineWidth( 0 );
    qtarch_Label_6->QFrame::setMargin( 0 );
    qtarch_Label_6->setText( tr( "maximum gradient for convergence" ) );
    qtarch_Label_6->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_6->setMargin( 0 );

    QRadioButton *qtarch_RadioButton_9 = new QRadioButton(qtarch_GroupBox_2, "RadioButton_9");
    qtarch_RadioButton_9->setGeometry(20, 20, 140, 30);
    qtarch_RadioButton_9->setMinimumSize(0, 0);
    qtarch_RadioButton_9->setMaximumSize(32767, 32767);
    qtarch_RadioButton_9->setFocusPolicy(QWidget::TabFocus);
    qtarch_RadioButton_9->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RadioButton_9->setFontPropagation(QWidget::SameFont);
    qtarch_RadioButton_9->setPalettePropagation(QWidget::SameFont);
    qtarch_RadioButton_9->setText( tr( "steepest descent" ) );
    qtarch_RadioButton_9->setAutoRepeat( FALSE );
    qtarch_RadioButton_9->setAutoResize( FALSE );
    qtarch_RadioButton_9->setChecked( TRUE );

    QRadioButton *qtarch_RadioButton_10 = new QRadioButton(qtarch_GroupBox_2, "RadioButton_10");
    qtarch_RadioButton_10->setGeometry(20, 50, 160, 30);
    qtarch_RadioButton_10->setMinimumSize(0, 0);
    qtarch_RadioButton_10->setMaximumSize(32767, 32767);
    qtarch_RadioButton_10->setFocusPolicy(QWidget::TabFocus);
    qtarch_RadioButton_10->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RadioButton_10->setFontPropagation(QWidget::SameFont);
    qtarch_RadioButton_10->setPalettePropagation(QWidget::SameFont);
    qtarch_RadioButton_10->setText( tr( "conjugate gradient" ) );
    qtarch_RadioButton_10->setAutoRepeat( FALSE );
    qtarch_RadioButton_10->setAutoResize( FALSE );
    qtarch_RadioButton_10->setChecked( FALSE );

    QLineEdit *qtarch_LineEdit_2 = new QLineEdit(this, "LineEdit_2");
    qtarch_LineEdit_2->setGeometry(300, 20, 100, 30);
    qtarch_LineEdit_2->setMinimumSize(0, 0);
    qtarch_LineEdit_2->setMaximumSize(32767, 32767);
    qtarch_LineEdit_2->setFocusPolicy(QWidget::StrongFocus);
    qtarch_LineEdit_2->setBackgroundMode(QWidget::PaletteBase);
    qtarch_LineEdit_2->setFontPropagation(QWidget::SameFont);
    qtarch_LineEdit_2->setPalettePropagation(QWidget::SameFont);
    qtarch_LineEdit_2->setText( tr( "500" ) );
    qtarch_LineEdit_2->setMaxLength( 7 );
    qtarch_LineEdit_2->setFrame( QLineEdit::Normal );
    qtarch_LineEdit_2->setFrame( TRUE );
    qtarch_LineEdit_2->setAlignment( AlignRight );

    QLineEdit *qtarch_LineEdit_3 = new QLineEdit(this, "LineEdit_3");
    qtarch_LineEdit_3->setGeometry(300, 50, 100, 30);
    qtarch_LineEdit_3->setMinimumSize(0, 0);
    qtarch_LineEdit_3->setMaximumSize(32767, 32767);
    qtarch_LineEdit_3->setFocusPolicy(QWidget::StrongFocus);
    qtarch_LineEdit_3->setBackgroundMode(QWidget::PaletteBase);
    qtarch_LineEdit_3->setFontPropagation(QWidget::SameFont);
    qtarch_LineEdit_3->setPalettePropagation(QWidget::SameFont);
    qtarch_LineEdit_3->setText( tr( "10" ) );
    qtarch_LineEdit_3->setMaxLength( 7 );
    qtarch_LineEdit_3->setFrame( QLineEdit::Normal );
    qtarch_LineEdit_3->setFrame( TRUE );
    qtarch_LineEdit_3->setAlignment( AlignRight );

    QLineEdit *qtarch_LineEdit_4 = new QLineEdit(this, "LineEdit_4");
    qtarch_LineEdit_4->setGeometry(300, 80, 100, 30);
    qtarch_LineEdit_4->setMinimumSize(0, 0);
    qtarch_LineEdit_4->setMaximumSize(32767, 32767);
    qtarch_LineEdit_4->setFocusPolicy(QWidget::StrongFocus);
    qtarch_LineEdit_4->setBackgroundMode(QWidget::PaletteBase);
    qtarch_LineEdit_4->setFontPropagation(QWidget::SameFont);
    qtarch_LineEdit_4->setPalettePropagation(QWidget::SameFont);
    qtarch_LineEdit_4->setText( tr( "0.5" ) );
    qtarch_LineEdit_4->setMaxLength( 12 );
    qtarch_LineEdit_4->setFrame( QLineEdit::Normal );
    qtarch_LineEdit_4->setFrame( TRUE );
    qtarch_LineEdit_4->setAlignment( AlignRight );

    QLabel *qtarch_Label_7 = new QLabel(this, "Label_7");
    qtarch_Label_7->setGeometry(410, 80, 70, 30);
    qtarch_Label_7->setMinimumSize(0, 0);
    qtarch_Label_7->setMaximumSize(32767, 32767);
    qtarch_Label_7->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_7->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_7->setFontPropagation(QWidget::SameFont);
    qtarch_Label_7->setPalettePropagation(QWidget::SameFont);
    qtarch_Label_7->setFrameStyle( 0 );
    qtarch_Label_7->setLineWidth( 1 );
    qtarch_Label_7->setMidLineWidth( 0 );
    qtarch_Label_7->QFrame::setMargin( 0 );
    qtarch_Label_7->setText( tr( "kJ/(mol A)" ) );
    qtarch_Label_7->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_7->setMargin( 0 );

    QPushButton *qtarch_PushButton_8 = new QPushButton(this, "PushButton_8");
    qtarch_PushButton_8->setGeometry(100, 280, 100, 30);
    qtarch_PushButton_8->setMinimumSize(0, 0);
    qtarch_PushButton_8->setMaximumSize(32767, 32767);
    qtarch_PushButton_8->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_8->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_8->setFontPropagation(QWidget::SameFont);
    qtarch_PushButton_8->setPalettePropagation(QWidget::SameFont);
    qtarch_PushButton_8->setText( tr( "&Start" ) );
    qtarch_PushButton_8->setAutoRepeat( FALSE );
    qtarch_PushButton_8->setAutoResize( FALSE );
    qtarch_PushButton_8->setToggleButton( FALSE );
    qtarch_PushButton_8->setDefault( FALSE );
    qtarch_PushButton_8->setAutoDefault( TRUE );
    qtarch_PushButton_8->setIsMenuButton( FALSE );
    connect(qtarch_PushButton_8, SIGNAL(clicked()), SLOT(accept()));

    QPushButton *qtarch_PushButton_9 = new QPushButton(this, "PushButton_9");
    qtarch_PushButton_9->setGeometry(270, 280, 100, 30);
    qtarch_PushButton_9->setMinimumSize(0, 0);
    qtarch_PushButton_9->setMaximumSize(32767, 32767);
    qtarch_PushButton_9->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_9->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_9->setFontPropagation(QWidget::SameFont);
    qtarch_PushButton_9->setPalettePropagation(QWidget::SameFont);
    qtarch_PushButton_9->setText( tr( "Cancel" ) );
    qtarch_PushButton_9->setAutoRepeat( FALSE );
    qtarch_PushButton_9->setAutoResize( FALSE );
    qtarch_PushButton_9->setToggleButton( FALSE );
    qtarch_PushButton_9->setDefault( FALSE );
    qtarch_PushButton_9->setAutoDefault( TRUE );
    qtarch_PushButton_9->setIsMenuButton( FALSE );
    connect(qtarch_PushButton_9, SIGNAL(clicked()), SLOT(reject()));

    QVButtonGroup *qtarch_VButtonGroup_1 = new QVButtonGroup(this, "VButtonGroup_1");
    qtarch_VButtonGroup_1->setGeometry(270, 120, 220, 90);
    qtarch_VButtonGroup_1->setMinimumSize(0, 0);
    qtarch_VButtonGroup_1->setMaximumSize(32767, 32767);
    qtarch_VButtonGroup_1->setFocusPolicy(QWidget::NoFocus);
    qtarch_VButtonGroup_1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_VButtonGroup_1->setFontPropagation(QWidget::SameFont);
    qtarch_VButtonGroup_1->setPalettePropagation(QWidget::SameFont);
    qtarch_VButtonGroup_1->setFrameStyle( 49 );
    qtarch_VButtonGroup_1->setLineWidth( 1 );
    qtarch_VButtonGroup_1->setMidLineWidth( 0 );
    qtarch_VButtonGroup_1->QFrame::setMargin( 0 );
    qtarch_VButtonGroup_1->setTitle( tr( "dielectric constant" ) );
    qtarch_VButtonGroup_1->setAlignment( AlignHCenter );
    qtarch_VButtonGroup_1->setExclusive( FALSE );

    QRadioButton *qtarch_RadioButton_11 = new QRadioButton(this, "RadioButton_11");
    qtarch_RadioButton_11->setGeometry(290, 140, 100, 30);
    qtarch_RadioButton_11->setMinimumSize(0, 0);
    qtarch_RadioButton_11->setMaximumSize(32767, 32767);
    qtarch_RadioButton_11->setFocusPolicy(QWidget::TabFocus);
    qtarch_RadioButton_11->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RadioButton_11->setFontPropagation(QWidget::SameFont);
    qtarch_RadioButton_11->setPalettePropagation(QWidget::SameFont);
    qtarch_RadioButton_11->setText( tr( "constant" ) );
    qtarch_RadioButton_11->setAutoRepeat( FALSE );
    qtarch_RadioButton_11->setAutoResize( FALSE );
    qtarch_RadioButton_11->setChecked( TRUE );

    QRadioButton *qtarch_RadioButton_12 = new QRadioButton(this, "RadioButton_12");
    qtarch_RadioButton_12->setGeometry(290, 170, 170, 30);
    qtarch_RadioButton_12->setMinimumSize(0, 0);
    qtarch_RadioButton_12->setMaximumSize(32767, 32767);
    qtarch_RadioButton_12->setFocusPolicy(QWidget::TabFocus);
    qtarch_RadioButton_12->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_RadioButton_12->setFontPropagation(QWidget::SameFont);
    qtarch_RadioButton_12->setPalettePropagation(QWidget::SameFont);
    qtarch_RadioButton_12->setText( tr( "distance dependent" ) );
    qtarch_RadioButton_12->setAutoRepeat( FALSE );
    qtarch_RadioButton_12->setAutoResize( FALSE );
    qtarch_RadioButton_12->setChecked( FALSE );

    parameter_file_edit_ = new QLineEdit(this, "LineEdit_5");
    parameter_file_edit_->setGeometry(120, 230, 280, 30);
    parameter_file_edit_->setMinimumSize(0, 0);
    parameter_file_edit_->setMaximumSize(32767, 32767);
    parameter_file_edit_->setFocusPolicy(QWidget::StrongFocus);
    parameter_file_edit_->setBackgroundMode(QWidget::PaletteBase);
    parameter_file_edit_->setFontPropagation(QWidget::SameFont);
    parameter_file_edit_->setPalettePropagation(QWidget::SameFont);
    parameter_file_edit_->setText( "" );
    parameter_file_edit_->setMaxLength( 32767 );
    parameter_file_edit_->setFrame( QLineEdit::Normal );
    parameter_file_edit_->setFrame( TRUE );
    parameter_file_edit_->setAlignment( AlignLeft );

    QLabel *qtarch_Label_10 = new QLabel(this, "Label_10");
    qtarch_Label_10->setGeometry(20, 230, 90, 30);
    qtarch_Label_10->setMinimumSize(0, 0);
    qtarch_Label_10->setMaximumSize(32767, 32767);
    qtarch_Label_10->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_10->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_10->setFontPropagation(QWidget::SameFont);
    qtarch_Label_10->setPalettePropagation(QWidget::SameFont);
    qtarch_Label_10->setFrameStyle( 0 );
    qtarch_Label_10->setLineWidth( 1 );
    qtarch_Label_10->setMidLineWidth( 0 );
    qtarch_Label_10->QFrame::setMargin( 0 );
    qtarch_Label_10->setText( tr( "parameter file" ) );
    qtarch_Label_10->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_10->setMargin( 0 );

    QPushButton *qtarch_PushButton_10 = new QPushButton(this, "PushButton_10");
    qtarch_PushButton_10->setGeometry(410, 230, 80, 30);
    qtarch_PushButton_10->setMinimumSize(0, 0);
    qtarch_PushButton_10->setMaximumSize(32767, 32767);
    qtarch_PushButton_10->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_10->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_10->setFontPropagation(QWidget::SameFont);
    qtarch_PushButton_10->setPalettePropagation(QWidget::SameFont);
    qtarch_PushButton_10->setText( tr( "Browse" ) );
    qtarch_PushButton_10->setAutoRepeat( FALSE );
    qtarch_PushButton_10->setAutoResize( FALSE );
    qtarch_PushButton_10->setToggleButton( FALSE );
    qtarch_PushButton_10->setDefault( FALSE );
    qtarch_PushButton_10->setAutoDefault( TRUE );
    qtarch_PushButton_10->setIsMenuButton( FALSE );
    connect(qtarch_PushButton_10, SIGNAL(clicked()), SLOT(browseParameterFiles()));

    resize(510,330);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

DlgAmberMinimizationData::~DlgAmberMinimizationData()
{
}
