/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgDisplayPropertiesData.h
	Last generated: Tue May 23 15:37:46 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DlgDisplayPropertiesData_included
#define DlgDisplayPropertiesData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qcombobox.h>

class DlgDisplayPropertiesData : public QDialog
{
    Q_OBJECT

public:

    DlgDisplayPropertiesData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~DlgDisplayPropertiesData();

    protected slots:

    virtual void selectPrecision(const QString&) =0;
    virtual void selectModel(const QString&) =0;
    virtual void applyButtonClicked() =0;
    virtual void selectColoringMethod(const QString&) =0;
    virtual void editColor() =0;

    protected:

    QComboBox *coloring_type_combobox_;
    QComboBox *model_type_combobox_;
    QComboBox *mode_resolution_combobox_;
    QLabel *color_sample;
};

#endif // DlgDisplayPropertiesData_included
