/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgPreferencesGeneralData.h
	Last generated: Sat Jan 15 19:16:46 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DlgPreferencesGeneralData_included
#define DlgPreferencesGeneralData_included

#include <qwidget.h>
#include <qradiobutton.h>

class DlgPreferencesGeneralData : public QWidget
{
    Q_OBJECT

public:

    DlgPreferencesGeneralData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~DlgPreferencesGeneralData();

    protected:

    QRadioButton *is_platinum_style;
    QRadioButton *is_windows_style;
    QRadioButton *is_motif_style;
    QRadioButton *is_cde_style;
};

#endif // DlgPreferencesGeneralData_included
