.\" Copyright 1998-2007 BALL project group
.TH BALLView 1 "24 January 2007"
.SH NAME
BALLView - A free molecular modeling and molecular graphics tool (version 1.2)
.SH SYNOPSIS
.B BALLView
.RI [Molecular-file]
.SH DESCRIPTION
.B BALLView
BALLView provides fast OpenGL-based visualization of molecular structures,
molecular mechanics methods (minimization, MD simulation using the
AMBER and CHARMM force fields), calculation and visualization
of electrostatic properties (FDPB).
.P
BALLView is based on BALL (Biochemical Algorithms Library) ,
which is currently being developed in the groups of Hans-Peter Lenhof
(Saarland University, Saarbruecken, Germany) and Oliver Kohlbacher
(University of Tuebingen, Germany). BALL is an application framework
in C++ that has been specifically designed for rapid software
development in Molecular Modeling and Computational Molecular Biology.
It provides an extensive set of data structures as well as classes
for Molecular Mechanics, advanced solvation methods, comparison and
analysis of protein structures, file import/export, and visualization.
.P
BALLView is available under the LGPL licence.
.P
Homepage: www.BALLView.org
.SH USAGE
.PP
To run BALLView, simply type:
.PP
.RS
BALLView 
.P
or
.P
BALLView file.pdp
.RE
.PP
where
.I file.pdb
is your PDB file. BALLView also supports HIN, MOL, MOL2 and SD files.
.P
BALLView provides HTML documentation, that is available in the application
itself (see Help menu).
.P
This package also includes Python example scripts, that can be run in BALLView.
They can be found under /usr/share/BALL/PYTHON.
.SH AUTHOR
BALLView is copyright 1998-2007 by the BALL project group 
.SH "SEE ALSO"
.br
.B http://www.ballview.org
