#!/bin/sh

rm -rf deb-ball &&
cp -r deb-ball-source deb-ball &&
cp ../lib/$PLATFORM/lib*.so deb-ball/opt/BALL/lib &&

cp ../lib/$PLATFORM/BALLmodule.so deb-ball/usr/lib/python2.3/site-packages &&
#cp /opt/sip-4.0rc1_gcc-3.3.3/siplib/sip.so deb-ball/usr/lib/python2.3/site-packages &&

cp ../source/APPLICATIONS/BALLVIEW/BALLView deb-ball/opt/BALL/bin &&

cp -rf ../doc/BALLView deb-ball/opt/BALL/doc &&

cp -r ../data deb-ball/opt/BALL &&

for i in `find deb-ball -name "CVS"`; do rm -rf $i; done &&

chmod -R 0755 deb-ball/DEBIAN &&
chmod +x deb-ball/usr/bin/BALLView &&

dpkg -b deb-ball BALLView.deb &&

rm -rf deb-ball

