#!/bin/bash 
# script to create a Debian source package from a BALL git tree
# arguments: $1 == BALL git branch
if test $# != 2 ; then
	echo "createDebianSource <git tag>"
	exit
fi

#create tgz
BALL_PATH=$(pwd)

# find out if we are in the right directory
if test ! -d source -o ! -d data -o ! -d include -o ! -d doc -o ! -d debian-upstream ; then
	echo "Please call this script in the root of a BALL-checkout (the directory containing source, data, include, ...)!"
	exit
fi

echo Using BALL_PATH: $BALL_PATH
echo "Creating git checkout..."
KEEP_DIRS="data debian-upstream doc include README source"

# get name of the BALL tgz
BFILE=$(source/config/makedistribution $1 ${KEEP_DIRS} | tr -d "\n"  | sed "s/^.* \([^ ]*\)$/\1/g")

# extract the version from the tgz
VERSION=$(basename ${BFILE} .tar.gz | sed "s_ball-__")
echo $BFILE", version "${VERSION}

# we need to manipulate some of the files in the distribution => extract our new and shiny tgz again...

# rename the tgz
ORIG_FILE=$(basename ${BFILE} .tar.gz).orig.tar.gz
mv ${BALL_PATH}/${BFILE} ${BALL_PATH}/${ORIG_FILE}

# create working directory
tempdir=$(mktemp -d)
cd ${tempdir}

# extract content of tgz into working directory
echo "Extracting tgz..."
tar xzf ${BALL_PATH}/${ORIG_FILE} > /dev/null
BDIR=`find . -maxdepth 1 -type d | grep ball | grep -v dist`
mv ${BDIR} ball-${VERSION}

# create a new orig.tar.gz with the updated paths
rm ${BALL_PATH}/${ORIG_FILE}
tar czf ${BALL_PATH}/${ORIG_FILE} "ball-"${VERSION}

# now create the debianized .tar.gz file
cd "ball-"${VERSION}

# copy debian control files
cp -r debian-upstream debian
rm -f debian/createDebianSource
rm -f debian/debian-ball-install
rm -f debian/createBALLVIEWDEB
rm -f debian/README

# build package
echo "building debian source package..."
dpkg-buildpackage -S -sa -rfakeroot
cd ..

#rm -f ballview-$2-debian-binary.tar.gz 
#tar czf ballview-$2-debian-binary.tar.gz  *.deb
#tar czf ballview-$2-debian-source.tar.gz \
#		ballview*.dsc \
#		ballview*.changes \
#		*orig.tar.gz \
#		*.diff.gz
