#!/bin/sh

for i in $*; do 
	SIZE=`cat $i | wc -c`
	STR_SIZE=`cat $i | gawk -f ./remove_comments.awk | wc -c`
	echo ${i} ${SIZE} ${STR_SIZE} | awk '{p=(1.0 - ($3 / $2)) * 100.0; if (p < 5.0){c="! "}else{c="  "} print c $1, p "%"}'
done
