#!/usr/local/bin/bash
# $Id: makehtmldoc,v 1.1 2001/07/12 12:36:40 amoll Exp $

# this script is used to build the html version of the BALL-documentation.
# DOCPP_PATH and BALLDIR must be set in the environment.
# You have to use the patched version of docpp, which ignores namespaces.
# (option -N)

#=================== Path to docpp =================================
if [ -z $DOCPP_PATH ]
then
	echo DOCPP_PATH must be defined to use this script.
	exit
fi

if [ ! -e $DOCPP_PATH ]
then
	echo docpp can not be found at the given position in DOCPP_PATH.
	exit
fi


#=================== Path to BALL ==================================
if [ -z $BALLDIR ]
then
	echo BALLDIR must be defined to use this script.
	exit
fi

if [ ! -d $BALLDIR ]
then
	echo Can not find the BALL-directory.
	exit
fi

# extract the date for replacing in all html pages
USERNAME=`finger ${USER} |grep Login|grep ": ${USER}" | head -1|sed "s/^.*life: //"|sed "s/&/${USER}/"`
DATE=`date +"%a %b %e %Y"`
RELEASE="`grep BALL_RELEASE_STRING $BALLDIR/include/BALL/COMMON/version.h | awk '{print $3}' | tr -d \\ `"
YEAR=`date +%Y`

cd $BALLDIR;

mkdir doc 2>/dev/null
mkdir doc/html 2>/dev/null
mkdir doc/html/BALL 2>/dev/null

cd doc/html
rm -rf $BALLDIR/doc/html/*

if test "$1" != "-f" -a "$2" != "-f" ; then
	echo "collecting header files..."

	HEADER_NAMES=`cd ../../include ; find BALL -name \*.h -print`

	echo "creating directories"

	HEADER_DIRECTORIES=`for i in ${HEADER_NAMES} ; do dirname $i ; done | sort -u`
	for i in ${HEADER_DIRECTORIES} ; do 
		mkdirhier $i 2>/dev/null
	done
	
	echo "copying headers..."

	for i in ${HEADER_NAMES} ; do 
		cat $BALLDIR/include/$i | expand -t 2 | /opt/gnu/bin/gawk -f $BALLDIR/doc/tools/remove_comments.awk  > $i
	done

fi

cp $BALLDIR/source/doc/html/*.gif .

echo "creating start page and html include files..."

for i in $BALLDIR/doc/tools/*.inc $BALLDIR/doc/tools/*.html ; do
	cat $i |\
		sed "s/@USER@/${USERNAME}/" |\
		sed "s/@RELEASE@/${RELEASE}/" |\
		sed "s/@YEAR@/${YEAR}/" |\
		sed "s/@DATE@/${DATE}/" > `basename $i`
done

$DOCPP_PATH -u -m -w -W -G -N -ep amsmath -ep graphicx -eo 11pt -d . $BALLDIR/include/BALL/BALL.doc

