IF (UNIX AND NOT APPLE)
	SET(COMPONENT_PLUGINS "")
ELSEIF(APPLE)
	SET(COMPONENT_PLUGINS "BALL${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}-plugins")
ELSEIF(WIN32)
	SET(COMPONENT_PLUGINS "")
ELSE()
	SET(COMPONENT_PLUGINS "")
ENDIF()

IF (COMPONENT_PLUGINS)
	SET_COMPONENT_NAME(${COMPONENT_PLUGINS}
		"SpaceNavigator plugin"
		"Plugin adding support for 3Dconnexion SpaceNavigator input device"
	)

	SET_COMPONENT_DEPENDENCIES(${COMPONENT_PLUGINS} ${COMPONENT_LIBVIEW})  
ENDIF()
