#
# $Id: Makefile.lst,v 1.22.2.4 2005/10/27 15:01:12 amoll Exp $
#

XDR_DEPENDENT_EXECUTABLES = \
$(PREFIX)XDRPersistenceManager_test$(EXEEXT)

VIEW_DEPENDENT_EXECUTABLES=\

EXECUTABLES_BASIC = \
$(PREFIX)ClassTest_test$(EXEEXT)\
$(PREFIX)Debug_test$(EXEEXT)\
$(PREFIX)RegularExpression_test$(EXEEXT)\
$(PREFIX)GlobalTypes_test$(EXEEXT)\
$(PREFIX)Limits_test$(EXEEXT)\
$(PREFIX)VersionInfo_test$(EXEEXT)\
$(PREFIX)RTTI_test$(EXEEXT)


EXECUTABLES_MATHS = \
$(PREFIX)MathsCommon_test$(EXEEXT)\
$(PREFIX)AnalyticalGeometry_test$(EXEEXT)\
$(PREFIX)Angle_test$(EXEEXT)\
$(PREFIX)Vector2_test$(EXEEXT)\
$(PREFIX)Vector3_test$(EXEEXT)\
$(PREFIX)Vector4_test$(EXEEXT)\
$(PREFIX)Quaternion_test$(EXEEXT)\
$(PREFIX)Matrix44_test$(EXEEXT)\
$(PREFIX)NumericalIntegrator_test$(EXEEXT)\
$(PREFIX)Line3_test$(EXEEXT)\
$(PREFIX)Circle3_test$(EXEEXT)\
$(PREFIX)SimpleBox3_test$(EXEEXT)\
$(PREFIX)Box3_test$(EXEEXT)\
$(PREFIX)Plane3_test$(EXEEXT)\
$(PREFIX)Sphere3_test$(EXEEXT)\
$(PREFIX)Surface_test$(EXEEXT)\
$(PREFIX)Function_test$(EXEEXT)\
$(PREFIX)PiecewiseFunction_test$(EXEEXT)\
$(PREFIX)PiecewisePolynomial_test$(EXEEXT)

EXECUTABLES_SYSTEM = \
$(PREFIX)BinaryFileAdaptor_test$(EXEEXT)\
$(PREFIX)Directory_test$(EXEEXT)\
$(PREFIX)FileSystem_test$(EXEEXT)\
$(PREFIX)File_test$(EXEEXT)\
$(PREFIX)Path_test$(EXEEXT)\
$(PREFIX)PreciseTime_test$(EXEEXT)\
$(PREFIX)Socket_test$(EXEEXT)\
$(PREFIX)Sysinfo_test$(EXEEXT)\
$(PREFIX)TCPTransfer_test$(EXEEXT)\
$(PREFIX)Timer_test$(EXEEXT)\
$(PREFIX)TimeStamp_test$(EXEEXT)\
$(PREFIX)TransformationManager_test$(EXEEXT)

EXECUTABLES_DATATYPES = \
$(PREFIX)Bit_test$(EXEEXT)\
$(PREFIX)BitVector_test$(EXEEXT)\
$(PREFIX)Contour_test$(EXEEXT)\
$(PREFIX)ContourLine_test$(EXEEXT)\
$(PREFIX)List_test$(EXEEXT)\
$(PREFIX)Hash_test$(EXEEXT)\
$(PREFIX)HashMap_test$(EXEEXT)\
$(PREFIX)StringHashMap_test$(EXEEXT)\
$(PREFIX)HashSet_test$(EXEEXT)\
$(PREFIX)HashGrid3_test$(EXEEXT)\
$(PREFIX)HashGridBox3_test$(EXEEXT)\
$(PREFIX)HashGrid3DataIteratorTraits_test$(EXEEXT)\
$(PREFIX)HashGrid3BoxIteratorTraits_test$(EXEEXT)\
$(PREFIX)HashGrid3DataItem_test$(EXEEXT)\
$(PREFIX)HashGrid3NeighborBoxItem_test$(EXEEXT)\
$(PREFIX)Options_test$(EXEEXT)\
$(PREFIX)String_test1$(EXEEXT)\
$(PREFIX)String_test2$(EXEEXT)\
$(PREFIX)String_test3$(EXEEXT)\
$(PREFIX)String_test4$(EXEEXT)\
$(PREFIX)Substring_test$(EXEEXT)\
$(PREFIX)Triple_test$(EXEEXT)\
$(PREFIX)Quadruple_test$(EXEEXT)\
$(PREFIX)RegularData1D_test$(EXEEXT)\
$(PREFIX)RegularData2D_test$(EXEEXT)\
$(PREFIX)RegularData3D_test$(EXEEXT)\
$(PREFIX)ContourSurface_test$(EXEEXT)

EXECUTABLES_CONCEPTS = \
$(PREFIX)LogStream_test$(EXEEXT)\
$(PREFIX)AutoDeletable_test$(EXEEXT)\
$(PREFIX)Factory_test$(EXEEXT)\
$(PREFIX)Object_test$(EXEEXT)\
$(PREFIX)PersistentObject_test$(EXEEXT)\
$(PREFIX)PersistenceManager_test$(EXEEXT)\
$(PREFIX)TextPersistenceManager_test$(EXEEXT)\
$(PREFIX)Selectable_test$(EXEEXT)\
$(PREFIX)NamedProperty_test$(EXEEXT)\
$(PREFIX)PropertyManager_test$(EXEEXT)\
$(PREFIX)Composite_test1$(EXEEXT)\
$(PREFIX)Composite_test2$(EXEEXT)\
$(PREFIX)CompositeCompositeIteratorTraits_test$(EXEEXT)\
$(PREFIX)CompositeChildcompositeIteratorTraits_test$(EXEEXT)\
$(PREFIX)CompositeAncestorIteratorTraits_test$(EXEEXT)\
$(PREFIX)Embeddable_test$(EXEEXT)\
$(PREFIX)BaseIterator_test$(EXEEXT)\
$(PREFIX)ConstForwardIterator_test$(EXEEXT)\
$(PREFIX)ForwardIterator_test$(EXEEXT)\
$(PREFIX)ConstBidirectionalIterator_test$(EXEEXT)\
$(PREFIX)BidirectionalIterator_test$(EXEEXT)\
$(PREFIX)ConstRandomAccessIterator_test$(EXEEXT)\
$(PREFIX)RandomAccessIterator_test$(EXEEXT)

EXECUTABLES_KERNEL = \
$(PREFIX)PTE_test$(EXEEXT)\
$(PREFIX)Atom_test$(EXEEXT)\
$(PREFIX)AtomStaticAtomAttributes_test$(EXEEXT)\
$(PREFIX)AtomAttributeVector_test$(EXEEXT)\
$(PREFIX)Bond_test$(EXEEXT)\
$(PREFIX)AtomContainer_test$(EXEEXT)\
$(PREFIX)Fragment_test$(EXEEXT)\
$(PREFIX)Chain_test$(EXEEXT)\
$(PREFIX)Molecule_test$(EXEEXT)\
$(PREFIX)SecondaryStructure_test$(EXEEXT)\
$(PREFIX)System_test$(EXEEXT)\
$(PREFIX)Protein_test$(EXEEXT)\
$(PREFIX)PDBAtom_test$(EXEEXT)\
$(PREFIX)NucleicAcid_test$(EXEEXT)\
$(PREFIX)Nucleotide_test$(EXEEXT)\
$(PREFIX)Residue_test$(EXEEXT)\
$(PREFIX)Expression_test$(EXEEXT)\
$(PREFIX)ExpressionParser_test$(EXEEXT)\
$(PREFIX)ExpressionPredicate_test$(EXEEXT)\
$(PREFIX)ExpressionTree_test$(EXEEXT)\
$(PREFIX)KernelPredicate_test$(EXEEXT)\
$(PREFIX)Selector_test$(EXEEXT)\
$(PREFIX)RuleEvaluator_test$(EXEEXT)\
$(PREFIX)StandardPredicates_test$(EXEEXT)\
$(PREFIX)DefaultProcessors_test$(EXEEXT)\
$(PREFIX)FragmentDB_test$(EXEEXT)\
$(PREFIX)NormalizeNamesProcessor_test$(EXEEXT)\
$(PREFIX)ForEach_test$(EXEEXT)\
$(PREFIX)GlobalKernel_test$(EXEEXT)\
$(PREFIX)CompositeIteratorTraits_test$(EXEEXT)\
$(PREFIX)AtomIterator_test$(EXEEXT)\
$(PREFIX)AtomBondIteratorTraits_test$(EXEEXT)


EXECUTABLES_MOLMEC = \
$(PREFIX)Gradient_test$(EXEEXT)\
$(PREFIX)AtomVector_test$(EXEEXT)\
$(PREFIX)MolmecSupport_test$(EXEEXT)\
$(PREFIX)SnapShot_test$(EXEEXT)\
$(PREFIX)SnapShotManager_test$(EXEEXT)\
$(PREFIX)ForceField_test$(EXEEXT)\
$(PREFIX)AmberFF_test$(EXEEXT)\
$(PREFIX)CharmmFF_test$(EXEEXT)\
$(PREFIX)EnergyMinimizer_test$(EXEEXT)\
$(PREFIX)LineSearch_test$(EXEEXT)\
$(PREFIX)SteepestDescentMinimizer_test$(EXEEXT)\
$(PREFIX)ConjugateGradientMinimizer_test$(EXEEXT)\
$(PREFIX)AtomTypes_test$(EXEEXT)

EXECUTABLES_NMR = \
$(PREFIX)AssignShiftProcessor_test$(EXEEXT)\
$(PREFIX)RandomCoilShiftProcessor_test$(EXEEXT)\
$(PREFIX)AnisotropyShiftProcessor_test$(EXEEXT)\
$(PREFIX)ClearShiftProcessor_test$(EXEEXT)\
$(PREFIX)CreateSpectrumProcessor_test$(EXEEXT)\
$(PREFIX)EFShiftProcessor_test$(EXEEXT)\
$(PREFIX)HaighMallionShiftProcessor_test$(EXEEXT)\
$(PREFIX)JohnsonBoveyShiftProcessor_test$(EXEEXT)\
$(PREFIX)ShiftModel_test$(EXEEXT)\
$(PREFIX)ShiftModule_test$(EXEEXT)\
$(PREFIX)Spectrum_test$(EXEEXT)\
$(PREFIX)Peak_test$(EXEEXT)\
$(PREFIX)PeakList_test$(EXEEXT)

EXECUTABLES_FORMATS = \
$(PREFIX)LineBasedFile_test$(EXEEXT)\
$(PREFIX)BinaryFileAdaptor_test$(EXEEXT)\
$(PREFIX)Bruker1DFile_test$(EXEEXT)\
$(PREFIX)Bruker2DFile_test$(EXEEXT)\
$(PREFIX)INIFile_test$(EXEEXT)\
$(PREFIX)JCAMPFile_test$(EXEEXT)\
$(PREFIX)KCFFile_test$(EXEEXT)\
$(PREFIX)Parameters_test$(EXEEXT)\
$(PREFIX)ParameterSection_test$(EXEEXT)\
$(PREFIX)ResourceFile_test$(EXEEXT)\
$(PREFIX)GenericMolFile_test$(EXEEXT)\
$(PREFIX)HINFile_test$(EXEEXT)\
$(PREFIX)MOLFile_test$(EXEEXT)\
$(PREFIX)SDFile_test$(EXEEXT)\
$(PREFIX)MOL2File_test$(EXEEXT)\
$(PREFIX)NMRStarFile_test$(EXEEXT)\
$(PREFIX)DCDFile_test$(EXEEXT)\
$(PREFIX)PDBRecords_test$(EXEEXT)\
$(PREFIX)PDBInfo_test$(EXEEXT)\
$(PREFIX)PDBFile_test$(EXEEXT)\
$(PREFIX)TrajectoryFile_test$(EXEEXT)\
$(PREFIX)XYZFile_test$(EXEEXT)

EXECUTABLES_ENERGY = \
$(PREFIX)AtomicContactEnergy_test$(EXEEXT)\
$(PREFIX)ComposedEnergyProcessor_test$(EXEEXT)\
$(PREFIX)EnergyProcessor_test$(EXEEXT)\
$(PREFIX)OoiEnergy_test$(EXEEXT)

EXECUTABLES_STRUCTURE = \
$(PREFIX)Enumerator_test$(EXEEXT)\
$(PREFIX)EnumeratorIndex_test$(EXEEXT)\
$(PREFIX)AnalyticalSES_test$(EXEEXT)\
$(PREFIX)MolecularGraph_test$(EXEEXT)\
$(PREFIX)NumericalSAS_test$(EXEEXT)\
$(PREFIX)PeptideBuilder_test$(EXEEXT)\
$(PREFIX)Peptides_test$(EXEEXT)\
$(PREFIX)RadialDistributionFunction_test$(EXEEXT)\
$(PREFIX)RDFIntegrator_test$(EXEEXT)\
$(PREFIX)RDFParameter_test$(EXEEXT)\
$(PREFIX)RDFSection_test$(EXEEXT)\
$(PREFIX)ReconstructFragmentProcessor_test$(EXEEXT)\
$(PREFIX)ResidueChecker_test$(EXEEXT)\
$(PREFIX)RotamerLibrary_test$(EXEEXT)\
$(PREFIX)SmilesParser_test$(EXEEXT)\
$(PREFIX)StructureMapper_test$(EXEEXT)\
$(PREFIX)TransformationProcessor_test$(EXEEXT)\
$(PREFIX)TranslationProcessor_test$(EXEEXT)\
$(PREFIX)SurfaceProcessor_test$(EXEEXT)\
$(PREFIX)SecondaryStructureProcessor_test$(EXEEXT)\
$(PREFIX)UCK_test$(EXEEXT)\
$(PREFIX)BuildBondsProcessor_test$(EXEEXT)

EXECUTABLES_SOLVATION = \
$(PREFIX)PoissonBoltzmann_test$(EXEEXT)\
$(PREFIX)SolventDescriptor_test$(EXEEXT)\
$(PREFIX)SolventParameter_test$(EXEEXT)\
$(PREFIX)ClaverieParameter_test$(EXEEXT)\
$(PREFIX)ReissCavFreeEnergyProcessor_test$(EXEEXT)\
$(PREFIX)UhligCavFreeEnergyProcessor_test$(EXEEXT)\
$(PREFIX)PCMCavFreeEnergyProcessor_test$(EXEEXT)\
$(PREFIX)PierottiCavFreeEnergyProcessor_test$(EXEEXT)\
$(PREFIX)Pair6_12RDFIntegrator_test$(EXEEXT)\
$(PREFIX)Pair6_12InteractionEnergyProcessor_test$(EXEEXT)\
$(PREFIX)PairExpInteractionEnergyProcessor_test$(EXEEXT)\
$(PREFIX)PairExpRDFIntegrator_test$(EXEEXT)\
$(PREFIX)PARSE_test$(EXEEXT)

EXECUTABLES_QSAR = \
$(PREFIX)AromaticityProcessor_test$(EXEEXT)\
$(PREFIX)ConnectivityBase_test$(EXEEXT)\
$(PREFIX)ConnectivityDescriptors_test$(EXEEXT)\
$(PREFIX)Descriptor_test$(EXEEXT)\
$(PREFIX)PartialChargeProcessor_test$(EXEEXT)\
$(PREFIX)PartialChargeBase_test$(EXEEXT)\
$(PREFIX)PartialChargeDescriptors_test$(EXEEXT)\
$(PREFIX)RingPerceptionProcessor_test$(EXEEXT)\
$(PREFIX)SimpleBase_test$(EXEEXT)\
$(PREFIX)SimpleDescriptors_test$(EXEEXT)\
$(PREFIX)SurfaceBase_test$(EXEEXT)\
$(PREFIX)SurfaceDescriptors_test$(EXEEXT)
