#
# $Id: Makefile.lst,v 1.35.4.9 2007/05/14 19:02:39 oliver Exp $
#
# Author:
#  Oliver Kohlbacher
#

EXECUTABLES_BASIC = \
$(TEST_PREFIX)ClassTest_test$(EXEEXT)\
$(TEST_PREFIX)Debug_test$(EXEEXT)\
$(TEST_PREFIX)RegularExpression_test$(EXEEXT)\
$(TEST_PREFIX)GlobalTypes_test$(EXEEXT)\
$(TEST_PREFIX)Limits_test$(EXEEXT)\
$(TEST_PREFIX)VersionInfo_test$(EXEEXT)\
$(TEST_PREFIX)RTTI_test$(EXEEXT)


EXECUTABLES_MATHS = \
$(TEST_PREFIX)MathsCommon_test$(EXEEXT)\
$(TEST_PREFIX)AnalyticalGeometry_test$(EXEEXT)\
$(TEST_PREFIX)Angle_test$(EXEEXT)\
$(TEST_PREFIX)Vector2_test$(EXEEXT)\
$(TEST_PREFIX)Vector3_test$(EXEEXT)\
$(TEST_PREFIX)Vector4_test$(EXEEXT)\
$(TEST_PREFIX)Quaternion_test$(EXEEXT)\
$(TEST_PREFIX)Matrix44_test$(EXEEXT)\
$(TEST_PREFIX)NumericalIntegrator_test$(EXEEXT)\
$(TEST_PREFIX)Line3_test$(EXEEXT)\
$(TEST_PREFIX)Circle3_test$(EXEEXT)\
$(TEST_PREFIX)SimpleBox3_test$(EXEEXT)\
$(TEST_PREFIX)Box3_test$(EXEEXT)\
$(TEST_PREFIX)Plane3_test$(EXEEXT)\
$(TEST_PREFIX)Sphere3_test$(EXEEXT)\
$(TEST_PREFIX)Surface_test$(EXEEXT)\
$(TEST_PREFIX)Function_test$(EXEEXT)\
$(TEST_PREFIX)PiecewiseFunction_test$(EXEEXT)\
$(TEST_PREFIX)PiecewisePolynomial_test$(EXEEXT)

EXECUTABLES_SYSTEM = \
$(TEST_PREFIX)BinaryFileAdaptor_test$(EXEEXT)\
$(TEST_PREFIX)Directory_test$(EXEEXT)\
$(TEST_PREFIX)FileSystem_test$(EXEEXT)\
$(TEST_PREFIX)File_test$(EXEEXT)\
$(TEST_PREFIX)Path_test$(EXEEXT)\
$(TEST_PREFIX)PreciseTime_test$(EXEEXT)\
$(TEST_PREFIX)Sysinfo_test$(EXEEXT)\
$(TEST_PREFIX)Timer_test$(EXEEXT)\
$(TEST_PREFIX)TimeStamp_test$(EXEEXT)\
$(TEST_PREFIX)TransformationManager_test$(EXEEXT)

EXECUTABLES_DATATYPES = \
$(TEST_PREFIX)Bit_test$(EXEEXT)\
$(TEST_PREFIX)BitVector_test$(EXEEXT)\
$(TEST_PREFIX)Contour_test$(EXEEXT)\
$(TEST_PREFIX)ContourLine_test$(EXEEXT)\
$(TEST_PREFIX)List_test$(EXEEXT)\
$(TEST_PREFIX)Hash_test$(EXEEXT)\
$(TEST_PREFIX)HashMap_test$(EXEEXT)\
$(TEST_PREFIX)StringHashMap_test$(EXEEXT)\
$(TEST_PREFIX)HashSet_test$(EXEEXT)\
$(TEST_PREFIX)HashGrid3_test$(EXEEXT)\
$(TEST_PREFIX)HashGridBox3_test$(EXEEXT)\
$(TEST_PREFIX)HashGrid3DataIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)HashGrid3BoxIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)HashGrid3DataItem_test$(EXEEXT)\
$(TEST_PREFIX)HashGrid3NeighborBoxItem_test$(EXEEXT)\
$(TEST_PREFIX)Options_test$(EXEEXT)\
$(TEST_PREFIX)String_test1$(EXEEXT)\
$(TEST_PREFIX)String_test2$(EXEEXT)\
$(TEST_PREFIX)String_test3$(EXEEXT)\
$(TEST_PREFIX)String_test4$(EXEEXT)\
$(TEST_PREFIX)Substring_test$(EXEEXT)\
$(TEST_PREFIX)Triple_test$(EXEEXT)\
$(TEST_PREFIX)Quadruple_test$(EXEEXT)\
$(TEST_PREFIX)RegularData1D_test$(EXEEXT)\
$(TEST_PREFIX)RegularData2D_test$(EXEEXT)\
$(TEST_PREFIX)RegularData3D_test$(EXEEXT)\
$(TEST_PREFIX)ContourSurface_test$(EXEEXT)

EXECUTABLES_CONCEPTS = \
$(TEST_PREFIX)LogStream_test$(EXEEXT)\
$(TEST_PREFIX)AutoDeletable_test$(EXEEXT)\
$(TEST_PREFIX)Factory_test$(EXEEXT)\
$(TEST_PREFIX)Object_test$(EXEEXT)\
$(TEST_PREFIX)PersistentObject_test$(EXEEXT)\
$(TEST_PREFIX)PersistenceManager_test$(EXEEXT)\
$(TEST_PREFIX)TextPersistenceManager_test$(EXEEXT)\
$(TEST_PREFIX)Selectable_test$(EXEEXT)\
$(TEST_PREFIX)NamedProperty_test$(EXEEXT)\
$(TEST_PREFIX)PropertyManager_test$(EXEEXT)\
$(TEST_PREFIX)Composite_test1$(EXEEXT)\
$(TEST_PREFIX)Composite_test2$(EXEEXT)\
$(TEST_PREFIX)CompositeCompositeIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)CompositeChildcompositeIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)CompositeAncestorIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)Embeddable_test$(EXEEXT)\
$(TEST_PREFIX)BaseIterator_test$(EXEEXT)\
$(TEST_PREFIX)ConstForwardIterator_test$(EXEEXT)\
$(TEST_PREFIX)ForwardIterator_test$(EXEEXT)\
$(TEST_PREFIX)ConstBidirectionalIterator_test$(EXEEXT)\
$(TEST_PREFIX)BidirectionalIterator_test$(EXEEXT)\
$(TEST_PREFIX)ConstRandomAccessIterator_test$(EXEEXT)\
$(TEST_PREFIX)RandomAccessIterator_test$(EXEEXT)

EXECUTABLES_KERNEL = \
$(TEST_PREFIX)PTE_test$(EXEEXT)\
$(TEST_PREFIX)Atom_test$(EXEEXT)\
$(TEST_PREFIX)AtomStaticAtomAttributes_test$(EXEEXT)\
$(TEST_PREFIX)AtomAttributeVector_test$(EXEEXT)\
$(TEST_PREFIX)Bond_test$(EXEEXT)\
$(TEST_PREFIX)AtomContainer_test$(EXEEXT)\
$(TEST_PREFIX)Fragment_test$(EXEEXT)\
$(TEST_PREFIX)Chain_test$(EXEEXT)\
$(TEST_PREFIX)Molecule_test$(EXEEXT)\
$(TEST_PREFIX)SecondaryStructure_test$(EXEEXT)\
$(TEST_PREFIX)System_test$(EXEEXT)\
$(TEST_PREFIX)Protein_test$(EXEEXT)\
$(TEST_PREFIX)PDBAtom_test$(EXEEXT)\
$(TEST_PREFIX)NucleicAcid_test$(EXEEXT)\
$(TEST_PREFIX)Nucleotide_test$(EXEEXT)\
$(TEST_PREFIX)Residue_test$(EXEEXT)\
$(TEST_PREFIX)Expression_test$(EXEEXT)\
$(TEST_PREFIX)ExpressionParser_test$(EXEEXT)\
$(TEST_PREFIX)ExpressionPredicate_test$(EXEEXT)\
$(TEST_PREFIX)ExpressionTree_test$(EXEEXT)\
$(TEST_PREFIX)KernelPredicate_test$(EXEEXT)\
$(TEST_PREFIX)Selector_test$(EXEEXT)\
$(TEST_PREFIX)RuleEvaluator_test$(EXEEXT)\
$(TEST_PREFIX)StandardPredicates_test$(EXEEXT)\
$(TEST_PREFIX)DefaultProcessors_test$(EXEEXT)\
$(TEST_PREFIX)FragmentDB_test$(EXEEXT)\
$(TEST_PREFIX)NormalizeNamesProcessor_test$(EXEEXT)\
$(TEST_PREFIX)ForEach_test$(EXEEXT)\
$(TEST_PREFIX)GlobalKernel_test$(EXEEXT)\
$(TEST_PREFIX)CompositeIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)AtomIterator_test$(EXEEXT)\
$(TEST_PREFIX)AtomBondIteratorTraits_test$(EXEEXT)\
$(TEST_PREFIX)Extractors_test$(EXEEXT)

EXECUTABLES_MOLMEC = \
$(TEST_PREFIX)Gradient_test$(EXEEXT)\
$(TEST_PREFIX)AtomVector_test$(EXEEXT)\
$(TEST_PREFIX)MolmecSupport_test$(EXEEXT)\
$(TEST_PREFIX)SnapShot_test$(EXEEXT)\
$(TEST_PREFIX)SnapShotManager_test$(EXEEXT)\
$(TEST_PREFIX)ForceField_test$(EXEEXT)\
$(TEST_PREFIX)AmberFF_test$(EXEEXT)\
$(TEST_PREFIX)MMFF94_test$(EXEEXT)\
$(TEST_PREFIX)CharmmFF_test$(EXEEXT)\
$(TEST_PREFIX)EnergyMinimizer_test$(EXEEXT)\
$(TEST_PREFIX)LineSearch_test$(EXEEXT)\
$(TEST_PREFIX)SteepestDescentMinimizer_test$(EXEEXT)\
$(TEST_PREFIX)ConjugateGradientMinimizer_test$(EXEEXT)\
$(TEST_PREFIX)StrangLBFGSMinimizer_test$(EXEEXT)\
$(TEST_PREFIX)ShiftedLVMMMinimizer_test$(EXEEXT)\
$(TEST_PREFIX)AtomTypes_test$(EXEEXT)

EXECUTABLES_NMR = \
$(TEST_PREFIX)AssignShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)RandomCoilShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)AnisotropyShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)ClearShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)CreateSpectrumProcessor_test$(EXEEXT)\
$(TEST_PREFIX)EFShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)HaighMallionShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)JohnsonBoveyShiftProcessor_test$(EXEEXT)\
$(TEST_PREFIX)ShiftModel_test$(EXEEXT)\
$(TEST_PREFIX)ShiftModule_test$(EXEEXT)\
$(TEST_PREFIX)Spectrum_test$(EXEEXT)\
$(TEST_PREFIX)Peak_test$(EXEEXT)\
$(TEST_PREFIX)PeakList_test$(EXEEXT)

EXECUTABLES_FORMATS = \
$(TEST_PREFIX)LineBasedFile_test$(EXEEXT)\
$(TEST_PREFIX)BinaryFileAdaptor_test$(EXEEXT)\
$(TEST_PREFIX)Bruker1DFile_test$(EXEEXT)\
$(TEST_PREFIX)Bruker2DFile_test$(EXEEXT)\
$(TEST_PREFIX)INIFile_test$(EXEEXT)\
$(TEST_PREFIX)JCAMPFile_test$(EXEEXT)\
$(TEST_PREFIX)KCFFile_test$(EXEEXT)\
$(TEST_PREFIX)Parameters_test$(EXEEXT)\
$(TEST_PREFIX)ParameterSection_test$(EXEEXT)\
$(TEST_PREFIX)ResourceFile_test$(EXEEXT)\
$(TEST_PREFIX)GenericMolFile_test$(EXEEXT)\
$(TEST_PREFIX)HINFile_test$(EXEEXT)\
$(TEST_PREFIX)MOLFile_test$(EXEEXT)\
$(TEST_PREFIX)SDFile_test$(EXEEXT)\
$(TEST_PREFIX)MOL2File_test$(EXEEXT)\
$(TEST_PREFIX)NMRStarFile_test$(EXEEXT)\
$(TEST_PREFIX)DCDFile_test$(EXEEXT)\
$(TEST_PREFIX)PDBRecords_test$(EXEEXT)\
$(TEST_PREFIX)PDBInfo_test$(EXEEXT)\
$(TEST_PREFIX)PDBFile_test$(EXEEXT)\
$(TEST_PREFIX)TrajectoryFile_test$(EXEEXT)\
$(TEST_PREFIX)XYZFile_test$(EXEEXT)\
$(TEST_PREFIX)CCP4File_test$(EXEEXT)\
$(TEST_PREFIX)SCWRLRotamerFile_test$(EXEEXT)

EXECUTABLES_ENERGY = \
$(TEST_PREFIX)AtomicContactEnergy_test$(EXEEXT)\
$(TEST_PREFIX)ComposedEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)EnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)OoiEnergy_test$(EXEEXT)

EXECUTABLES_STRUCTURE = \
$(TEST_PREFIX)Enumerator_test$(EXEEXT)\
$(TEST_PREFIX)BindingPocketProcessor_test$(EXEEXT)\
$(TEST_PREFIX)EnumeratorIndex_test$(EXEEXT)\
$(TEST_PREFIX)AnalyticalSES_test$(EXEEXT)\
$(TEST_PREFIX)MolecularGraph_test$(EXEEXT)\
$(TEST_PREFIX)NumericalSAS_test$(EXEEXT)\
$(TEST_PREFIX)PeptideBuilder_test$(EXEEXT)\
$(TEST_PREFIX)Peptides_test$(EXEEXT)\
$(TEST_PREFIX)RadialDistributionFunction_test$(EXEEXT)\
$(TEST_PREFIX)RDFIntegrator_test$(EXEEXT)\
$(TEST_PREFIX)RDFParameter_test$(EXEEXT)\
$(TEST_PREFIX)RDFSection_test$(EXEEXT)\
$(TEST_PREFIX)ReconstructFragmentProcessor_test$(EXEEXT)\
$(TEST_PREFIX)ResidueChecker_test$(EXEEXT)\
$(TEST_PREFIX)SmilesParser_test$(EXEEXT)\
$(TEST_PREFIX)AtomBijection_test$(EXEEXT)\
$(TEST_PREFIX)SmartsParser_test$(EXEEXT)\
$(TEST_PREFIX)SmartsMatcher_test$(EXEEXT)\
$(TEST_PREFIX)StructureMapper_test$(EXEEXT)\
$(TEST_PREFIX)TransformationProcessor_test$(EXEEXT)\
$(TEST_PREFIX)TranslationProcessor_test$(EXEEXT)\
$(TEST_PREFIX)SurfaceProcessor_test$(EXEEXT)\
$(TEST_PREFIX)SecondaryStructureProcessor_test$(EXEEXT)\
$(TEST_PREFIX)UCK_test$(EXEEXT)\
$(TEST_PREFIX)BuildBondsProcessor_test$(EXEEXT)\
$(TEST_PREFIX)DockResult_test$(EXEEXT)\
$(TEST_PREFIX)MoleculeAssembler_test$(EXEEXT)\
$(TEST_PREFIX)SDGenerator_test$(EXEEXT)\
$(TEST_PREFIX)RingAnalyser_test$(EXEEXT)\
$(TEST_PREFIX)ResidueRotamerSet_test$(EXEEXT)\
$(TEST_PREFIX)RotamerLibrary_test$(EXEEXT)\
$(TEST_PREFIX)ConnectedComponentsProcessor_test$(EXEEXT)\
$(TEST_PREFIX)AssignBondOrderProcessor_test$(EXEEXT)

EXECUTABLES_SOLVATION = \
$(TEST_PREFIX)PoissonBoltzmann_test$(EXEEXT)\
$(TEST_PREFIX)SolventDescriptor_test$(EXEEXT)\
$(TEST_PREFIX)SolventParameter_test$(EXEEXT)\
$(TEST_PREFIX)ClaverieParameter_test$(EXEEXT)\
$(TEST_PREFIX)ReissCavFreeEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)UhligCavFreeEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)PCMCavFreeEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)PierottiCavFreeEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)Pair6_12RDFIntegrator_test$(EXEEXT)\
$(TEST_PREFIX)Pair6_12InteractionEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)PairExpInteractionEnergyProcessor_test$(EXEEXT)\
$(TEST_PREFIX)PairExpRDFIntegrator_test$(EXEEXT)\
$(TEST_PREFIX)PARSE_test$(EXEEXT)

EXECUTABLES_QSAR = \
$(TEST_PREFIX)AromaticityProcessor_test$(EXEEXT)\
$(TEST_PREFIX)ConnectivityBase_test$(EXEEXT)\
$(TEST_PREFIX)ConnectivityDescriptors_test$(EXEEXT)\
$(TEST_PREFIX)Descriptor_test$(EXEEXT)\
$(TEST_PREFIX)PartialChargeProcessor_test$(EXEEXT)\
$(TEST_PREFIX)PartialChargeBase_test$(EXEEXT)\
$(TEST_PREFIX)PartialChargeDescriptors_test$(EXEEXT)\
$(TEST_PREFIX)RingPerceptionProcessor_test$(EXEEXT)\
$(TEST_PREFIX)SimpleBase_test$(EXEEXT)\
$(TEST_PREFIX)SimpleDescriptors_test$(EXEEXT)\
$(TEST_PREFIX)SurfaceBase_test$(EXEEXT)\
$(TEST_PREFIX)SurfaceDescriptors_test$(EXEEXT)

XDR_DEPENDENT_EXECUTABLES = \
$(TEST_PREFIX)XDRPersistenceManager_test$(EXEEXT)

VIEW_DEPENDENT_EXECUTABLES= \
$(TEST_PREFIX)BallAndStickModel_test$(EXEEXT)\
$(TEST_PREFIX)AddCartoonModel_test$(EXEEXT)\
$(TEST_PREFIX)LabelModel_test$(EXEEXT)\
$(TEST_PREFIX)LineModel_test$(EXEEXT)\
$(TEST_PREFIX)SurfaceModel_test$(EXEEXT)\
$(TEST_PREFIX)HBondModel_test$(EXEEXT)\
$(TEST_PREFIX)ColorRGBA_test$(EXEEXT)

GSL_DEPENDENT_EXECUTABLES= \
$(TEST_PREFIX)RMSDMinimizer_test$(EXEEXT)

SQL_DEPENDENT_EXECUTABLES= \
$(TEST_PREFIX)DBInterface_test$(EXEEXT)

ifeq ($(BALL_HAS_VIEW),true)
	ASIO_DEPENDENT_EXECUTABLES= \
	$(TEST_PREFIX)Socket_test$(EXEEXT)
endif
