DIRECTORY=MOLVIEW/GUI/FUNCTOR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glAtomBondModelConnector.C\
	glBallAndStickModel.C\
	glLineModel.C\
	glSurfaceModel.C\
	glVanDerWaalsModel.C\
	moleculeGLObjectCollector.C\
	moleculeObjectProcessor.C

include ../../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)
