DIRECTORY=MOLMEC/MINIMIZATION

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	conjugateGradient.C\
	energyMinimizer.C\
	lineSearch.C\
	steepestDescent.C\
	strangLBFGS.C\
	shiftedLVMM.C

include ../../common.mak
-include .Dependencies
