DIRECTORY=MOLMEC/MINIMIZATION

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	energyMinimizer.C\
	lineSearch.C\
	conicLineSearch.C\
	steepestDescent.C\
	strangLBFGS.C\
	shiftedLVMM.C\
	conjugateGradient.C

include ../../common.mak
-include .Dependencies
