#!/opt/gnu/bin/gawk -f
/^res /{
	name=$3
	print "(" name
	print "  (Names"
	print "  )"
	print "  (Atoms"
	number_of_bonds = 0
	number_of_atoms = 0
}
/^atom /{
	atoms[$2] = $3
	print "    (" $3, $4, $8, $9, $10 ")"

	number_of_atoms++

	if ($11 > 0){
		for (i = 1; i <= $11; i++){
			number_of_bonds++
			bonds_B[number_of_bonds] = $(10 + 2 * i)
			bonds_A[number_of_bonds] = $2
		}
	}
}
END{
	print "  )"
	print "  (Bonds"
	for (i = 1; i <= number_of_bonds; i++){
		if (bonds_A[i] > bonds_B[i])
			print "    (" atoms[bonds_A[i]] " " atoms[bonds_B[i]] ")"
	}
	print "  )"
	print ")"
}


	
	
	
	
