## Detect the raytracing library rtfact

INCLUDE(CheckLibraryExists)

SET(RTFACT_ROOT_DIR ${RTFACT_ROOT_DIR} CACHE PATH "Path to the root RTfact ray tracer (i.e. where include/RTpie directory resides")

## Set some possible paths to use when looking for the RTfact installation
SET(RTFACT_POSSIBLE_ROOT_DIRS
	${RTFACT_ROOT_DIR}
	$ENV{RTFACT_ROOT_DIR}
)

## First, try to find the required header files (RTremote/Renderer.hpp)
FIND_PATH(RTFACT_INCLUDE_PATH
	NAMES RTpie/IRayTracer.hpp
	PATHS ${RTFACT_POSSIBLE_ROOT_DIRS}
	PATH_SUFFIXES include
	DOC "RTfact header include dir")

IF (NOT RTFACT_INCLUDE_PATH)
	MESSAGE(STATUS "Could not find RTfact header file (RTpie/IRayTracer.hpp)! Real time ray tracing will be disabled!")
ELSE()
	SET(RTFACT_INCLUDE_DIR ${RTFACT_INCLUDE_PATH} CACHE STRING "Full path to the RTfact headers")

	## Now, try to find the rtfact library itself.
	FIND_LIBRARY(RTFACT_LIBRARY
		NAMES RTfactRTpie
		PATHS ${RTFACT_POSSIBLE_ROOT_DIRS} ${RTFACT_POSSIBLE_ROOT_DIRS}/build ${RTFACT_POSSIBLE_ROOT_DIRS}/build_x64
		PATH_SUFFIXES lib Release lib/Release
		DOC "RTfact library, optimized")

	## And a possible debug version
	FIND_LIBRARY(RTFACT_LIBRARY_DEBUG
		NAMES RTfactRemoted RTfactRTpied
		PATHS ${RTFACT_POSSIBLE_ROOT_DIRS} ${RTFACT_POSSIBLE_ROOT_DIRS}/build ${RTFACT_POSSIBLE_ROOT_DIRS}/build_x64
		PATH_SUFFIXES lib Debug lib/Debug
		DOC "RTfact library, debug")

	IF (RTFACT_LIBRARY)
		GET_FILENAME_COMPONENT( _RTFACT_LIBRARY_NAME ${RTFACT_LIBRARY} NAME )
        GET_FILENAME_COMPONENT( _RTFACT_LIBRARY_PATH ${RTFACT_LIBRARY} PATH )
        
        GET_FILENAME_COMPONENT( _RTFACT_LIBRARY_DEBUG_NAME ${RTFACT_LIBRARY_DEBUG} NAME )
        GET_FILENAME_COMPONENT( _RTFACT_LIBRARY_DEBUG_PATH ${RTFACT_LIBRARY_DEBUG} PATH )
        
        BALL_COMBINE_LIBS(RTFACT_LIBRARIES ${_RTFACT_LIBRARY_NAME} ${_RTFACT_LIBRARY_DEBUG_NAME})
        SET(_RTFACT_LIBRARY_DIRS ${_RTFACT_LIBRARY_PATH} ${_RTFACT_LIBRARY_DEBUG_PATH})
        list(REMOVE_DUPLICATES _RTFACT_LIBRARY_DIRS)
        SET(RTFACT_LIBRARY_DIRS ${_RTFACT_LIBRARY_DIRS} CACHE PATH "Directoris with RTfact libraries")
		SET(RTFACT_FOUND TRUE)
	ELSE()
		MESSAGE(STATUS "Could not find RTfact libraries!")
		SET(RTFACT_FOUND FALSE)
	ENDIF()

	INCLUDE(FindPackageHandleStandardArgs)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(RTFACT DEFAULT_MSG
		RTFACT_INCLUDE_DIR
		RTFACT_LIBRARIES)

	MARK_AS_ADVANCED(RTFACT_INCLUDE_DIR)
	MARK_AS_ADVANCED(RTFACT_LIBRARIES)

ENDIF()
