DIRECTORY=VIEW/GUI/PRIMITIV

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glline.C\
	gllabel.C\
	glmesh.C\
	glpoint.C\
	glsimpleBox.C\
	glsphere.C\
	gltube.C

include ../../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)

