/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgDisplayPropertiesData.h
	Last generated: Mon Jan 10 15:21:18 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef DlgDisplayPropertiesData_included
#define DlgDisplayPropertiesData_included

#include <qdialog.h>

class DlgDisplayPropertiesData : public QDialog
{
    Q_OBJECT

public:

    DlgDisplayPropertiesData(QWidget *parent = NULL, const char *name = NULL);

    virtual ~DlgDisplayPropertiesData();
};

#endif // DlgDisplayPropertiesData_included
