// $Id: icons.C,v 1.3 2000/04/04 15:05:43 oliver Exp $

// this file contains the icons needed by MolVIEW in XPM format

// the network server activity icon
const char * mini_ray_xpm[] =
{
	"16 14 4 1",
	"   c None",
	".  c black",
	"X  c yellow",
	"o  c gray50",
	"     .........  ",
	"     .XXXXXX.o  ",
	"    .XXXXXX.o   ",
	"    .XXXXX.o    ",
	"   .XXXXX.o     ",
	"   .XXXX.....   ",
	"  .XXXXXXXX.o   ",
	"  .....XXX.o    ",
	"   oo.XXX.o     ",
	"     .XX.o      ",
	"    .XX.o       ",
	"    .X.o        ",
	"   .X.o         ",
	"   ..o          "
};
 

// the application icon - the BALL bucky (64x64)
const char * bucky_64x64_xpm[] = 
{
	"64 64 257 2",
	"  	c None",
	". 	c #060614",
	"+ 	c #86863E",
	"@ 	c #48481F",
	"# 	c #CACA8C",
	"$ 	c #676731",
	"% 	c #292912",
	"& 	c #A6A66A",
	"* 	c #262690",
	"= 	c #484898",
	"- 	c #6666B4",
	"; 	c #86869C",
	"> 	c #797933",
	", 	c #383816",
	"' 	c #585829",
	") 	c #E6E6E2",
	"! 	c #161609",
	"~ 	c #A6A6B6",
	"{ 	c #979757",
	"] 	c #D6D6C9",
	"^ 	c #363684",
	"/ 	c #161659",
	"( 	c #686868",
	"_ 	c #282851",
	": 	c #5858B8",
	"< 	c #969695",
	"[ 	c #48485F",
	"} 	c #76766F",
	"| 	c #56566F",
	"1 	c #B6B6B5",
	"2 	c #86866A",
	"3 	c #38384E",
	"4 	c #B6B68E",
	"5 	c #161634",
	"6 	c #C6C6D2",
	"7 	c #3636C7",
	"8 	c #4747D7",
	"9 	c #6F6F30",
	"0 	c #E0E0C8",
	"a 	c #303016",
	"b 	c #505022",
	"c 	c #7676AC",
	"d 	c #5F5F2A",
	"e 	c #9696D0",
	"f 	c #B6B6EC",
	"g 	c #0A0A2E",
	"h 	c #2F2F51",
	"i 	c #2E2E8F",
	"j 	c #7E7E40",
	"k 	c #A0A061",
	"l 	c #707069",
	"m 	c #F6F6F6",
	"n 	c #3E3E1C",
	"o 	c #8E8E6A",
	"p 	c #1E1E54",
	"q 	c #91914A",
	"r 	c #505099",
	"s 	c #9E9E99",
	"t 	c #80806A",
	"u 	c #A6A690",
	"v 	c #5959D1",
	"w 	c #BEBEB5",
	"x 	c #8C8CC8",
	"y 	c #3E3E56",
	"z 	c #1E1E36",
	"A 	c #CECED1",
	"B 	c #0E0E05",
	"C 	c #EFEFEC",
	"D 	c #20200F",
	"E 	c #B0B0AF",
	"F 	c #3E3E84",
	"G 	c #505060",
	"H 	c #5E5E64",
	"I 	c #BEBE74",
	"J 	c #28282E",
	"K 	c #6868E4",
	"L 	c #D9D9E6",
	"M 	c #474741",
	"N 	c #D1D1AF",
	"O 	c #666655",
	"P 	c #4242BC",
	"Q 	c #6E6E51",
	"R 	c #5E5E4D",
	"S 	c #AEAE8F",
	"T 	c #767652",
	"U 	c #262676",
	"V 	c #E1E1E9",
	"W 	c #2F2FB2",
	"X 	c #4646B8",
	"Y 	c #919194",
	"Z 	c #56564A",
	"` 	c #66668C",
	" .	c #868684",
	"..	c #2E2E3E",
	"+.	c #505045",
	"@.	c #9F9F86",
	"#.	c #202080",
	"$.	c #81818E",
	"%.	c #5E5ECC",
	"&.	c #898951",
	"*.	c #98987B",
	"=.	c #7676E4",
	"-.	c #303071",
	";.	c #717191",
	">.	c #404035",
	",.	c #505087",
	"'.	c #2828A3",
	").	c #6F6FA5",
	"!.	c #383844",
	"~.	c #4F4FDE",
	"{.	c #808054",
	"].	c #A1A1B4",
	"^.	c #3F3F6F",
	"/.	c #E9E9EE",
	"(.	c #D8D8D7",
	"_.	c #9999B2",
	":.	c #B8B8C7",
	"<.	c #B8B8A2",
	"[.	c #919183",
	"}.	c #C0C0C6",
	"|.	c #212148",
	"1.	c #CFCFEA",
	"2.	c #11111D",
	"3.	c #AFAFD2",
	"4.	c #606078",
	"5.	c #484830",
	"6.	c #C7C7B3",
	"7.	c #68683F",
	"8.	c #282820",
	"9.	c #4848A8",
	"0.	c #606098",
	"a.	c #7E7EAA",
	"b.	c #B2B27C",
	"c.	c #C1C1D9",
	"d.	c #9E9ECC",
	"e.	c #8282E4",
	"f.	c #9292E8",
	"g.	c #121246",
	"h.	c #A9A9D7",
	"i.	c #3838B1",
	"j.	c #383876",
	"k.	c #C6C6F8",
	"l.	c #4F4FC1",
	"m.	c #5858F9",
	"n.	c #4040B1",
	"o.	c #BFBF9C",
	"p.	c #4242E4",
	"q.	c #5E5EFC",
	"r.	c #5E5EB9",
	"s.	c #FEFEFC",
	"t.	c #797987",
	"u.	c #565684",
	"v.	c #3A3AE1",
	"w.	c #7878C4",
	"x.	c #7171BC",
	"y.	c #4F4FF2",
	"z.	c #08081E",
	"A.	c #6666C4",
	"B.	c #8888B8",
	"C.	c #181820",
	"D.	c #1A1A6E",
	"E.	c #464678",
	"F.	c #191946",
	"G.	c #3030A0",
	"H.	c #1F1F71",
	"I.	c #AAAAA0",
	"J.	c #8E8EE4",
	"K.	c #B1B1A1",
	"L.	c #9090AF",
	"M.	c #C0C0F4",
	"N.	c #787843",
	"O.	c #373727",
	"P.	c #585836",
	"Q.	c #96966C",
	"R.	c #373798",
	"S.	c #676778",
	"T.	c #272760",
	"U.	c #4A4AE9",
	"V.	c #707040",
	"W.	c #E0E0D8",
	"X.	c #323227",
	"Y.	c #51512D",
	"Z.	c #616139",
	"`.	c #2F2F61",
	" +	c #A1A16F",
	".+	c #707077",
	"++	c #909056",
	"@+	c #808077",
	"#+	c #F1F1F6",
	"$+	c #212121",
	"%+	c #B1B1BE",
	"&+	c #3F3F99",
	"*+	c #505070",
	"=+	c #C0C088",
	"-+	c #28283F",
	";+	c #6767FA",
	">+	c #D9D9F9",
	",+	c #494950",
	"'+	c #D0D0C3",
	")+	c #4040D1",
	"!+	c #DFDFF6",
	"~+	c #3232C4",
	"{+	c #22228E",
	"]+	c #5F5FDF",
	"^+	c #999988",
	"/+	c #C8C8BF",
	"(+	c #8282BC",
	"_+	c #A0A0E4",
	":+	c #7E7EFC",
	"<+	c #0A0A0E",
	"[+	c #8A8A40",
	"}+	c #2A2A89",
	"|+	c #6A6AA4",
	"1+	c #8A8AA2",
	"2+	c #EAEAE1",
	"3+	c #1A1A0E",
	"4+	c #AAAAAF",
	"5+	c #DADAC8",
	"6+	c #1A1A60",
	"7+	c #9A9A99",
	"8+	c #7A7A6D",
	"9+	c #5A5A68",
	"0+	c #BABAB7",
	"a+	c #8A8A6F",
	"b+	c #BABA8C",
	"c+	c #1A1A38",
	"d+	c #CACAD0",
	"e+	c #3A3ABF",
	"f+	c #7A7AB4",
	"g+	c #9A9AD4",
	"h+	c #BABAE4",
	"i+	c #0E0E36",
	"j+	c #323294",
	"k+	c #82823F",
	"l+	c #FAFAFB",
	"m+	c #42421D",
	"n+	c #929274",
	"o+	c #222260",
	"p+	c #A2A29A",
	"q+	c #AAAA93",
	"r+	c #C2C2B5",
	"s+	c #424252",
	"t+	c #222237",
	"u+	c #D2D2D0",
	"v+	c #121208",
	"w+	c #626266",
	"x+	c #6A6A53",
	"y+	c #727255",
	"z+	c #62624B",
	"A+	c #B2B294",
	"B+	c #7A7A51",
	"C+	c #2A2A76",
	"D+	c #4A4ABF",
	"E+	c #5A5A50",
	"F+	c #6A6A8C",
	"G+	c #8A8A84",
	"H+	c #32323A",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s._.r x m s.s.C C s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.:.D.{+n.x.'+p+U D+f s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.u+o y {+P `., m+@ @ '.= 6.#+s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.d+o P.Y.d ' * ~+3 m+n , , -.[ N.V.a+o.) s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.c.B.3.m /+a+Y.Z.V.7.V.^+u+).* _ , @ @ @ n n @ R s+`.4.{.4 W.3.w.h+s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.A / * ~.[ 7.B+N.B+@.] s.s.%+'.3 n Q 5+V ^+' @ m+z #.H.* s+d Z.* 6+T.1.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s._.H.~+7 &+T p+W.s.s.C <.a+Z '.&+u.s.s.s.s.l+w y+* '.* H.|.@ 5.`.v+% y+) C 1.m s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.C ,+X.F+i.j+L s.) <.&.N.V.j p+).j.,+W.s.s.s.s.s.#+j+H+_ D.2.O., , , O.a n i i.9.V s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.l+a.r O.D j V.C+i y.;.j N.2 q+W.s.s.s.m Z.V.m s.s.s.s.s. .+.m+[ }.^+8+5.% D D % h * D.L.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.E D.z 8.@ { $ 9 Z.8 9.I.) s.s.s.s.s.s.s.V b 2 s.s.s.s.s.Q Z.@+s.s.s.s.s.2+3+D ! _ '.6+].s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.%+{+j+a q j p+S j.* d.s.s.s.s.s.s.s.s.s.s.d+m+u.h.s.s.C , P.w s.s.s.s.s.s.} v+^.<+6++.y+s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.@++.T.d + W.s.s.G+P.s.s.s.s.s.s.s.s.s.s.s.s.2.g.T.u W.E @ Y.#+s.s.s.s.s.s.$.<+p ).u+B+' ^+s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.1 $ V.5.+  +s.s.s.a+Z.s.s.s.s.s.s.s.s.s.s.s.@+B z.G O.8., Y.R l+) 1.s.d+@+O.B . . S.s.6.B+b r+s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.W.P.z+w+9 j C s.s.s.G+z+s.s.s.s.s.s.s.s.s.s.l 2.E l+s.s.A a m+8.5.p U 8.D >.@+:.F+J O.) s.p+V.b V s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.l+>.5 {+~+A.1 s.s.s.s.a+7.s.s.s.s.s.s.s.s.l+9+D /+s.s.s.W.)._ y '+Y / o+( W.s.s.s.s.) z+j l+l+2 Z.7.m s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.t.<+g.{+W U.J.s.s.s.A c+-+3.) m s.s.s.#+c.+.8.] s.s.s.!+-.{+{+F h.l+_.H+L s.s.s.s.s.s.r+N. +s.C V.Y.2 s.s.s.s.s.s.",
	"s.s.s.s.s.s.0+v+C./ * = O..+l+s.s.4+z.i+-+m+5.P.x+t s+C+8.V s.s.s.#+;.* * {+/ ^.s.l+Y.r+s.s.s.s.s.s.s.p+V.o.s.] d @ K.s.s.s.s.s.",
	"s.s.s.s./.:.' @ E+g.#.o+D a Z.u+s.w+D 4.V V d+1 s [.t+g w+s.C 1 {.@ >.'.v * / ^.l+s.T ^+s.s.s.s.s.s.s.s.t 9 W.s.<.' s+e.e l+s.s.",
	"s.s.s.L T.{+: +.a n .+1+< a a m+B+% 0+s.s.s.s.s.s.s.W.!.x+B+Y.b b b @ j+'.#.p P.l+s.^+T s.s.s.s.s.s.s.s.C V.y+f /.,.W '.{+L.s.s.",
	"s.s.s.]./ G i.% n t l+s.s.) R % O.' 6.#+L C s.s./.K.B+Y.d ' b @ O p+W.L f+4.B+@ a+s.6.Y.l+s.s.s.s.s.s.s.s.:.7 ~.l.G.l.* / ` s.s.",
	"s.s.s.) 8.d % , y+l+s.s.s.s.m X.D D $+* '.K L.y+Y.N.k+V.b 7.q+) s.s.s.s.s.l+a+V.m+<.C b }.s.s.s.s.s.s.s.s.h.G.*+P.0.y +.c+6 s.s.",
	"s.s.s.A a a , z+m s.s.s.s.s.8+D w M i+{+'.p.X > N.' T E T u s.s.s.s.s.s.s.s.m V.' m+1+P U.>+s.s.s.s.s.s.s.^+_ 4.P.V.d Z.>.s.s.s.",
	"s.s.~ s+D a n ] s.s.s.s.%+5 <+p+s.6 / * l.e+'.x+K.C l+s.r+V.C s.s.s.s.s.s.s.l+W.d @ O.j+j.&.N s.s.s.s.s.'+@ ^+s.] d ' Z.! 1.s.s.",
	"s._./ #., X., K.s.s.) S Y.B z.%+s.m T.{+'.'.* /.s.s.s.s.:.X m.C s.s.s.s.s.s.s.s.^+b m++.] p+7.&.'+s.s.#+P.x+s.s.s.2+d ' B 6+}.s.",
	"s.4.H.G.X 7 % H ].T @ 5.@+y . ] s.s.6 h j.-.:.s.s.s.s.s.~ G.R.&.4 N 2+s.s.s.m Q.Y.{.b n @.s.C @.7.++h.( 5./.s.s.s.2+$ b <+g 1+s.",
	"s.:./ {+* {+T.r.)+l 1 m s.l+X..+l+s.s.8+k+7.s.s.s.s.s.C T ^+) /.<.*.&.++s ]+( y+W.l+T @ , 6.s.s.2+@+7 ^.` s.s.s.s.W.$ @ . J ) s.",
	"s.s.s +.( ~ H.'.x.s.s.s.s.s.4+B ) s.s.@+j z+s.s.s.s.s.o a+s.s.s.s.s.l+d+` G.C+l+s.s.2+d @ 5.W.s.s.) j+#.L.s.s.s.s.N $ @ <+< s.s.",
	"s.s.w V.k s.$.B+m s.s.s.s.s.s.O.@.s.s.@+N.Z.s.s.s.s.0+T C s.s.s.s.s.s.s.C | 7+s.s.s.s.A b m+z+!+#+s.E V.l+s.s.s.s.6.Z.m+3+Y s.s.",
	"s.s.}.7.{ s.n+{ l+s.s.s.s.s.s.4+' #+s.@+$ R s.s.l+W.+ '+s.s.s.s.s.s.s.s.s.{.w s.s.s.s.s.q+@ j.v.%.g+K.Q s.s.s.l+>+~.~.X y Y s.s.",
	"s.s.}.Z.Q.s.*.q l+s.s.s.s.s.s.l+R a.>+2 ' P.s.l+J.c I.s.s.s.s.s.s.s.s.s.s.o w s.s.s.s.s.m j+e+'.{+6+E+b y+Q Q x++.y '.* 6+^+s.s.",
	"s.s./+d &.s.< ++l+s.s.s.s.s.s.s.i m.D+Y.' b > > X U.h+s.s.s.s.s.s.s.s.s.s.Q.6.s.s.s.s.s.V '.l.{+/ i+2.! v+v+v+v+! v+/ / g < s.s.",
	"s.s.d+' B+s.@.[+m s.s.s.s.s.s.s.8+,.].} @ ' ) 2+a.*+<.s.s.s.s.s.s.s.s.s.s.Q.r+s.s.s.s.s.l+^ {+H.i+z.E+m+Y 7+p+u .+. . g D 7+s.s.",
	"s.s.u+b V.s.@.[+#+s.s.s.s.s.s.W.+ ] s.o b b s.s.s.) ++'+s.s.s.s.s.s.s.s.s.Q.r+s.s.s.s.s.<.d J i+t+4+w 9 s.s.s.s.s.Y <+<+7.*.s.s.",
	"s.s.u+b 7.s.p++ #+s.s.s.s.s.s.G+&.s.s.Y @ b s.s.s.s./+q ) s.s.s.s.s.s.s.L v =.l+s.s.s.W.V.n >.C s.s.|+: f s.s.s.s.A B B Z.*.s.s.",
	"s.s.5+@ V.s.a.0.M.s.s.s.s.s.C ' 0+s.s.*.@ @ s.s.s.s.s.q+k m s.s.s.s.] 4 8+e+9.'+s.s.m 2 P.% u+s.s.6 }+P r s.s.s.s.2+<+B r v V s.",
	"s.s.6 s+4._.W ;+)+L s.s.s.s.< d m s.s.< @ @ s.s.s.s.s.l+o @.k.W.o.{.V.*.r+d.^+V.S m *.j % s s./.n+@ ,.M 7.#+s.s.s.s.v+B = W x.s.",
	"s.V i v.;+W H+y+U m+5.[.W.c.[ p+s.s.s.7+m+b m s.s.s.s.s.A v.m.{.@.d+l+s.s.s.s.2+{.N.&., z+m S $ x+'+s.C V.k l+s.s.s.8.B ' t+$.s.",
	"s.7+D.~+]+R.>.R L r+8+X.a !.j+e s.s.d+i '.'.v C s.s.s.s./.*+R.!+s.s.s.s.s.s.s.s.) N.Y.z w.V.d 1 s.s.s.s.u+V.4 s.l+o ! <+@ @+l+s.",
	"s.u+g.D.>.$ m+t s.s.s.s.~ z.i+; s.s.E.#.)+D+{+1+s.s.s.s.C q 2+s.s.s.s.s.s.s.s.s.{.Z.D G.8 .+m s.s.s.s.s.s.q+x+f.} , D B a 2+s.s.",
	"s.s.6 4.! m+9 @.l+s.s.s.s.}.( @ W.l+F.6+{+{+H.( {.Q.6.m r+k s.s.s.s.s.s.s.s.s.u $ a G+} 4.W.s.s.s.s.s.s.s.C * r a ( t+<+c+c.s.s.",
	"s.s.s.s.>.3+b V.'+s.s.s.s.s.l++.R >.<+g g./ i+a 5.7.$ [+& b+C s.s.s.s.s.s.s.'+d , +.l+&.w s.s.s.s.s.s.s.s.#+}+'./ H+. <+g.j.s.s.",
	"s.s.s.s.,+! D b > '+s.s.s.s.s.s % v+B [ -+y E r+@+>.% n b $ +  +N ) l+s.k.e z+m+a /.#+b '+s.s.s.s.s.s.s.s.K.Z.4.~ $.. . z.|.s.s.",
	"s.s.s.l+z p i.z b > u+s.s.#+y+D ! 3+Q.s.s.s.s.s.s.s.5+,...% a m+@ Z.N.;.'.W #.$+0+s./+b #+s.s.s.s.s.s.s.W.T y+s.l+s+. . c+1 s.s.",
	"s.s.s.s.; / o+2 , ' w+:+(+m+D v+O s + _+>+s.m ) 5+N @.y.y.W.%+y+O.% , -.n.n.H.g.A s.<.q s.s.s.s.s.s.s.m &.P./.s.*.v+D W.l+s.s.s.",
	"s.s.s.s.s.#+E V.k H+'.p.$+! $+E s.s.9.q.y.{ [+> N.j 8+{+*+o.s.s.s.u+ .D.#.H./ g }.s.u  +s.s.s.s.s.s.s.S 7./+s.}.8.v+%+s.s.s.s.s.",
	"s.s.s.s.s.s.s.o &.H+{+~+|.<+}.s.s.s.,.H r 1 u+C s.s.s.L 0+V. +m s.s.s.[ g.i+g t+m g+m.K l+s.s.s.s.s.6.&.[.s.C X.v+} s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.l+x+t+g.H.H.z m s.s.s.V > /+s.s.s.s.s.s.s.s.W.d y+/.s.s.#+.+5 z.z+o.,.)+R &.4 5+m C h+++Q l+s.Z 3+>.m s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.2+5.c+g i+B A s.s.s.l+' o.s.s.s.s.s.s.s.s.s./.V.q u+!+l+0 z+B D {.7+,.$.n+z+' 7.8 q.X ] s.< v+3+] s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.A ' q O.a +.s.s.s.s.@ u s.s.s.s.s.s.s.s.s.s.m t.p.m.@+B+B+B B 6.s.s.s.s.s.W.~ j.0.'.A u+v+v+p+s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.I.Z.N.D D u s.s.s.7.S s.s.s.s.s.s.s.s.s.s.s.:.( )+c 2+s.>.<+l s.s.s.s.s.s.s.++Z.h F+J B w+s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s..+)+C+v+X.] C L l.=./.s.s.s.s.s.s.s.s.s.s.& j t.#+s.s.< B % l+s.s.s.s.s.0 k+{.i+. . c+#+s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.` {+8.! v+, m+9 ` m.J.2+s.s.s.s.s.s.s.s.o.j ] s.s.s.s./.v+B 1 s.s.s.l+5+n+d b a . . g.) s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.].. <+3+B D !...U }+O k k ^+r+#+s.s.s.5+[+q+s.s.s.s.s.l+..B _ x.q+{.' @ , a D B . . c+m s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.d+1 l B v+-+X r 1 C 1 t R Z.[+# d+;+]+t l+s.s.s.s.s.:.z.B / H...% D D ! 3+8.G+w+9+d+s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.H <+6+H.^.6.#+s.s.l+'+Y V.G U.- _.s.s.s.s.C I.+.6+z.i+i+J P.M G.t+2.) s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.t.z.i+6+H+k I =+4 5+s.s.l+L.H.X.Z.k W.W.*.' @ a i+g.g g $ ' O U g.4.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.V 3 g.y < O , ' $ 7.V.n+r+#+).j+3 b $ b n % % $ 2 8.C.E+I./.s.#+W.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.l+C s.s.s.#+1 8+5., Y.' N.v.K w+@ a D a i.0.' Q ~ C s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.] *.R H+'.U.h ! v+D 3+D.u.2+s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s / #./ H d+4+t+!.(.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.l+t.h S.m s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.l+s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.",
	"s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s."
};
