// $Id: color.h,v 1.7 2001/02/04 15:58:18 hekl Exp $

#ifndef BALL_VIEW_DATATYPE_COLOR_H
#define BALL_VIEW_DATATYPE_COLOR_H

#ifndef BALL_VIEW_DATATYPE_COLORHSV_H
#	include <BALL/VIEW/DATATYPE/colorHSV.h>
#endif

#ifndef BALL_VIEW_DATATYPE_COLORRGBA_H
#	include <BALL/VIEW/DATATYPE/colorRGBA.h>
#endif

#endif // <BALL/VIEW_DATATYPE_COLOR_H
