// $Id: color.h,v 1.7.4.1 2002/08/16 13:24:42 anhi Exp $

#ifndef BALL_VIEW_DATATYPE_COLOR_H
#define BALL_VIEW_DATATYPE_COLOR_H

#ifndef BALL_VIEW_DATATYPE_COLORHSV_H
#	include <BALL/VIEW/DATATYPE/colorHSV.h>
#endif

#ifndef BALL_VIEW_DATATYPE_COLORRGBA_H
#	include <BALL/VIEW/DATATYPE/colorRGBA.h>
#endif

#endif // BALL/VIEW_DATATYPE_COLOR_H
