DIRECTORY=CONCEPT

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	autoDeletable.C\
	callback.C\
	composite.C\
	embeddable.C\
	enumerator.C\
	notification.C\
	object.C\
	persistenceManager.C\
	processor.C\
	property.C\
	selectable.C\
	singleton.C\
	timeStamp.C\
	textPersistenceManager.C\
	visitor.C\
	XDRPersistenceManager.C

include ../common.mak
include .Dependencies
