<html>
<head>
	<TITLE>BALL Documentation: Class Hierarchy</TITLE>
</head>
<body bgcolor="#FFFFFF">
<table>
	<tr width=100%>
		<td width=20%>
			<A HREF="http://www.mpi-sb.mpg.de/BALL">
			<IMG BORDER=0 ALIGN=CENTER SRC=BALL_logo.gif></A>
		</td>
		<td width=60%>
			<center>
			<IMG BORDER=0 ALIGN=LEFT SRC=BALL.gif></A>
			</center>
		</td>
		<td width=20% ALIGN=RIGHT>
			Reference Manual<br>
			Release @RELEASE@
		</td>
	</tr>
</table>
<hr>
<table width=100%>
	<tr>
		<td width=33% align=center>
			<A HREF="INTRO.html"> introduction</A>
		</td>
		<td width=33% align=center>
			<A HREF="aindex.html"> alphabetic index</A>
		</td>
		<td width=33% align=center>
			<A HREF="HIER.html"> hierarchy of classes</A>
		</td>
	</tr>
</table>
<hr>

