#ifndef BALL_STRUCTURE_BONDORDERS_BONDORDERASSIGNMENT_H
#define BALL_STRUCTURE_BONDORDERS_BONDORDERASSIGNMENT_H

#ifndef BALL_COMMON_GLOBAL_H
# include <BALL/COMMON/global.h>
#endif

#ifndef BALL_DATATYPE_HASHMAP_H
# include <BALL/DATATYPE/hashMap.h>
#endif

#ifndef BALL_STRUCTURE_BONDORDERS_PARTIALBONDORDERASSIGNMENT_H
# include <BALL/STRUCTURE/BONDORDERS/partialBondOrderAssignment.h>
#endif

namespace BALL
{
	class AssignBondOrderProcessor;
	class AtomContainer;
	class Atom;
	class Bond;

	/** \brief A solution to the bond order assignment problem.
	 *  
	 *  This class represents a full bond order assignment as it
	 *  is generated by the \link AssignBondOrderProcessor AssignBondOrderProcessor \endlink
	 *  through a \link BondOrderAssignmentStrategy BondOrderAssignmentStrategy \endlink.
	 * 
	 */
	class BALL_EXPORT BondOrderAssignment
		: public PartialBondOrderAssignment
	{
		friend class AssignBondOrderProcessor;

		public:
			// Default constructor
			BondOrderAssignment(AssignBondOrderProcessor* abop);

			// Destructor
			virtual ~BondOrderAssignment();

			// 
			void clear();

			/// Apply the solution to the AtomContainer
			bool apply();

			// 
			int getNumberOfNodeExpansions() const {return node_expansions;}

			//
			int getQueueSize() const {return queue_size;}

			// denotes whether the problem could be solved or not
			bool valid;

			// v2.2 H3d.D (D-H3.8) + H3d closing-CR MEDIUM finding 5:
			//
			// bond_order_map + number_of_virtual_hydrogens are populated
			// by the bond-order solver and consumed inside the same
			// AssignBondOrderProcessor::apply() invocation that produced
			// them. Inside one apply() they ARE pure scratch. HOWEVER --
			// the parent ABO retains its solutions_ vector (which holds
			// BondOrderAssignment values) BETWEEN apply() calls until
			// the next ABO::start() -> clear() runs, and the public
			// ABO API exposes those solutions through `getNumberOf...
			// Assignments()` and `apply(solution_index)`. A caller who
			// mutates the underlying MoleculeStore (compact() /
			// release_atom) AFTER apply() but BEFORE consuming a
			// solution via these accessors will see stale Atom*/Bond*
			// pointers inside the cached bond_order_map and
			// number_of_virtual_hydrogens.
			//
			// This is a documented RESIDUAL HAZARD, not pure scratch.
			// Callers MUST treat ABO solutions as "valid only until the
			// next MoleculeStore mutation OR the next ABO::apply()".
			// H4 v0 retirement migrates these to sid-keyed forms;
			// until then, the caller-side discipline is the safety
			// boundary.

			// the result : the set of bond orders for _ALL_ original bonds
			HashMap<Bond*, int> bond_order_map;

			// the result part2: the atoms with n additional hydrogens
			HashMap<Atom*, int> number_of_virtual_hydrogens;

			// the virtual atoms and bonds that should be deleted when the next 
			// solution is applied
			vector<Atom*> atoms_to_delete;
			//vector<Bond*> bonds_to_delete;

			float total_charge;
			int node_expansions;
			int queue_size;

			AtomContainer* ac;
	};
}
#endif // BALL_STRUCTURE_BONDORDERS_BONDORDERASSIGNMENT_H

