DIRECTORY=FORMAT

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	genericPDBFile.C\
	HINFile.C\
	INIFile.C\
	lineBasedFile.C\
	MOL2File.C\
	parameters.C\
	parameterSection.C\
	PDBFile.C\
	resourceFile.C\
	XYZFile.C\
	NMRStarFile.C

include ../common.mak
include .Dependencies
