# $Id: Makefile,v 1.2 2006/02/21 16:28:41 anker Exp $
#
DIRECTORY=SCORING/COMPONENTS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	aromaticRingStacking.C\
	buriedPolar.C\
	CHPI.C\
	hydrogenBond.C\
	lipophilic.C\
	nonpolarSolvation.C\
	polarSolvation.C\
	rotationalEntropyLoss.C\
	vanDerWaals.C

include ../../common.mak
include .Dependencies
