# $Id: Makefile,v 1.1 2005/11/21 19:27:09 anker Exp $
#
DIRECTORY=SCORING/COMPONENTS

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	aromaticRingStacking.C\
	CHPI.C\
	nonpolarSolvation.C\
	polarSolvation.C\
	vanDerWaals.C

include ../../common.mak
include .Dependencies
