# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.6.14.1 2007/03/25 22:02:32 oliver Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/PRIMITIVES

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	box.C\
	disc.C\
	gridVisualisation.C\
	label.C\
	line.C\
	mesh.C\
	multiLine.C\
	quadMesh.C\
	point.C\
	simpleBox.C\
	sphere.C\
	tube.C\
	twoColoredLine.C\
	twoColoredTube.C

include ../../common.mak
-include .Dependencies
