# -*- Mode: C++; tab-width: 2; -*-
# vi: set ts=2:
#
# $Id: Makefile,v 1.6 2006/01/26 16:12:55 oliver Exp $
#
# Author:
#   Oliver Kohlbacher
#

DIRECTORY=VIEW/PRIMITIVES

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	label.C\
	line.C\
	mesh.C\
	point.C\
	box.C\
	disc.C\
	simpleBox.C\
	sphere.C\
	tube.C\
	twoColoredLine.C\
	twoColoredTube.C

include ../../common.mak
-include .Dependencies
