DIRECTORY=VIEW/PRIMITIVES

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	label.C\
	line.C\
	mesh.C\
	point.C\
	box.C\
	disc.C\
	simpleBox.C\
	sphere.C\
	tube.C\
	twoColoredLine.C\
	twoColoredTube.C

include ../../common.mak
include .Dependencies
