/****************************************************************************
** Form implementation generated from reading ui file 'displayProperties.ui'
**
** Created: Sun Nov 17 18:25:50 2002
**      by:  The User Interface Compiler (uic)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/
#include <BALL/MOLVIEW/GUI/DIALOGS/displayPropertiesData.h>

#include <qvariant.h>
#include <qcombobox.h>
#include <qgroupbox.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qlayout.h>
#include <qtooltip.h>
#include <qwhatsthis.h>

/* 
 *  Constructs a DisplayPropertiesData which is a child of 'parent', with the 
 *  name 'name' and widget flags set to 'f'.
 *
 *  The dialog will by default be modeless, unless you set 'modal' to
 *  TRUE to construct a modal dialog.
 */
DisplayPropertiesData::DisplayPropertiesData( QWidget* parent,  const char* name, bool modal, WFlags fl )
    : QDialog( parent, name, modal, fl )
{
    if ( !name )
	setName( "dlgDisplayProperties" );
    resize( 510, 220 ); 
    setMinimumSize( QSize( 510, 220 ) );
    setMaximumSize( QSize( 500, 200 ) );
    QPalette pal;
    QColorGroup cg;
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    setPalette( pal );
    setCaption( "Display Settings"  );

    GroupBox_9_3 = new QGroupBox( this, "GroupBox_9_3" );
    GroupBox_9_3->setGeometry( QRect( 260, 100, 250, 60 ) ); 
    GroupBox_9_3->setBackgroundMode( QGroupBox::PaletteBackground );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    GroupBox_9_3->setPalette( pal );
    GroupBox_9_3->setBackgroundOrigin( QGroupBox::ParentOrigin );
    GroupBox_9_3->setFocusPolicy( QGroupBox::NoFocus );
    GroupBox_9_3->setFrameShape( QGroupBox::Box );
    GroupBox_9_3->setFrameShadow( QGroupBox::Sunken );
    GroupBox_9_3->setLineWidth( 2 );
    GroupBox_9_3->setTitle(  "selection color"  );
    GroupBox_9_3->setAlignment( int( QGroupBox::AlignHCenter ) );

    color_sample_selection = new QLabel( GroupBox_9_3, "color_sample_selection" );
    color_sample_selection->setGeometry( QRect( 50, 20, 70, 30 ) ); 
    color_sample_selection->setBackgroundMode( QLabel::PaletteBackground );
    color_sample_selection->setPaletteForegroundColor( QColor( 255, 255, 0 ) );
    color_sample_selection->setPaletteBackgroundColor( QColor( 255, 255, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, QColor( 255, 255, 0) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setDisabled( cg );
    color_sample_selection->setPalette( pal );
    color_sample_selection->setFocusPolicy( QLabel::NoFocus );
    color_sample_selection->setFrameShadow( QLabel::Raised );
    color_sample_selection->setLineWidth( 0 );
    color_sample_selection->setMargin( 0 );
    color_sample_selection->setMidLineWidth( 0 );
    color_sample_selection->setTextFormat( QLabel::AutoText );
    color_sample_selection->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    edit_selection = new QPushButton( GroupBox_9_3, "edit_selection" );
    edit_selection->setGeometry( QRect( 140, 20, 80, 30 ) ); 
    edit_selection->setMinimumSize( QSize( 80, 30 ) );
    edit_selection->setMaximumSize( QSize( 80, 30 ) );
    edit_selection->setBackgroundMode( QPushButton::PaletteButton );
    edit_selection->setFocusPolicy( QPushButton::TabFocus );
    edit_selection->setText( "Edit"  );
    edit_selection->setAutoDefault( TRUE );

    model_groupbox = new QGroupBox( this, "model_groupbox" );
    model_groupbox->setGeometry( QRect( 0, 0, 250, 90 ) ); 
    model_groupbox->setBackgroundMode( QGroupBox::PaletteBackground );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    model_groupbox->setPalette( pal );
    model_groupbox->setBackgroundOrigin( QGroupBox::ParentOrigin );
    model_groupbox->setFocusPolicy( QGroupBox::NoFocus );
    model_groupbox->setLineWidth( 2 );
    model_groupbox->setTitle( "static model" );
    model_groupbox->setAlignment( int( QGroupBox::AlignHCenter ) );

    model_type_label = new QLabel( model_groupbox, "model_type_label" );
    model_type_label->setGeometry( QRect( 10, 20, 28, 18 ) ); 
    model_type_label->setBackgroundMode( QLabel::PaletteBackground );
    model_type_label->setFocusPolicy( QLabel::NoFocus );
    model_type_label->setLineWidth( 1 );
    model_type_label->setText( "type"  );
    model_type_label->setTextFormat( QLabel::AutoText );
    model_type_label->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    model_resolution_label = new QLabel( model_groupbox, "model_resolution_label" );
    model_resolution_label->setGeometry( QRect( 10, 50, 70, 22 ) ); 
    model_resolution_label->setBackgroundMode( QLabel::PaletteBackground );
    model_resolution_label->setFocusPolicy( QLabel::NoFocus );
    model_resolution_label->setLineWidth( 1 );
    model_resolution_label->setText( "resolution"  );
    model_resolution_label->setTextFormat( QLabel::AutoText );
    model_resolution_label->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    model_type_combobox_static = new QComboBox( FALSE, model_groupbox, "model_type_combobox_static" );
    model_type_combobox_static->insertItem(  "none"  );
    model_type_combobox_static->insertItem(  "line"  );
    model_type_combobox_static->insertItem(  "stick"  );
    model_type_combobox_static->insertItem(  "ball and stick" );
    model_type_combobox_static->insertItem(  "surface"  );
    model_type_combobox_static->insertItem(  "van der Waals"  );
    model_type_combobox_static->setGeometry( QRect( 90, 20, 140, 24 ) ); 
    model_type_combobox_static->setMinimumSize( QSize( 140, 24 ) );
    model_type_combobox_static->setMaximumSize( QSize( 140, 24 ) );
    model_type_combobox_static->setBackgroundMode( QComboBox::NoBackground );
    model_type_combobox_static->setFocusPolicy( QComboBox::StrongFocus );
    model_type_combobox_static->setSizeLimit( 10 );
    model_type_combobox_static->setMaxCount( 2147483647 );
    model_type_combobox_static->setInsertionPolicy( QComboBox::AtBottom );
    model_type_combobox_static->setDuplicatesEnabled( TRUE );

    mode_resolution_combobox_static = new QComboBox( FALSE, model_groupbox, "mode_resolution_combobox_static" );
    mode_resolution_combobox_static->insertItem(  "low"  );
    mode_resolution_combobox_static->insertItem(  "medium"  );
    mode_resolution_combobox_static->insertItem(  "high"  );
    mode_resolution_combobox_static->insertItem(  "ultra"  );
    mode_resolution_combobox_static->setGeometry( QRect( 90, 50, 140, 24 ) ); 
    mode_resolution_combobox_static->setMinimumSize( QSize( 140, 24 ) );
    mode_resolution_combobox_static->setMaximumSize( QSize( 140, 24 ) );
    mode_resolution_combobox_static->setBackgroundMode( QComboBox::NoBackground );
    mode_resolution_combobox_static->setFocusPolicy( QComboBox::StrongFocus );
    mode_resolution_combobox_static->setSizeLimit( 10 );
    mode_resolution_combobox_static->setMaxCount( 2147483647 );
    mode_resolution_combobox_static->setInsertionPolicy( QComboBox::AtBottom );
    mode_resolution_combobox_static->setDuplicatesEnabled( TRUE );

    model_groupbox_2 = new QGroupBox( this, "model_groupbox_2" );
    model_groupbox_2->setGeometry( QRect( 260, 0, 250, 90 ) ); 
    model_groupbox_2->setBackgroundMode( QGroupBox::PaletteBackground );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    model_groupbox_2->setPalette( pal );
    model_groupbox_2->setBackgroundOrigin( QGroupBox::ParentOrigin );
    model_groupbox_2->setFocusPolicy( QGroupBox::NoFocus );
    model_groupbox_2->setLineWidth( 2 );
    model_groupbox_2->setTitle(  "dynamic model"  );
    model_groupbox_2->setAlignment( int( QGroupBox::AlignHCenter ) );

    model_resolution_label_2 = new QLabel( model_groupbox_2, "model_resolution_label_2" );
    model_resolution_label_2->setGeometry( QRect( 10, 50, 70, 22 ) ); 
    model_resolution_label_2->setBackgroundMode( QLabel::PaletteBackground );
    model_resolution_label_2->setFocusPolicy( QLabel::NoFocus );
    model_resolution_label_2->setLineWidth( 1 );
    model_resolution_label_2->setText( "resolution"  );
    model_resolution_label_2->setTextFormat( QLabel::AutoText );
    model_resolution_label_2->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    model_type_label_2 = new QLabel( model_groupbox_2, "model_type_label_2" );
    model_type_label_2->setGeometry( QRect( 10, 20, 28, 18 ) ); 
    model_type_label_2->setBackgroundMode( QLabel::PaletteBackground );
    model_type_label_2->setFocusPolicy( QLabel::NoFocus );
    model_type_label_2->setLineWidth( 1 );
    model_type_label_2->setText(  "type"  );
    model_type_label_2->setTextFormat( QLabel::AutoText );
    model_type_label_2->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    mode_resolution_combobox_dynamic = new QComboBox( FALSE, model_groupbox_2, "mode_resolution_combobox_dynamic" );
    mode_resolution_combobox_dynamic->insertItem(  "low"  );
    mode_resolution_combobox_dynamic->insertItem(  "medium"  );
    mode_resolution_combobox_dynamic->insertItem(  "high"  );
    mode_resolution_combobox_dynamic->insertItem(  "ultra"  );
    mode_resolution_combobox_dynamic->setGeometry( QRect( 90, 50, 140, 24 ) ); 
    mode_resolution_combobox_dynamic->setMinimumSize( QSize( 140, 24 ) );
    mode_resolution_combobox_dynamic->setMaximumSize( QSize( 140, 24 ) );
    mode_resolution_combobox_dynamic->setBackgroundMode( QComboBox::NoBackground );
    mode_resolution_combobox_dynamic->setFocusPolicy( QComboBox::StrongFocus );
    mode_resolution_combobox_dynamic->setSizeLimit( 10 );
    mode_resolution_combobox_dynamic->setMaxCount( 2147483647 );
    mode_resolution_combobox_dynamic->setInsertionPolicy( QComboBox::AtBottom );
    mode_resolution_combobox_dynamic->setDuplicatesEnabled( TRUE );

    model_type_combobox_dynamic = new QComboBox( FALSE, model_groupbox_2, "model_type_combobox_dynamic" );
    model_type_combobox_dynamic->insertItem(  "none"  );
    model_type_combobox_dynamic->insertItem(  "line"  );
    model_type_combobox_dynamic->insertItem(  "stick"  );
    model_type_combobox_dynamic->insertItem(  "ball and stick" );
    model_type_combobox_dynamic->insertItem(  "surface"  );
    model_type_combobox_dynamic->insertItem(  "van der Waals"  );
    model_type_combobox_dynamic->setGeometry(QRect( 90, 20, 140, 24 ) ); 
    model_type_combobox_dynamic->setMinimumSize( QSize( 140, 24 ) );
    model_type_combobox_dynamic->setMaximumSize( QSize( 140, 24 ) );
    model_type_combobox_dynamic->setBackgroundMode( QComboBox::NoBackground );
    model_type_combobox_dynamic->setFocusPolicy( QComboBox::StrongFocus );
    model_type_combobox_dynamic->setSizeLimit( 10 );
    model_type_combobox_dynamic->setMaxCount( 2147483647 );
    model_type_combobox_dynamic->setInsertionPolicy( QComboBox::AtBottom );
    model_type_combobox_dynamic->setDuplicatesEnabled( TRUE );

    close_button = new QPushButton( this, "close_button" );
    close_button->setGeometry( QRect( 400, 180, 107, 30 ) ); 
    close_button->setBackgroundMode( QPushButton::PaletteButton );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    close_button->setPalette( pal );
    close_button->setFocusPolicy( QPushButton::TabFocus );
    close_button->setText(  "&Close"  );
    close_button->setAutoDefault( TRUE );

    apply_button = new QPushButton( this, "apply_button" );
    apply_button->setEnabled( FALSE );
    apply_button->setGeometry( QRect( 280, 180, 110, 30 ) ); 
    apply_button->setBackgroundMode( QPushButton::PaletteButton );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    apply_button->setPalette( pal );
    apply_button->setFocusPolicy( QPushButton::TabFocus );
    apply_button->setText(  "&Apply"  );
    apply_button->setAutoDefault( TRUE );

    color_groupbox = new QGroupBox( this, "color_groupbox" );
    color_groupbox->setEnabled( TRUE );
    color_groupbox->setGeometry( QRect( 0, 100, 250, 120 ) ); 
    color_groupbox->setBackgroundMode( QGroupBox::PaletteBackground );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 10, 95, 137) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 228, 228, 228) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 250, 254, 255) );
    cg.setColor( QColorGroup::Dark, QColor( 81, 84, 85) );
    cg.setColor( QColorGroup::Mid, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::Text, QColor( 189, 196, 198) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, QColor( 228, 236, 238) );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    color_groupbox->setPalette( pal );
    color_groupbox->setBackgroundOrigin( QGroupBox::ParentOrigin );
    color_groupbox->setFocusPolicy( QGroupBox::NoFocus );
    color_groupbox->setLineWidth( 2 );
    color_groupbox->setTitle(  "model color"  );
    color_groupbox->setAlignment( int( QGroupBox::AlignHCenter ) );

    static_custom = new QGroupBox( color_groupbox, "static_custom" );
    static_custom->setEnabled( TRUE );
    static_custom->setGeometry( QRect( 20, 50, 210, 60 ) ); 
    static_custom->setBackgroundMode( QGroupBox::PaletteBackground );
    static_custom->setFocusPolicy( QGroupBox::NoFocus );
    static_custom->setFrameShape( QGroupBox::Box );
    static_custom->setFrameShadow( QGroupBox::Sunken );
    static_custom->setLineWidth( 1 );
    static_custom->setTitle( "custom color"  );
    static_custom->setAlignment( int( QGroupBox::AlignHCenter ) );

    edit_button = new QPushButton( static_custom, "edit_button" );
    edit_button->setGeometry( QRect( 110, 20, 80, 30 ) ); 
    edit_button->setMinimumSize( QSize( 80, 30 ) );
    edit_button->setMaximumSize( QSize( 80, 30 ) );
    edit_button->setBackgroundMode( QPushButton::PaletteButton );
    edit_button->setFocusPolicy( QPushButton::TabFocus );
    edit_button->setText(  "Edit"  );
    edit_button->setAutoDefault( TRUE );

    color_sample = new QLabel( static_custom, "color_sample" );
    color_sample->setGeometry( QRect( 20, 20, 70, 30 ) ); 
    color_sample->setBackgroundMode( QLabel::PaletteBackground );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, black );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, black );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, black );
    pal.setDisabled( cg );
    color_sample->setPalette( pal );
    color_sample->setFocusPolicy( QLabel::NoFocus );
    color_sample->setLineWidth( 1 );
    color_sample->setTextFormat( QLabel::AutoText );
    color_sample->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    coloring_type_combobox = new QComboBox( FALSE, color_groupbox, "coloring_type_combobox" );
    coloring_type_combobox->insertItem(  "by element"  );
    coloring_type_combobox->insertItem(  "by residue type"  );
    coloring_type_combobox->insertItem(  "by residue name"  );
    coloring_type_combobox->insertItem(  "by atom charge"  );
    coloring_type_combobox->insertItem(  "by atom distance"  );
    coloring_type_combobox->insertItem(  "custom"  );
    coloring_type_combobox->setGeometry( QRect( 20, 20, 210, 24 ) ); 
    coloring_type_combobox->setMinimumSize( QSize( 210, 24 ) );
    coloring_type_combobox->setMaximumSize( QSize( 210, 24 ) );
    coloring_type_combobox->setBackgroundMode( QComboBox::NoBackground );
    coloring_type_combobox->setFocusPolicy( QComboBox::StrongFocus );
    coloring_type_combobox->setSizeLimit( 10 );
    coloring_type_combobox->setMaxCount( 2147483647 );
    coloring_type_combobox->setInsertionPolicy( QComboBox::AtBottom );
    coloring_type_combobox->setDuplicatesEnabled( TRUE );

    // signals and slots connections
    connect( apply_button, SIGNAL( clicked() ), this, SLOT( applyButtonClicked() ) );
    connect( close_button, SIGNAL( clicked() ), this, SLOT( accept() ) );
    connect( mode_resolution_combobox_static, SIGNAL( activated(const QString&) ), this, SLOT( selectPrecisionStatic(const QString&) ) );
    connect( edit_selection, SIGNAL( clicked() ), this, SLOT( editSelectionColor() ) );
    connect( coloring_type_combobox, SIGNAL( activated(const QString&) ), this, SLOT( selectColoringMethod(const QString&) ) );
    connect( model_type_combobox_dynamic, SIGNAL( activated(const QString&) ), this, SLOT( selectModelDynamic(const QString&) ) );
    connect( model_type_combobox_static, SIGNAL( activated(const QString&) ), this, SLOT( selectModelStatic(const QString&) ) );
    connect( mode_resolution_combobox_dynamic, SIGNAL( activated(const QString&) ), this, SLOT( selectPrecisionDynamic(const QString&) ) );
    connect( edit_button, SIGNAL( clicked() ), this, SLOT( editColor() ) );

    // tab order
    setTabOrder( apply_button, close_button );
    setTabOrder( close_button, coloring_type_combobox );
    setTabOrder( coloring_type_combobox, model_type_combobox_static );
    setTabOrder( model_type_combobox_static, mode_resolution_combobox_static );
    setTabOrder( mode_resolution_combobox_static, edit_button );
}

/*  
 *  Destroys the object and frees any allocated resources
 */
DisplayPropertiesData::~DisplayPropertiesData()
{
    // no need to delete child widgets, Qt does it all for us
}

