// $Id: DlgMoveOverlayData.C,v 1.3 2001/01/24 13:04:11 amoll Exp $
/**********************************************************************

	--- Qt Architect generated file ---

	File: DlgMoveOverlayData.cpp
	Last generated: Mon Dec 4 00:54:10 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include <BALL/MOLVIEW/GUI/DIALOGS/DlgMoveOverlayData.h>

#include <qlabel.h>
#include <qpushbutton.h>

DlgMoveOverlayData::DlgMoveOverlayData(QWidget *parent, const char *name)
                   : QDialog(parent, name, FALSE, 0)
{
    QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
    qtarch_PushButton_1->setGeometry(80, 60, 40, 20);
    qtarch_PushButton_1->setMinimumSize(0, 0);
    qtarch_PushButton_1->setMaximumSize(32767, 32767);
    qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_1->setText( "Up" );
    qtarch_PushButton_1->setAutoRepeat( FALSE );
    qtarch_PushButton_1->setToggleButton( FALSE );
    qtarch_PushButton_1->setDefault( FALSE );
    qtarch_PushButton_1->setAutoDefault( FALSE );
    connect(qtarch_PushButton_1, SIGNAL(pressed()), SLOT(slotUp()));

    QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
    qtarch_PushButton_2->setGeometry(40, 80, 40, 20);
    qtarch_PushButton_2->setMinimumSize(0, 0);
    qtarch_PushButton_2->setMaximumSize(32767, 32767);
    qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_2->setText( "Left" );
    qtarch_PushButton_2->setAutoRepeat( FALSE );
    qtarch_PushButton_2->setToggleButton( FALSE );
    qtarch_PushButton_2->setDefault( FALSE );
    qtarch_PushButton_2->setAutoDefault( FALSE );
    connect(qtarch_PushButton_2, SIGNAL(pressed()), SLOT(slotLeft()));

    QPushButton *qtarch_PushButton_3 = new QPushButton(this, "PushButton_3");
    qtarch_PushButton_3->setGeometry(120, 80, 40, 20);
    qtarch_PushButton_3->setMinimumSize(0, 0);
    qtarch_PushButton_3->setMaximumSize(32767, 32767);
    qtarch_PushButton_3->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_3->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_3->setText( "Right" );
    qtarch_PushButton_3->setAutoRepeat( FALSE );
    qtarch_PushButton_3->setToggleButton( FALSE );
    qtarch_PushButton_3->setDefault( FALSE );
    qtarch_PushButton_3->setAutoDefault( FALSE );
    connect(qtarch_PushButton_3, SIGNAL(pressed()), SLOT(slotRight()));

    QPushButton *qtarch_PushButton_4 = new QPushButton(this, "PushButton_4");
    qtarch_PushButton_4->setGeometry(80, 100, 40, 20);
    qtarch_PushButton_4->setMinimumSize(0, 0);
    qtarch_PushButton_4->setMaximumSize(32767, 32767);
    qtarch_PushButton_4->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_4->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_4->setText( "Down" );
    qtarch_PushButton_4->setAutoRepeat( FALSE );
    qtarch_PushButton_4->setToggleButton( FALSE );
    qtarch_PushButton_4->setDefault( FALSE );
    qtarch_PushButton_4->setAutoDefault( FALSE );
    connect(qtarch_PushButton_4, SIGNAL(pressed()), SLOT(slotDown()));

    QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
    qtarch_Label_1->setGeometry(60, 10, 100, 30);
    qtarch_Label_1->setMinimumSize(0, 0);
    qtarch_Label_1->setMaximumSize(32767, 32767);
    qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
    qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
    qtarch_Label_1->setFrameStyle( 0 );
    qtarch_Label_1->setLineWidth( 1 );
    qtarch_Label_1->setMidLineWidth( 0 );
    qtarch_Label_1->setMargin( 0 );
    qtarch_Label_1->setTextFormat( Qt::AutoText );
    qtarch_Label_1->setText( "Move overlay" );
    qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
    qtarch_Label_1->setIndent( -1 );

    QPushButton *qtarch_PushButton_5 = new QPushButton(this, "PushButton_5");
    qtarch_PushButton_5->setGeometry(150, 120, 30, 20);
    qtarch_PushButton_5->setMinimumSize(0, 0);
    qtarch_PushButton_5->setMaximumSize(32767, 32767);
    qtarch_PushButton_5->setFocusPolicy(QWidget::TabFocus);
    qtarch_PushButton_5->setBackgroundMode(QWidget::PaletteButton);
    qtarch_PushButton_5->setText( "OK" );
    qtarch_PushButton_5->setAutoRepeat( FALSE );
    qtarch_PushButton_5->setToggleButton( FALSE );
    qtarch_PushButton_5->setDefault( FALSE );
    qtarch_PushButton_5->setAutoDefault( FALSE );
    connect(qtarch_PushButton_5, SIGNAL(pressed()), SLOT(slotOK()));

    resize(200,160);
    setMinimumSize(0, 0);
    setMaximumSize(32767, 32767);
}

DlgMoveOverlayData::~DlgMoveOverlayData()
{
}
