# Python wrapper code.
#
# Generated by SIP v0.12 on Tue Jun 27 14:52:46 2000

import libBALLc

libBALLc.sipInitModule()

class String:
	def __init__(self,*args):
		libBALLc.sipCallCtor(49,self,args)

class Angle:
	def __init__(self,*args):
		libBALLc.sipCallCtor(48,self,args)

class Box3:
	def __init__(self,*args):
		libBALLc.sipCallCtor(47,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(47,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(47,self,name,value)

class PropertyManager:
	def __init__(self,*args):
		libBALLc.sipCallCtor(44,self,args)

class Element(PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(43,self,args)

class PTE_(PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(42,self,args)

class Selectable:
	def __init__(self,*args):
		libBALLc.sipCallCtor(41,self,args)

class PersistentObject:
	def __init__(self,*args):
		libBALLc.sipCallCtor(39,self,args)

class Object:
	def __init__(self,*args):
		libBALLc.sipCallCtor(38,self,args)

class Composite(PersistentObject,Object,Selectable):
	def __init__(self,*args):
		libBALLc.sipCallCtor(37,self,args)

class Vector3(PersistentObject):
	def __init__(self,*args):
		libBALLc.sipCallCtor(36,self,args)

class Bond(Composite,PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(35,self,args)

class Atom(Composite,PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(34,self,args)

class Options:
	def __init__(self,*args):
		libBALLc.sipCallCtor(31,self,args)

class File:
	def __init__(self,*args):
		libBALLc.sipCallCtor(24,self,args)

class PDBAtom(Atom):
	def __init__(self,*args):
		libBALLc.sipCallCtor(23,self,args)

class PDBFile:
	def __init__(self,*args):
		libBALLc.sipCallCtor(22,self,args)

class HINFile(File):
	def __init__(self,*args):
		libBALLc.sipCallCtor(21,self,args)

class MOL2File(File):
	def __init__(self,*args):
		libBALLc.sipCallCtor(20,self,args)

class XYZFile(File):
	def __init__(self,*args):
		libBALLc.sipCallCtor(19,self,args)

class ForceField:
	def __init__(self,*args):
		libBALLc.sipCallCtor(17,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(17,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(17,self,name,value)

class ForceFieldComponent:
	def __init__(self,*args):
		libBALLc.sipCallCtor(16,self,args)

class AtomVector:
	def __init__(self,*args):
		libBALLc.sipCallCtor(15,self,args)

class Gradient:
	def __init__(self,*args):
		libBALLc.sipCallCtor(14,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(14,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(14,self,name,value)

class SnapShotManager:
	def __init__(self,*args):
		libBALLc.sipCallCtor(13,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(13,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(13,self,name,value)

class EnergyMinimizer:
	def __init__(self,*args):
		libBALLc.sipCallCtor(12,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(12,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(12,self,name,value)

class ConjugateGradientMinimizer(EnergyMinimizer):
	class UpdateMethod:
		POLAK_RIBIERE = 0
		FLETCHER_REEVES = 1
		SHANNO = 2

	def __init__(self,*args):
		libBALLc.sipCallCtor(11,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(11,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(11,self,name,value)

class PeriodicBoundary:
	def __init__(self,*args):
		libBALLc.sipCallCtor(10,self,args)
	def __getattr__(self,name):
		return libBALLc.sipCallGetVar(10,self,name)
	def __setattr__(self,name,value):
		return libBALLc.sipCallSetVar(10,self,name,value)

class BaseFragment(Composite,PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(45,self,args)

class NamedProperty(PersistentObject):
	def __init__(self,*args):
		libBALLc.sipCallCtor(40,self,args)

class Fragment(BaseFragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(33,self,args)

class Molecule(BaseFragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(32,self,args)

class Protein(Molecule):
	def __init__(self,*args):
		libBALLc.sipCallCtor(30,self,args)

class Chain(BaseFragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(29,self,args)

class SecondaryStructure(BaseFragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(28,self,args)

class Residue(Fragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(27,self,args)

class Nucleotide(Fragment):
	def __init__(self,*args):
		libBALLc.sipCallCtor(26,self,args)

class NucleicAcid(Molecule):
	def __init__(self,*args):
		libBALLc.sipCallCtor(25,self,args)

class AmberFF(ForceField):
	def __init__(self,*args):
		libBALLc.sipCallCtor(18,self,args)

class System(BaseFragment,PropertyManager):
	def __init__(self,*args):
		libBALLc.sipCallCtor(46,self,args)

# Register the classes with the C++ module.

libBALLc.sipRegisterClasses()
