// C++ wrapper code.
//
// Generated by SIP v0.12 on Wed Jun 21 17:17:45 2000

#include "sipBALLDeclBALL.h"

#include "sipBALLString.h"
#include "sipBALLAngle.h"
#include "sipBALLBox3.h"
#include "sipBALLSystem.h"
#include "sipBALLElement.h"
#include "sipBALLPTE_.h"
#include "sipBALLSelectable.h"
#include "sipBALLNamedProperty.h"
#include "sipBALLPropertyManager.h"
#include "sipBALLObject.h"
#include "sipBALLPersistentObject.h"
#include "sipBALLComposite.h"
#include "sipBALLVector3.h"
#include "sipBALLBond.h"
#include "sipBALLAtom.h"
#include "sipBALLBaseFragment.h"
#include "sipBALLFragment.h"
#include "sipBALLMolecule.h"
#include "sipBALLOptions.h"
#include "sipBALLProtein.h"
#include "sipBALLChain.h"
#include "sipBALLSecondaryStructure.h"
#include "sipBALLResidue.h"
#include "sipBALLFile.h"
#include "sipBALLPDBAtom.h"
#include "sipBALLPDBFile.h"
#include "sipBALLHINFile.h"
#include "sipBALLMOL2File.h"
#include "sipBALLXYZFile.h"
#include "sipBALLAmberFF.h"
#include "sipBALLForceField.h"
#include "sipBALLForceFieldComponent.h"
#include "sipBALLAtomVector.h"
#include "sipBALLGradient.h"
#include "sipBALLSnapShotManager.h"
#include "sipBALLEnergyMinimizer.h"
#include "sipBALLConjugateGradientMinimizer.h"
#include "sipBALLPeriodicBoundary.h"

char sipName_BALL_updateMolecules[] = "updateMolecules";
char sipName_BALL_isEnabled[] = "isEnabled";
char sipName_BALL_removeSolvent[] = "removeSolvent";
char sipName_BALL_addSolvent[] = "addSolvent";
char sipName_BALL_setBox[] = "setBox";
char sipName_BALL_getBox[] = "getBox";
char sipName_BALL_disable[] = "disable";
char sipName_BALL_enable[] = "enable";
char sipName_BALL_generateMoleculesVector[] = "generateMoleculesVector";
char sipName_BALL_PeriodicBoundary[] = "PeriodicBoundary";
char sipName_BALL_getStepLength[] = "getStepLength";
char sipName_BALL_setStepLength[] = "setStepLength";
char sipName_BALL_ConjugateGradientMinimizer[] = "ConjugateGradientMinimizer";
char sipName_BALL_minimize[] = "minimize";
char sipName_BALL_getSnapShotFrequency[] = "getSnapShotFrequency";
char sipName_BALL_setSnapShotFrequency[] = "setSnapShotFrequency";
char sipName_BALL_getMaximalShift[] = "getMaximalShift";
char sipName_BALL_setMaximalShift[] = "setMaximalShift";
char sipName_BALL_getMaxGradient[] = "getMaxGradient";
char sipName_BALL_setMaxGradient[] = "setMaxGradient";
char sipName_BALL_getEnergyDifferenceBound[] = "getEnergyDifferenceBound";
char sipName_BALL_setEnergyDifferenceBound[] = "setEnergyDifferenceBound";
char sipName_BALL_getEnergyOutputFrequency[] = "getEnergyOutputFrequency";
char sipName_BALL_setEnergyOutputFrequency[] = "setEnergyOutputFrequency";
char sipName_BALL_getMaxSameEnergy[] = "getMaxSameEnergy";
char sipName_BALL_setMaxSameEnergy[] = "setMaxSameEnergy";
char sipName_BALL_setMaximalNumberOfIterations[] = "setMaximalNumberOfIterations";
char sipName_BALL_getMaximalNumberOfIterations[] = "getMaximalNumberOfIterations";
char sipName_BALL_setNumberOfIteration[] = "setNumberOfIteration";
char sipName_BALL_getInitialEnergy[] = "getInitialEnergy";
char sipName_BALL_getInitialGradient[] = "getInitialGradient";
char sipName_BALL_getGradient[] = "getGradient";
char sipName_BALL_getDirection[] = "getDirection";
char sipName_BALL_getNumberOfIteration[] = "getNumberOfIteration";
char sipName_BALL_finishIteration[] = "finishIteration";
char sipName_BALL_printEnergy[] = "printEnergy";
char sipName_BALL_updateDirection[] = "updateDirection";
char sipName_BALL_findStep[] = "findStep";
char sipName_BALL_isConverged[] = "isConverged";
char sipName_BALL_EnergyMinimizer[] = "EnergyMinimizer";
char sipName_BALL_getSnapShotAsSystem[] = "getSnapShotAsSystem";
char sipName_BALL_getNumberOfSnapShots[] = "getNumberOfSnapShots";
char sipName_BALL_flushToDisk[] = "flushToDisk";
char sipName_BALL_takeSnapShot[] = "takeSnapShot";
char sipName_BALL_getFlushToDiskFrequency[] = "getFlushToDiskFrequency";
char sipName_BALL_setFlushToDiskFrequency[] = "setFlushToDiskFrequency";
char sipName_BALL_SnapShotManager[] = "SnapShotManager";
char sipName_BALL_rms[] = "rms";
char sipName_BALL_inv_norm[] = "inv_norm";
char sipName_BALL_norm[] = "norm";
char sipName_BALL_invalidate[] = "invalidate";
char sipName_BALL_Gradient[] = "Gradient";
char sipName_BALL_resize[] = "resize";
char sipName_BALL_push_back[] = "push_back";
char sipName_BALL_resetPositions[] = "resetPositions";
char sipName_BALL_savePositions[] = "savePositions";
char sipName_BALL_AtomVector[] = "AtomVector";
char sipName_BALL_setForceField[] = "setForceField";
char sipName_BALL_getForceField[] = "getForceField";
char sipName_BALL_ForceFieldComponent[] = "ForceFieldComponent";
char sipName_BALL_periodic_boundary[] = "periodic_boundary";
char sipName_BALL_options[] = "options";
char sipName_BALL_update[] = "update";
char sipName_BALL_getUpdateFrequency[] = "getUpdateFrequency";
char sipName_BALL_getRMSGradient[] = "getRMSGradient";
char sipName_BALL_updateForces[] = "updateForces";
char sipName_BALL_updateEnergy[] = "updateEnergy";
char sipName_BALL_getEnergy[] = "getEnergy";
char sipName_BALL_getComponent[] = "getComponent";
char sipName_BALL_removeComponent[] = "removeComponent";
char sipName_BALL_insertComponent[] = "insertComponent";
char sipName_BALL_countComponents[] = "countComponents";
char sipName_BALL_setUseSelection[] = "setUseSelection";
char sipName_BALL_getUseSelection[] = "getUseSelection";
char sipName_BALL_getAtoms[] = "getAtoms";
char sipName_BALL_getNumberOfMovableAtoms[] = "getNumberOfMovableAtoms";
char sipName_BALL_getNumberOfAtoms[] = "getNumberOfAtoms";
char sipName_BALL_setup[] = "setup";
char sipName_BALL_hasInitializedParameters[] = "hasInitializedParameters";
char sipName_BALL_getVdWEnergy[] = "getVdWEnergy";
char sipName_BALL_getESEnergy[] = "getESEnergy";
char sipName_BALL_getNonbondedEnergy[] = "getNonbondedEnergy";
char sipName_BALL_getTorsionEnergy[] = "getTorsionEnergy";
char sipName_BALL_getBendEnergy[] = "getBendEnergy";
char sipName_BALL_getStretchEnergy[] = "getStretchEnergy";
char sipName_BALL_specificSetup[] = "specificSetup";
char sipName_BALL_ForceField[] = "ForceField";
char sipName_BALL_AmberFF[] = "AmberFF";
char sipName_BALL_XYZFile[] = "XYZFile";
char sipName_BALL_MOL2File[] = "MOL2File";
char sipName_BALL_getTemperature[] = "getTemperature";
char sipName_BALL_getPeriodicBoundary[] = "getPeriodicBoundary";
char sipName_BALL_hasPeriodicBoundary[] = "hasPeriodicBoundary";
char sipName_BALL_HINFile[] = "HINFile";
char sipName_BALL_write[] = "write";
char sipName_BALL_read[] = "read";
char sipName_BALL_PDBFile[] = "PDBFile";
char sipName_BALL_getTemperatureFactor[] = "getTemperatureFactor";
char sipName_BALL_setTemperatureFactor[] = "setTemperatureFactor";
char sipName_BALL_getOccupancy[] = "getOccupancy";
char sipName_BALL_setOccupancy[] = "setOccupancy";
char sipName_BALL_getAlternateLocationIndicator[] = "getAlternateLocationIndicator";
char sipName_BALL_setAlternateLocationIndicator[] = "setAlternateLocationIndicator";
char sipName_BALL_getRemotenessIndicator[] = "getRemotenessIndicator";
char sipName_BALL_setRemotenessIndicator[] = "setRemotenessIndicator";
char sipName_BALL_getBranchDesignator[] = "getBranchDesignator";
char sipName_BALL_setBranchDesignator[] = "setBranchDesignator";
char sipName_BALL_PDBAtom[] = "PDBAtom";
char sipName_BALL_hasFormat[] = "hasFormat";
char sipName_BALL_isExecutable[] = "isExecutable";
char sipName_BALL_isWritable[] = "isWritable";
char sipName_BALL_isReadable[] = "isReadable";
char sipName_BALL_isCanonized[] = "isCanonized";
char sipName_BALL_isAccessible[] = "isAccessible";
char sipName_BALL_isClosed[] = "isClosed";
char sipName_BALL_isOpen[] = "isOpen";
char sipName_BALL_truncate[] = "truncate";
char sipName_BALL_renameTo[] = "renameTo";
char sipName_BALL_moveTo[] = "moveTo";
char sipName_BALL_copyTo[] = "copyTo";
char sipName_BALL_getOpenMode[] = "getOpenMode";
char sipName_BALL_getSize[] = "getSize";
char sipName_BALL_getOriginalName[] = "getOriginalName";
char sipName_BALL_close[] = "close";
char sipName_BALL_reopen[] = "reopen";
char sipName_BALL_open[] = "open";
char sipName_BALL_File[] = "File";
char sipName_BALL_isCTerminal[] = "isCTerminal";
char sipName_BALL_isNTerminal[] = "isNTerminal";
char sipName_BALL_isTerminal[] = "isTerminal";
char sipName_BALL_isAminoAcid[] = "isAminoAcid";
char sipName_BALL_getInsertionCode[] = "getInsertionCode";
char sipName_BALL_setInsertionCode[] = "setInsertionCode";
char sipName_BALL_Residue[] = "Residue";
char sipName_BALL_SecondaryStructure[] = "SecondaryStructure";
char sipName_BALL_getProtein[] = "getProtein";
char sipName_BALL_Chain[] = "Chain";
char sipName_BALL_countPDBAtoms[] = "countPDBAtoms";
char sipName_BALL_countResidues[] = "countResidues";
char sipName_BALL_countSecondaryStructures[] = "countSecondaryStructures";
char sipName_BALL_countChains[] = "countChains";
char sipName_BALL_getID[] = "getID";
char sipName_BALL_setID[] = "setID";
char sipName_BALL_getPDBAtom[] = "getPDBAtom";
char sipName_BALL_getCTerminal[] = "getCTerminal";
char sipName_BALL_getNTerminal[] = "getNTerminal";
char sipName_BALL_getResidue[] = "getResidue";
char sipName_BALL_getSecondaryStructure[] = "getSecondaryStructure";
char sipName_BALL_getChain[] = "getChain";
char sipName_BALL_[] = "";
char sipName_BALL_Protein[] = "Protein";
char sipName_BALL_readOptionFile[] = "readOptionFile";
char sipName_BALL_setDefaultBool[] = "setDefaultBool";
char sipName_BALL_setDefaultReal[] = "setDefaultReal";
char sipName_BALL_setDefaultInteger[] = "setDefaultInteger";
char sipName_BALL_setDefault[] = "setDefault";
char sipName_BALL_setBool[] = "setBool";
char sipName_BALL_setInteger[] = "setInteger";
char sipName_BALL_setVector[] = "setVector";
char sipName_BALL_setReal[] = "setReal";
char sipName_BALL_getInteger[] = "getInteger";
char sipName_BALL_getVector[] = "getVector";
char sipName_BALL_getReal[] = "getReal";
char sipName_BALL_isSet[] = "isSet";
char sipName_BALL_isVector[] = "isVector";
char sipName_BALL_isReal[] = "isReal";
char sipName_BALL_isBool[] = "isBool";
char sipName_BALL_isInteger[] = "isInteger";
char sipName_BALL_Options[] = "Options";
char sipName_BALL_getSystem[] = "getSystem";
char sipName_BALL_Molecule[] = "Molecule";
char sipName_BALL_Fragment[] = "Fragment";
char sipName_BALL_isSuperBaseFragmentOf[] = "isSuperBaseFragmentOf";
char sipName_BALL_isSubBaseFragmentOf[] = "isSubBaseFragmentOf";
char sipName_BALL_countIntraBonds[] = "countIntraBonds";
char sipName_BALL_countInterBonds[] = "countInterBonds";
char sipName_BALL_countBaseFragments[] = "countBaseFragments";
char sipName_BALL_getAtom[] = "getAtom";
char sipName_BALL_getBaseFragment[] = "getBaseFragment";
char sipName_BALL_getSuperBaseFragment[] = "getSuperBaseFragment";
char sipName_BALL_BaseFragment[] = "BaseFragment";
char sipName_BALL_isVicinal[] = "isVicinal";
char sipName_BALL_isGeminal[] = "isGeminal";
char sipName_BALL_isBondedTo[] = "isBondedTo";
char sipName_BALL_hasBond[] = "hasBond";
char sipName_BALL_destroyBond[] = "destroyBond";
char sipName_BALL_cloneBond[] = "cloneBond";
char sipName_BALL_countBonds[] = "countBonds";
char sipName_BALL_getForce[] = "getForce";
char sipName_BALL_setForce[] = "setForce";
char sipName_BALL_getVelocity[] = "getVelocity";
char sipName_BALL_setVelocity[] = "setVelocity";
char sipName_BALL_setTypeName[] = "setTypeName";
char sipName_BALL_getTypeName[] = "getTypeName";
char sipName_BALL_getRadius[] = "getRadius";
char sipName_BALL_setRadius[] = "setRadius";
char sipName_BALL_getPosition[] = "getPosition";
char sipName_BALL_setPosition[] = "setPosition";
char sipName_BALL_getFragment[] = "getFragment";
char sipName_BALL_getMolecule[] = "getMolecule";
char sipName_BALL_getCharge[] = "getCharge";
char sipName_BALL_setCharge[] = "setCharge";
char sipName_BALL_setElement[] = "setElement";
char sipName_BALL_Atom[] = "Atom";
char sipName_BALL_isIntraBondOf[] = "isIntraBondOf";
char sipName_BALL_isIntraBond[] = "isIntraBond";
char sipName_BALL_isInterBondOf[] = "isInterBondOf";
char sipName_BALL_isInterBond[] = "isInterBond";
char sipName_BALL_isBonded[] = "isBonded";
char sipName_BALL_isBondOf[] = "isBondOf";
char sipName_BALL_getBondedAtomOf[] = "getBondedAtomOf";
char sipName_BALL_getBond[] = "getBond";
char sipName_BALL_setType[] = "setType";
char sipName_BALL_getOrder[] = "getOrder";
char sipName_BALL_setOrder[] = "setOrder";
char sipName_BALL_getSecondAtom[] = "getSecondAtom";
char sipName_BALL_setSecondAtom[] = "setSecondAtom";
char sipName_BALL_getPartner[] = "getPartner";
char sipName_BALL_getFirstAtom[] = "getFirstAtom";
char sipName_BALL_setFirstAtom[] = "setFirstAtom";
char sipName_BALL_createBond[] = "createBond";
char sipName_BALL_Bond[] = "Bond";
char sipName_BALL_isOrthogonalTo[] = "isOrthogonalTo";
char sipName_BALL_isZero[] = "isZero";
char sipName_BALL_getPerpendicularNormalization[] = "getPerpendicularNormalization";
char sipName_BALL_getOrthogonalProjection[] = "getOrthogonalProjection";
char sipName_BALL_getAngle[] = "getAngle";
char sipName_BALL_getSquareDistance[] = "getSquareDistance";
char sipName_BALL_getDistance[] = "getDistance";
char sipName_BALL_getUnit[] = "getUnit";
char sipName_BALL_getZero[] = "getZero";
char sipName_BALL_normalize[] = "normalize";
char sipName_BALL_getSquareLength[] = "getSquareLength";
char sipName_BALL_getLength[] = "getLength";
char sipName_BALL_Vector3[] = "Vector3";
char sipName_BALL_containsSelection[] = "containsSelection";
char sipName_BALL_isHomomorph[] = "isHomomorph";
char sipName_BALL_isRelatedWith[] = "isRelatedWith";
char sipName_BALL_isAncestorOf[] = "isAncestorOf";
char sipName_BALL_isAncestor[] = "isAncestor";
char sipName_BALL_hasAnyAncestor[] = "hasAnyAncestor";
char sipName_BALL_isDescendantOf[] = "isDescendantOf";
char sipName_BALL_isDescendant[] = "isDescendant";
char sipName_BALL_hasDescendant[] = "hasDescendant";
char sipName_BALL_isNextSiblingOf[] = "isNextSiblingOf";
char sipName_BALL_hasNextSibling[] = "hasNextSibling";
char sipName_BALL_isPreviousSiblingOf[] = "isPreviousSiblingOf";
char sipName_BALL_hasPreviousSibling[] = "hasPreviousSibling";
char sipName_BALL_isSiblingOf[] = "isSiblingOf";
char sipName_BALL_hasSibling[] = "hasSibling";
char sipName_BALL_isParentOf[] = "isParentOf";
char sipName_BALL_isParent[] = "isParent";
char sipName_BALL_hasParent[] = "hasParent";
char sipName_BALL_isLastChildOf[] = "isLastChildOf";
char sipName_BALL_isLastChild[] = "isLastChild";
char sipName_BALL_isFirstChildOf[] = "isFirstChildOf";
char sipName_BALL_isFirstChild[] = "isFirstChild";
char sipName_BALL_isChildOf[] = "isChildOf";
char sipName_BALL_isChild[] = "isChild";
char sipName_BALL_hasChild[] = "hasChild";
char sipName_BALL_isInterior[] = "isInterior";
char sipName_BALL_isRootOf[] = "isRootOf";
char sipName_BALL_isRoot[] = "isRoot";
char sipName_BALL_isCollapsed[] = "isCollapsed";
char sipName_BALL_isExpanded[] = "isExpanded";
char sipName_BALL_replace[] = "replace";
char sipName_BALL_removeChild[] = "removeChild";
char sipName_BALL_insertParent[] = "insertParent";
char sipName_BALL_appendChild[] = "appendChild";
char sipName_BALL_prependChild[] = "prependChild";
char sipName_BALL_collapse[] = "collapse";
char sipName_BALL_expand[] = "expand";
char sipName_BALL_getLastChild[] = "getLastChild";
char sipName_BALL_getFirstChild[] = "getFirstChild";
char sipName_BALL_getSibling[] = "getSibling";
char sipName_BALL_getChild[] = "getChild";
char sipName_BALL_getParent[] = "getParent";
char sipName_BALL_getLowestCommonAncestor[] = "getLowestCommonAncestor";
char sipName_BALL_getRoot[] = "getRoot";
char sipName_BALL_getPathLength[] = "getPathLength";
char sipName_BALL_countDescendants[] = "countDescendants";
char sipName_BALL_getDegree[] = "getDegree";
char sipName_BALL_compare[] = "compare";
char sipName_BALL_getNewHandle[] = "getNewHandle";
char sipName_BALL_getNextHandle[] = "getNextHandle";
char sipName_BALL_getHandle[] = "getHandle";
char sipName_BALL_Object[] = "Object";
char sipName_BALL_hasProperty[] = "hasProperty";
char sipName_BALL_countNamedProperties[] = "countNamedProperties";
char sipName_BALL_getProperty[] = "getProperty";
char sipName_BALL_countProperties[] = "countProperties";
char sipName_BALL_toggleProperty[] = "toggleProperty";
char sipName_BALL_clearProperty[] = "clearProperty";
char sipName_BALL_setProperty[] = "setProperty";
char sipName_BALL_getString[] = "getString";
char sipName_BALL_getObject[] = "getObject";
char sipName_BALL_getUnsignedInt[] = "getUnsignedInt";
char sipName_BALL_getFloat[] = "getFloat";
char sipName_BALL_getInt[] = "getInt";
char sipName_BALL_getBool[] = "getBool";
char sipName_BALL_getType[] = "getType";
char sipName_BALL_PersistentObject[] = "PersistentObject";
char sipName_BALL_NamedProperty[] = "NamedProperty";
char sipName_BALL_isSelected[] = "isSelected";
char sipName_BALL_deselect[] = "deselect";
char sipName_BALL_select[] = "select";
char sipName_BALL_Selectable[] = "Selectable";
char sipName_BALL_getElement[] = "getElement";
char sipName_BALL_PTE_[] = "PTE_";
char sipName_BALL_isUnknown[] = "isUnknown";
char sipName_BALL_getElectronegativity[] = "getElectronegativity";
char sipName_BALL_setElectronegativity[] = "setElectronegativity";
char sipName_BALL_getVanDerWaalsRadius[] = "getVanDerWaalsRadius";
char sipName_BALL_setVanDerWaalsRadius[] = "setVanDerWaalsRadius";
char sipName_BALL_getCovalentRadius[] = "getCovalentRadius";
char sipName_BALL_setCovalentRadius[] = "setCovalentRadius";
char sipName_BALL_getAtomicRadius[] = "getAtomicRadius";
char sipName_BALL_setAtomicRadius[] = "setAtomicRadius";
char sipName_BALL_getAtomicWeight[] = "getAtomicWeight";
char sipName_BALL_setAtomicWeight[] = "setAtomicWeight";
char sipName_BALL_getAtomicNumber[] = "getAtomicNumber";
char sipName_BALL_setAtomicNumber[] = "setAtomicNumber";
char sipName_BALL_getPeriod[] = "getPeriod";
char sipName_BALL_setPeriod[] = "setPeriod";
char sipName_BALL_getGroup[] = "getGroup";
char sipName_BALL_setGroup[] = "setGroup";
char sipName_BALL_getSymbol[] = "getSymbol";
char sipName_BALL_setSymbol[] = "setSymbol";
char sipName_BALL_Element[] = "Element";
char sipName_BALL_destroyBonds[] = "destroyBonds";
char sipName_BALL_splice[] = "splice";
char sipName_BALL_spliceAfter[] = "spliceAfter";
char sipName_BALL_spliceBefore[] = "spliceBefore";
char sipName_BALL_remove[] = "remove";
char sipName_BALL_insertAfter[] = "insertAfter";
char sipName_BALL_insertBefore[] = "insertBefore";
char sipName_BALL_insert[] = "insert";
char sipName_BALL_append[] = "append";
char sipName_BALL_prepend[] = "prepend";
char sipName_BALL_countAtoms[] = "countAtoms";
char sipName_BALL_countFragments[] = "countFragments";
char sipName_BALL_countMolecules[] = "countMolecules";
char sipName_BALL_getName[] = "getName";
char sipName_BALL_setName[] = "setName";
char sipName_BALL_clear[] = "clear";
char sipName_BALL_PropertyManager[] = "PropertyManager";
char sipName_BALL_Composite[] = "Composite";
char sipName_BALL_System[] = "System";
char sipName_BALL_b[] = "b";
char sipName_BALL_a[] = "a";
char sipName_BALL_join[] = "join";
char sipName_BALL_getDepth[] = "getDepth";
char sipName_BALL_getHeight[] = "getHeight";
char sipName_BALL_getWidth[] = "getWidth";
char sipName_BALL_getVolume[] = "getVolume";
char sipName_BALL_getSurface[] = "getSurface";
char sipName_BALL_get[] = "get";
char sipName_BALL_Box3[] = "Box3";
char sipName_BALL_isValid[] = "isValid";
char sipName_BALL_isEquivalent[] = "isEquivalent";
char sipName_BALL_negate[] = "negate";
char sipName_BALL_toDegree[] = "toDegree";
char sipName_BALL_toRadian[] = "toRadian";
char sipName_BALL_set[] = "set";
char sipName_BALL_Angle[] = "Angle";
char sipName_BALL_size[] = "size";
char sipName_BALL_c_str[] = "c_str";
char sipName_BALL_isWhitespace[] = "isWhitespace";
char sipName_BALL_isSpace[] = "isSpace";
char sipName_BALL_isDigit[] = "isDigit";
char sipName_BALL_isAlnum[] = "isAlnum";
char sipName_BALL_isAlpha[] = "isAlpha";
char sipName_BALL_isEmpty[] = "isEmpty";
char sipName_BALL_hasSuffix[] = "hasSuffix";
char sipName_BALL_hasPrefix[] = "hasPrefix";
char sipName_BALL_hasSubstring[] = "hasSubstring";
char sipName_BALL_has[] = "has";
char sipName_BALL_reverse[] = "reverse";
char sipName_BALL_swap[] = "swap";
char sipName_BALL_destroy[] = "destroy";
char sipName_BALL_String[] = "String";
char sipName_BALL_BALL[] = "BALL";

static sipClassDef classesTable[] = {
	{sipName_BALL_PeriodicBoundary, sipNew_PeriodicBoundary, &sipClass_PeriodicBoundary, sipClassAttrTab_PeriodicBoundary, sipClassVarHierTab_PeriodicBoundary},
	{sipName_BALL_ConjugateGradientMinimizer, sipNew_ConjugateGradientMinimizer, &sipClass_ConjugateGradientMinimizer, sipClassAttrTab_ConjugateGradientMinimizer, sipClassVarHierTab_ConjugateGradientMinimizer},
	{sipName_BALL_EnergyMinimizer, sipNew_EnergyMinimizer, &sipClass_EnergyMinimizer, sipClassAttrTab_EnergyMinimizer, sipClassVarHierTab_EnergyMinimizer},
	{sipName_BALL_SnapShotManager, sipNew_SnapShotManager, &sipClass_SnapShotManager, sipClassAttrTab_SnapShotManager, sipClassVarHierTab_SnapShotManager},
	{sipName_BALL_Gradient, sipNew_Gradient, &sipClass_Gradient, sipClassAttrTab_Gradient, sipClassVarHierTab_Gradient},
	{sipName_BALL_AtomVector, sipNew_AtomVector, &sipClass_AtomVector, sipClassAttrTab_AtomVector, NULL},
	{sipName_BALL_ForceFieldComponent, sipNew_ForceFieldComponent, &sipClass_ForceFieldComponent, sipClassAttrTab_ForceFieldComponent, NULL},
	{sipName_BALL_ForceField, sipNew_ForceField, &sipClass_ForceField, sipClassAttrTab_ForceField, sipClassVarHierTab_ForceField},
	{sipName_BALL_AmberFF, sipNew_AmberFF, &sipClass_AmberFF, sipClassAttrTab_AmberFF, NULL},
	{sipName_BALL_XYZFile, sipNew_XYZFile, &sipClass_XYZFile, sipClassAttrTab_XYZFile, NULL},
	{sipName_BALL_MOL2File, sipNew_MOL2File, &sipClass_MOL2File, sipClassAttrTab_MOL2File, NULL},
	{sipName_BALL_HINFile, sipNew_HINFile, &sipClass_HINFile, sipClassAttrTab_HINFile, NULL},
	{sipName_BALL_PDBFile, sipNew_PDBFile, &sipClass_PDBFile, sipClassAttrTab_PDBFile, NULL},
	{sipName_BALL_PDBAtom, sipNew_PDBAtom, &sipClass_PDBAtom, sipClassAttrTab_PDBAtom, NULL},
	{sipName_BALL_File, sipNew_File, &sipClass_File, sipClassAttrTab_File, NULL},
	{sipName_BALL_Residue, sipNew_Residue, &sipClass_Residue, sipClassAttrTab_Residue, NULL},
	{sipName_BALL_SecondaryStructure, sipNew_SecondaryStructure, &sipClass_SecondaryStructure, sipClassAttrTab_SecondaryStructure, NULL},
	{sipName_BALL_Chain, sipNew_Chain, &sipClass_Chain, sipClassAttrTab_Chain, NULL},
	{sipName_BALL_Protein, sipNew_Protein, &sipClass_Protein, sipClassAttrTab_Protein, NULL},
	{sipName_BALL_Options, sipNew_Options, &sipClass_Options, sipClassAttrTab_Options, NULL},
	{sipName_BALL_Molecule, sipNew_Molecule, &sipClass_Molecule, sipClassAttrTab_Molecule, NULL},
	{sipName_BALL_Fragment, sipNew_Fragment, &sipClass_Fragment, sipClassAttrTab_Fragment, NULL},
	{sipName_BALL_BaseFragment, sipNew_BaseFragment, &sipClass_BaseFragment, sipClassAttrTab_BaseFragment, NULL},
	{sipName_BALL_Atom, sipNew_Atom, &sipClass_Atom, sipClassAttrTab_Atom, NULL},
	{sipName_BALL_Bond, sipNew_Bond, &sipClass_Bond, sipClassAttrTab_Bond, NULL},
	{sipName_BALL_Vector3, sipNew_Vector3, &sipClass_Vector3, sipClassAttrTab_Vector3, NULL},
	{sipName_BALL_Object, sipNew_Object, &sipClass_Object, sipClassAttrTab_Object, NULL},
	{sipName_BALL_PersistentObject, sipNew_PersistentObject, &sipClass_PersistentObject, sipClassAttrTab_PersistentObject, NULL},
	{sipName_BALL_NamedProperty, sipNew_NamedProperty, &sipClass_NamedProperty, sipClassAttrTab_NamedProperty, NULL},
	{sipName_BALL_Selectable, sipNew_Selectable, &sipClass_Selectable, sipClassAttrTab_Selectable, NULL},
	{sipName_BALL_PTE_, sipNew_PTE_, &sipClass_PTE_, sipClassAttrTab_PTE_, NULL},
	{sipName_BALL_Element, sipNew_Element, &sipClass_Element, sipClassAttrTab_Element, NULL},
	{sipName_BALL_PropertyManager, sipNew_PropertyManager, &sipClass_PropertyManager, sipClassAttrTab_PropertyManager, NULL},
	{sipName_BALL_Composite, sipNew_Composite, &sipClass_Composite, sipClassAttrTab_Composite, NULL},
	{sipName_BALL_System, sipNew_System, &sipClass_System, sipClassAttrTab_System, NULL},
	{sipName_BALL_Box3, sipNew_Box3, &sipClass_Box3, sipClassAttrTab_Box3, sipClassVarHierTab_Box3},
	{sipName_BALL_Angle, sipNew_Angle, &sipClass_Angle, sipClassAttrTab_Angle, NULL},
	{sipName_BALL_String, sipNew_String, &sipClass_String, sipClassAttrTab_String, NULL},
};

static sipModuleDef sipModule = {
	sipName_BALL_BALL,
	38,
	classesTable
};

// The entry point into the bindings for constructors.

static PyObject *callCtor(PyObject *,PyObject *args)
{
	return sipCallCtor(&sipModule,args);
}

// The entry point into the bindings for getting class variables.

static PyObject *callGetVar(PyObject *,PyObject *args)
{
	return sipGetVar(&sipModule,args);
}

// The entry point into the bindings for setting class variables.

static PyObject *callSetVar(PyObject *,PyObject *args)
{
	return sipSetVar(&sipModule,args);
}

// Initialise the module.

static PyObject *initModule(PyObject *,PyObject *)
{
	if (sipRegisterModule(&sipModule) < 0)
		return NULL;

	Py_INCREF(Py_None);
	return Py_None;
}

// Final stage after the Python classes have been created.

static PyObject *registerClasses(PyObject *,PyObject *)
{
	if (sipRegisterClasses(&sipModule,-1) < 0)
		return NULL;

	Py_INCREF(Py_None);
	return Py_None;
}

// The Python module initialisation function.

extern "C" SIP_EXPORT void initlibBALLc()
{
	static PyMethodDef methods[] = {
		{"sipCallCtor", callCtor, METH_VARARGS, NULL},
		{"sipCallGetVar", callGetVar, METH_VARARGS, NULL},
		{"sipCallSetVar", callSetVar, METH_VARARGS, NULL},
		{"sipInitModule", initModule, METH_VARARGS, NULL},
		{"sipRegisterClasses", registerClasses, METH_VARARGS, NULL},
		{NULL}
	};

	// Initialise the module.

	Py_InitModule("libBALLc",methods);
}
