# $Id: Makefile,v 1.21 2002/01/15 03:29:19 oliver Exp $

DIRECTORY=PYTHON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	pyInterpreter.C

include ../common.mak
-include .Dependencies

ADD_INCLUDES=$(PYTHON_INCLUDES)
