// Generate a header file containing the version information.
//
// Generated by SIP v0.12 on Wed Jun 28 22:12:47 2000


#include <iostream.h>



int main(int argc,char **argv)
{
	cout << "// Define simple constants for each version qualifier.\n\n";

	return 0;
}
