// C++ class wrapper code.
//
// Generated by SIP v0.11.1 on Wed May  3 23:13:54 2000

#include "sipBALLDeclBALL.h"
#include "sipBALLObject.h"



PyObject *sipClass_Object;

static void sipDealloc_Object(sipThisType *);

static PyTypeObject sipType_Object = {
	PyObject_HEAD_INIT(&PyType_Type)
	0,
	sipName_BALL_Object,
	sizeof (sipThisType),
	0,
	(destructor)sipDealloc_Object,
	0,
	0,
	0,
	0,
	0,
};

sipObject::sipObject(): Object()
{
	sipCommonCtor(sipPyMethods,3);
}

sipObject::sipObject(const Object& a0,bool a1): Object(a0,a1)
{
	sipCommonCtor(sipPyMethods,3);
}

sipObject::sipObject(const Object& a0): Object(a0)
{
	sipCommonCtor(sipPyMethods,3);
}

sipObject::~sipObject()
{
	sipCommonDtor(sipPyThis);
}
void sipObject::clear()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[0],sipPyThis,NULL,sipName_BALL_clear,&relLock))
		sipObject::sipVH_clear(&sipPyMethods[0],sipPyThis,relLock);
	else
		Object::clear();
}
void sipObject::destroy()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[1],sipPyThis,NULL,sipName_BALL_destroy,&relLock))
		sipObject::sipVH_destroy(&sipPyMethods[1],sipPyThis,relLock);
	else
		Object::destroy();
}
bool sipObject::isValid() const
{
	int relLock;

	return sipIsPyMethod((sipMethodCache *)&sipPyMethods[2],sipPyThis,NULL,sipName_BALL_isValid,&relLock) ?
		sipObject::sipVH_isValid(&sipPyMethods[2],sipPyThis,relLock) :
		Object::isValid();
}

// The common handler for all classes that inherit this virtual member
// function.

void sipObject::sipVH_clear(const sipMethodCache *pymc,sipThisType *sipThis,int sipRelLock)
{
	PyObject *resobj;
	PyObject *sipArgs;

	sipArgs = Py_BuildValue("(O)",sipThis -> sipSelf);

	if (sipArgs == NULL)
		goto reportError;

	resobj = sipEvalMethod(&pymc -> pyMethod,sipArgs);

	Py_DECREF(sipArgs);

	if (resobj != NULL)
	{
		Py_DECREF(resobj);

		if (resobj == Py_None)
			goto releaseLock;

		sipBadVirtualResultType(sipName_BALL_Object,sipName_BALL_clear);
	}

reportError:
	PyErr_Print();

releaseLock:
	sipCondReleaseLock(sipRelLock);
}

// The common handler for all classes that inherit this virtual member
// function.

void sipObject::sipVH_destroy(const sipMethodCache *pymc,sipThisType *sipThis,int sipRelLock)
{
	PyObject *resobj;
	PyObject *sipArgs;

	sipArgs = Py_BuildValue("(O)",sipThis -> sipSelf);

	if (sipArgs == NULL)
		goto reportError;

	resobj = sipEvalMethod(&pymc -> pyMethod,sipArgs);

	Py_DECREF(sipArgs);

	if (resobj != NULL)
	{
		Py_DECREF(resobj);

		if (resobj == Py_None)
			goto releaseLock;

		sipBadVirtualResultType(sipName_BALL_Object,sipName_BALL_destroy);
	}

reportError:
	PyErr_Print();

releaseLock:
	sipCondReleaseLock(sipRelLock);
}

// The common handler for all classes that inherit this virtual member
// function.

bool sipObject::sipVH_isValid(const sipMethodCache *pymc,sipThisType *sipThis,int sipRelLock)
{
	bool res;
	PyObject *resobj;
	PyObject *sipArgs;

	sipArgs = Py_BuildValue("(O)",sipThis -> sipSelf);

	if (sipArgs == NULL)
		goto reportError;

	resobj = sipEvalMethod(&pymc -> pyMethod,sipArgs);

	Py_DECREF(sipArgs);

	if (resobj != NULL)
	{
		res = (bool)PyInt_AsLong(resobj);

		Py_DECREF(resobj);

		if (PyErr_Occurred() == NULL)
		{
			goto releaseLock;
		}

		sipBadVirtualResultType(sipName_BALL_Object,sipName_BALL_isValid);
	}

reportError:
	PyErr_Print();

releaseLock:
	sipCondReleaseLock(sipRelLock);

	return res;
}

static PyObject *sipDo_Object_clear(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Object)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			Object *ptr;

			if ((ptr = (Object *)sipGetCppPtr(sipThis,sipClass_Object)) == NULL)
				return NULL;

			ptr -> Object::clear();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_clear);

	return NULL;
}

static PyObject *sipDo_Object_destroy(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Object)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			Object *ptr;

			if ((ptr = (Object *)sipGetCppPtr(sipThis,sipClass_Object)) == NULL)
				return NULL;

			ptr -> Object::destroy();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_destroy);

	return NULL;
}

static PyObject *sipDo_Object_getHandle(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Object)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			int res;
			Object *ptr;

			if ((ptr = (Object *)sipGetCppPtr(sipThis,sipClass_Object)) == NULL)
				return NULL;

			res = ptr -> Object::getHandle();

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_getHandle);

	return NULL;
}

static PyObject *sipDo_Object_getNextHandle(PyObject *,PyObject *sipArgs)
{

	{
		if (sipParseArgs(sipArgs,"-"))
		{
			int res;

			res = Object::getNextHandle();

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_getNextHandle);

	return NULL;
}

static PyObject *sipDo_Object_getNewHandle(PyObject *,PyObject *sipArgs)
{

	{
		if (sipParseArgs(sipArgs,"-"))
		{
			int res;

			res = Object::getNewHandle();

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_getNewHandle);

	return NULL;
}

static PyObject *sipDo_Object_compare(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Object)) == NULL)
		return NULL;

	{
		const Object *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Object,&a0obj))
		{
			int res;
			Object *ptr;

			if ((ptr = (Object *)sipGetCppPtr(sipThis,sipClass_Object)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Object(a0obj,(Object **)&a0,&iserr);

			if (iserr)
				return NULL;

			res = ptr -> Object::compare(* a0);

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_compare);

	return NULL;
}

static PyObject *sipDo_Object_isValid(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Object)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			Object *ptr;

			if ((ptr = (Object *)sipGetCppPtr(sipThis,sipClass_Object)) == NULL)
				return NULL;

			res = ptr -> Object::isValid();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Object,sipName_BALL_isValid);

	return NULL;
}

// Cast a pointer to a type somewhere in its superclass hierachy.

const void *sipCast_Object(const void *ptr,PyObject *targetClass)
{
	if (targetClass == sipClass_Object)
		return ptr;

	return NULL;
}

static void sipDealloc_Object(sipThisType *sipThis)
{
	if (sipThis -> u.cppPtr != NULL)
	{
		if (!sipIsSimple(sipThis))
			((sipObject *)sipThis -> u.cppPtr) -> sipPyThis = NULL;

		if (sipIsPyOwned(sipThis))
			if (sipIsSimple(sipThis))
				delete (Object *)sipThis -> u.cppPtr;
			else
				delete (sipObject *)sipThis -> u.cppPtr;
	}

	sipDeleteThis(sipThis);
}

PyObject *sipNew_Object(PyObject *sipSelf,PyObject *sipArgs)
{
	static sipExtraType et = {
		sipCast_Object
	};

	sipThisType *sipThis = NULL;
	const void *sipNew = NULL;
	int sipFlags = SIP_PY_OWNED;

	// See if there is something pending.

	sipNew = sipGetPending(&sipFlags);

	if (sipNew == NULL)
	{
		if (sipParseArgs(sipArgs,"-"))
		{
			sipNew = new sipObject();
		}
	}

	if (sipNew == NULL)
	{
		const Object *a0;
		PyObject *a0obj;
		long a1 = true;

		if (sipParseArgs(sipArgs,"-I|l",sipCanConvertTo_Object,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_Object(a0obj,(Object **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new sipObject(* a0, (bool)a1);
		}
	}

	if (sipNew == NULL)
	{
		const Object *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"-I",sipCanConvertTo_Object,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_Object(a0obj,(Object **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new sipObject(* a0);
		}
	}

	if (sipNew == NULL)
	{
		sipNoCtor(sipName_BALL_Object);
		return NULL;
	}

	// Wrap the object.

	if ((sipThis = sipCreateThis(sipSelf,sipNew,&sipType_Object,sipFlags,&et)) == NULL)
	{
		if (sipFlags & SIP_PY_OWNED)
			if (sipFlags & SIP_SIMPLE)
				delete (Object *)sipNew;
			else
				delete (sipObject *)sipNew;

		return NULL;
	}

	if (!(sipFlags & SIP_SIMPLE))
		((sipObject *)sipNew) -> sipPyThis = sipThis;

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef sipClassAttrTab_Object[] = {
	{sipName_BALL_clear, sipDo_Object_clear, METH_VARARGS, NULL},
	{sipName_BALL_destroy, sipDo_Object_destroy, METH_VARARGS, NULL},
	{sipName_BALL_getHandle, sipDo_Object_getHandle, METH_VARARGS, NULL},
	{sipName_BALL_getNextHandle, sipDo_Object_getNextHandle, METH_VARARGS, NULL},
	{sipName_BALL_getNewHandle, sipDo_Object_getNewHandle, METH_VARARGS, NULL},
	{sipName_BALL_compare, sipDo_Object_compare, METH_VARARGS, NULL},
	{sipName_BALL_isValid, sipDo_Object_isValid, METH_VARARGS, NULL},
	{NULL}
};

int sipCanConvertTo_Object(PyObject *sipPy)
{
	return sipIsSubClassInstance(sipPy,sipClass_Object);
}

void sipConvertTo_Object(PyObject *sipPy,Object **sipCppPtr,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return;

	if (sipPy == Py_None)
	{
		*sipCppPtr = NULL;
		return;
	}

	*sipCppPtr = (Object *)sipConvertToCpp(sipPy,sipClass_Object,sipIsErr);
}

Object *sipForceConvertTo_Object(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_Object(valobj))
	{
		Object *val;

		sipConvertTo_Object(valobj,&val,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_Object);
	*iserrp = 1;

	return NULL;
}
