// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Wed Jul 12 19:49:27 2000

#ifndef _BALLPyResidueList_H
#define	_BALLPyResidueList_H


#line 6 "pyResidueList.sip"
	#include <BALL/PYTHON/pyResidueList.h>
	#include "sipBALLResidue.h"
  #include <BALL/PYTHON/pyBALLSipHelper.h>
#line 14 "./sipBALLPyResidueList.h"

extern SIP_EXPORT int sipCanConvertTo_PyResidueList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyResidueList Py_PROTO((PyObject *,PyResidueList **,int,int *));
extern SIP_EXPORT PyResidueList *sipForceConvertTo_PyResidueList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyResidueList Py_PROTO((const PyResidueList *));

#endif
