// C++ class wrapper code.
//
// Generated by SIP v0.11.1 on Tue May  9 00:35:55 2000

#include "sipBALLDeclBALL.h"
#include "sipBALLSnapShot.h"



PyObject *sipClass_SnapShot;

static void sipDealloc_SnapShot(sipThisType *);

static PyTypeObject sipType_SnapShot = {
	PyObject_HEAD_INIT(&PyType_Type)
	0,
	sipName_BALL_SnapShot,
	sizeof (sipThisType),
	0,
	(destructor)sipDealloc_SnapShot,
	0,
	0,
	0,
	0,
	0,
};

static PyObject *sipDo_SnapShot_isValid(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_SnapShot)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			SnapShot *ptr;

			if ((ptr = (SnapShot *)sipGetCppPtr(sipThis,sipClass_SnapShot)) == NULL)
				return NULL;

			res = ptr -> SnapShot::isValid();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_SnapShot,sipName_BALL_isValid);

	return NULL;
}

// Cast a pointer to a type somewhere in its superclass hierachy.

const void *sipCast_SnapShot(const void *ptr,PyObject *targetClass)
{
	if (targetClass == sipClass_SnapShot)
		return ptr;

	return NULL;
}

static void sipDealloc_SnapShot(sipThisType *sipThis)
{
	if (sipThis -> u.cppPtr != NULL)
	{
		if (sipIsPyOwned(sipThis))
			delete (SnapShot *)sipThis -> u.cppPtr;
	}

	sipDeleteThis(sipThis);
}

PyObject *sipNew_SnapShot(PyObject *sipSelf,PyObject *sipArgs)
{
	static sipExtraType et = {
		sipCast_SnapShot
	};

	sipThisType *sipThis = NULL;
	const void *sipNew = NULL;
	int sipFlags = SIP_PY_OWNED;

	// See if there is something pending.

	sipNew = sipGetPending(&sipFlags);

	if (sipNew == NULL)
	{
		if (sipParseArgs(sipArgs,"-"))
		{
			sipNew = new SnapShot();
		}
	}

	if (sipNew == NULL)
	{
		int a0;

		if (sipParseArgs(sipArgs,"-i",&a0))
		{
			sipNew = new SnapShot( a0);
		}
	}

	if (sipNew == NULL)
	{
		SnapShot *a0;
		PyObject *a0obj;
		long a1;

		if (sipParseArgs(sipArgs,"-Il",sipCanConvertTo_SnapShot,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_SnapShot(a0obj,&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new SnapShot(* a0, (bool)a1);
		}
	}

	if (sipNew == NULL)
	{
		const SnapShot *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"-I",sipCanConvertTo_SnapShot,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_SnapShot(a0obj,(SnapShot **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new SnapShot(* a0);
		}
	}

	if (sipNew == NULL)
	{
		sipNoCtor(sipName_BALL_SnapShot);
		return NULL;
	}

	// Wrap the object.

	if ((sipThis = sipCreateThis(sipSelf,sipNew,&sipType_SnapShot,sipFlags,&et)) == NULL)
	{
		if (sipFlags & SIP_PY_OWNED)
			delete (SnapShot *)sipNew;

		return NULL;
	}

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_valid(PyObject *sipThisObj,PyObject *valobj)
{
	bool val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> valid;

		valobj = sipConvertFromBool((int)val);

		return valobj;
	}

	val = (bool)PyInt_AsLong(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_valid);
		return NULL;
	}

	ptr -> valid = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_index(PyObject *sipThisObj,PyObject *valobj)
{
	int val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> index;

		valobj = PyInt_FromLong((long)val);

		return valobj;
	}

	val = (int)PyInt_AsLong(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_index);
		return NULL;
	}

	ptr -> index = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_total_length(PyObject *sipThisObj,PyObject *valobj)
{
	int val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> total_length;

		valobj = PyInt_FromLong((long)val);

		return valobj;
	}

	val = (int)PyInt_AsLong(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_total_length);
		return NULL;
	}

	ptr -> total_length = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_data_length(PyObject *sipThisObj,PyObject *valobj)
{
	int val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> data_length;

		valobj = PyInt_FromLong((long)val);

		return valobj;
	}

	val = (int)PyInt_AsLong(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_data_length);
		return NULL;
	}

	ptr -> data_length = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_no_of_atoms(PyObject *sipThisObj,PyObject *valobj)
{
	int val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> no_of_atoms;

		valobj = PyInt_FromLong((long)val);

		return valobj;
	}

	val = (int)PyInt_AsLong(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_no_of_atoms);
		return NULL;
	}

	ptr -> no_of_atoms = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_potential_energy(PyObject *sipThisObj,PyObject *valobj)
{
	double val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> potential_energy;

		valobj = PyFloat_FromDouble(val);

		return valobj;
	}

	val = PyFloat_AsDouble(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_potential_energy);
		return NULL;
	}

	ptr -> potential_energy = val;

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_SnapShot_kinetic_energy(PyObject *sipThisObj,PyObject *valobj)
{
	double val;
	SnapShot *ptr;

	if ((ptr = (SnapShot *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_SnapShot)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> kinetic_energy;

		valobj = PyFloat_FromDouble(val);

		return valobj;
	}

	val = PyFloat_AsDouble(valobj);

	if (PyErr_Occurred() != NULL)
	{
		sipBadSetType(sipName_BALL_SnapShot,sipName_BALL_kinetic_energy);
		return NULL;
	}

	ptr -> kinetic_energy = val;

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef sipClassAttrTab_SnapShot[] = {
	{sipName_BALL_isValid, sipDo_SnapShot_isValid, METH_VARARGS, NULL},
	{NULL}
};

PyMethodDef sipClassVarTab_SnapShot[] = {
	{sipName_BALL_valid, sipGetSetVar_SnapShot_valid, 0, NULL},
	{sipName_BALL_index, sipGetSetVar_SnapShot_index, 0, NULL},
	{sipName_BALL_total_length, sipGetSetVar_SnapShot_total_length, 0, NULL},
	{sipName_BALL_data_length, sipGetSetVar_SnapShot_data_length, 0, NULL},
	{sipName_BALL_no_of_atoms, sipGetSetVar_SnapShot_no_of_atoms, 0, NULL},
	{sipName_BALL_potential_energy, sipGetSetVar_SnapShot_potential_energy, 0, NULL},
	{sipName_BALL_kinetic_energy, sipGetSetVar_SnapShot_kinetic_energy, 0, NULL},
	{NULL}
};

PyMethodDef *sipClassVarHierTab_SnapShot[] = {
	sipClassVarTab_SnapShot,
	NULL
};

int sipCanConvertTo_SnapShot(PyObject *sipPy)
{
	return sipIsSubClassInstance(sipPy,sipClass_SnapShot);
}

void sipConvertTo_SnapShot(PyObject *sipPy,SnapShot **sipCppPtr,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return;

	if (sipPy == Py_None)
	{
		*sipCppPtr = NULL;
		return;
	}

	*sipCppPtr = (SnapShot *)sipConvertToCpp(sipPy,sipClass_SnapShot,sipIsErr);
}

SnapShot *sipForceConvertTo_SnapShot(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_SnapShot(valobj))
	{
		SnapShot *val;

		sipConvertTo_SnapShot(valobj,&val,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_SnapShot);
	*iserrp = 1;

	return NULL;
}
