// C++ wrapper class header file.
//
// Generated by SIP v0.11.1 on Wed May  3 23:53:29 2000

#ifndef _BALLSnapShot_H
#define	_BALLSnapShot_H


#line 4 "snapShot.sip"
#include <BALL/MOLMEC/COMMON/snapShot.h>
using namespace BALL;
#line 13 "./sipBALLSnapShot.h"

extern SIP_EXPORT PyObject *sipClass_SnapShot;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_SnapShot[];
extern SIP_EXPORT PyMethodDef sipClassVarTab_SnapShot[];
extern SIP_EXPORT PyMethodDef *sipClassVarHierTab_SnapShot[];

extern SIP_EXPORT const void *sipCast_SnapShot Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_SnapShot Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_SnapShot Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_SnapShot Py_PROTO((PyObject *,SnapShot **,int *));
extern SIP_EXPORT SnapShot *sipForceConvertTo_SnapShot Py_PROTO((PyObject *,int *));

#endif
