// C++ wrapper class header file.
//
// Generated by SIP v0.11.1 on Sun Apr 30 20:31:23 2000

#ifndef _BALLVector3_H
#define	_BALLVector3_H

#include "sipBALLPersistentObject.h"
#include "sipBALLAngle.h"

#line 5 "vector3.sip"
#include <BALL/MATHS/vector3.h>
using namespace BALL;
#line 15 "./sipBALLVector3.h"

extern SIP_EXPORT PyObject *sipClass_Vector3;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Vector3[];

extern SIP_EXPORT const void *sipCast_Vector3 Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Vector3 Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Vector3 Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Vector3 Py_PROTO((PyObject *,Vector3 **,int *));
extern SIP_EXPORT Vector3 *sipForceConvertTo_Vector3 Py_PROTO((PyObject *,int *));

#endif
