// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Fri Jun 30 00:19:14 2000

#ifndef _BALLCharmmFF_H
#define	_BALLCharmmFF_H

#include "sipBALLForceField.h"
#include "sipBALLSystem.h"
#include "sipBALLOptions.h"

#line 7 "charmm.sip"
	#include <BALL/MOLMEC/CHARMM/charmm.h>
	using namespace BALL;
#line 16 "./sipBALLCharmmFF.h"

extern SIP_EXPORT PyObject *sipClass_CharmmFF;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_CharmmFF[];

extern SIP_EXPORT const void *sipCast_CharmmFF Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_CharmmFF Py_PROTO((PyObject *,PyObject *));


class SIP_EXPORT sipCharmmFF : public CharmmFF
{
public:
	sipCharmmFF();
	sipCharmmFF(System&);
	sipCharmmFF(System&,const Options&);
	sipCharmmFF(const CharmmFF&,bool);
	sipCharmmFF(const CharmmFF&);
	~sipCharmmFF();

       // There is a catcher function for every virtual member function in
       // the class hierachy.

	bool specificSetup();

	sipThisType *sipPyThis;

private:
	sipMethodCache sipPyMethods[1];
};

extern SIP_EXPORT int sipCanConvertTo_CharmmFF Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_CharmmFF Py_PROTO((PyObject *,CharmmFF **,int,int *));
extern SIP_EXPORT CharmmFF *sipForceConvertTo_CharmmFF Py_PROTO((PyObject *,int *));

#endif
