// C++ wrapper class header file.
//
// Generated by SIP v0.12 on Fri Jun 30 00:19:14 2000

#ifndef _BALLPyAtomList_H
#define	_BALLPyAtomList_H


#line 5 "pyAtomList.sip"
#include <BALL/PYTHON/pyAtomList.h>
#include "sipBALLAtom.h"
#line 13 "./sipBALLPyAtomList.h"

extern SIP_EXPORT int sipCanConvertTo_PyAtomList Py_PROTO((PyObject *));
extern SIP_EXPORT int sipConvertTo_PyAtomList Py_PROTO((PyObject *,PyAtomList **,int,int *));
extern SIP_EXPORT PyAtomList *sipForceConvertTo_PyAtomList Py_PROTO((PyObject *,int *));
extern SIP_EXPORT PyObject *sipConvertFrom_PyAtomList Py_PROTO((const PyAtomList *));

#endif
