// C++ class wrapper code.
//
// Generated by SIP v0.12 on Tue Jun 27 14:52:45 2000

#include "sipBALLDeclBALL.h"
#include "sipBALLNucleotide.h"



PyObject *sipClass_Nucleotide;

static void sipDealloc_Nucleotide(sipThisType *);

static PyTypeObject sipType_Nucleotide = {
	PyObject_HEAD_INIT(&PyType_Type)
	0,
	sipName_BALL_Nucleotide,
	sizeof (sipThisType),
	0,
	(destructor)sipDealloc_Nucleotide,
	0,
	0,
	0,
	0,
	0,
};

sipNucleotide::sipNucleotide(): Nucleotide()
{
	sipCommonCtor(sipPyMethods,5);
}

sipNucleotide::sipNucleotide(const Nucleotide& a0,bool a1): Nucleotide(a0,a1)
{
	sipCommonCtor(sipPyMethods,5);
}

sipNucleotide::sipNucleotide(const String& a0,const String& a1,char a2): Nucleotide(a0,a1,a2)
{
	sipCommonCtor(sipPyMethods,5);
}

sipNucleotide::sipNucleotide(const Nucleotide& a0): Nucleotide(a0)
{
	sipCommonCtor(sipPyMethods,5);
}

sipNucleotide::~sipNucleotide()
{
	sipCommonDtor(sipPyThis);
}
void sipNucleotide::select()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[0],sipPyThis,NULL,sipName_BALL_select,&relLock))
		sipSelectable::sipVH_select(&sipPyMethods[0],sipPyThis,relLock);
	else
		Composite::select();
}
void sipNucleotide::deselect()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[1],sipPyThis,NULL,sipName_BALL_deselect,&relLock))
		sipSelectable::sipVH_deselect(&sipPyMethods[1],sipPyThis,relLock);
	else
		Composite::deselect();
}
void sipNucleotide::clear()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[2],sipPyThis,NULL,sipName_BALL_clear,&relLock))
		sipObject::sipVH_clear(&sipPyMethods[2],sipPyThis,relLock);
	else
		Nucleotide::clear();
}
void sipNucleotide::destroy()
{
	int relLock;

	if (sipIsPyMethod(&sipPyMethods[3],sipPyThis,NULL,sipName_BALL_destroy,&relLock))
		sipObject::sipVH_destroy(&sipPyMethods[3],sipPyThis,relLock);
	else
		Nucleotide::destroy();
}
bool sipNucleotide::isValid() const
{
	int relLock;

	return sipIsPyMethod((sipMethodCache *)&sipPyMethods[4],sipPyThis,NULL,sipName_BALL_isValid,&relLock) ?
		sipObject::sipVH_isValid(&sipPyMethods[4],sipPyThis,relLock) :
		Nucleotide::isValid();
}

static PyObject *sipDo_Nucleotide_clear(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			ptr -> Nucleotide::clear();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_clear);

	return NULL;
}

static PyObject *sipDo_Nucleotide_destroy(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			ptr -> Nucleotide::destroy();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_destroy);

	return NULL;
}

static PyObject *sipDo_Nucleotide_set(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		const Nucleotide *a0;
		PyObject *a0obj;
		long a1 = true;

		if (sipParseArgs(sipArgs,"I|l",sipCanConvertTo_Nucleotide,&a0obj,&a1))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,(Nucleotide **)&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::set(* a0, (bool)a1);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_set);

	return NULL;
}

static PyObject *sipDo_Nucleotide_get(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Nucleotide *a0;
		PyObject *a0obj;
		long a1 = true;

		if (sipParseArgs(sipArgs,"I|l",sipCanConvertTo_Nucleotide,&a0obj,&a1))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::get(* a0, (bool)a1);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_get);

	return NULL;
}

static PyObject *sipDo_Nucleotide_swap(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Nucleotide *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Nucleotide,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::swap(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_swap);

	return NULL;
}

static PyObject *sipDo_Nucleotide_getNucleicAcid(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			NucleicAcid *res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::getNucleicAcid();

			return sipMapCppToSelf(res,sipClass_NucleicAcid);
		}
	}

	{
		if (sipParseArgs(sipArgs,""))
		{
			const NucleicAcid *res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::getNucleicAcid();

			return sipMapCppToSelf(res,sipClass_NucleicAcid);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_getNucleicAcid);

	return NULL;
}

static PyObject *sipDo_Nucleotide_setID(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		const String *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_String,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			int istemp0 = sipConvertTo_String(a0obj,(String **)&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::setID(* a0);

			if (istemp0)
				delete a0;

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_setID);

	return NULL;
}

static PyObject *sipDo_Nucleotide_getID(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			const String *res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = &ptr -> Nucleotide::getID();

			return sipMapCppToSelf(res,sipClass_String);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_getID);

	return NULL;
}

static PyObject *sipDo_Nucleotide_setInsertionCode(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		char a0;

		if (sipParseArgs(sipArgs,"c",&a0))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			ptr -> Nucleotide::setInsertionCode( a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_setInsertionCode);

	return NULL;
}

static PyObject *sipDo_Nucleotide_getInsertionCode(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			char res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::getInsertionCode();

			return PyString_FromStringAndSize(&res,1);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_getInsertionCode);

	return NULL;
}

static PyObject *sipDo_Nucleotide_prepend(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Atom,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::prepend(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_prepend);

	return NULL;
}

static PyObject *sipDo_Nucleotide_append(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Atom,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::append(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_append);

	return NULL;
}

static PyObject *sipDo_Nucleotide_insert(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Atom,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::insert(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_insert);

	return NULL;
}

static PyObject *sipDo_Nucleotide_insertBefore(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;
		Composite *a1;
		PyObject *a1obj;

		if (sipParseArgs(sipArgs,"II",sipCanConvertTo_Atom,&a0obj,sipCanConvertTo_Composite,&a1obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);
			sipConvertTo_Composite(a1obj,&a1,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::insertBefore(* a0,* a1);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_insertBefore);

	return NULL;
}

static PyObject *sipDo_Nucleotide_insertAfter(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;
		Composite *a1;
		PyObject *a1obj;

		if (sipParseArgs(sipArgs,"II",sipCanConvertTo_Atom,&a0obj,sipCanConvertTo_Composite,&a1obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);
			sipConvertTo_Composite(a1obj,&a1,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::insertAfter(* a0,* a1);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_insertAfter);

	return NULL;
}

static PyObject *sipDo_Nucleotide_remove(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Atom *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Atom,&a0obj))
		{
			bool res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Atom(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			res = ptr -> Nucleotide::remove(* a0);

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_remove);

	return NULL;
}

static PyObject *sipDo_Nucleotide_spliceBefore(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Nucleotide *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Nucleotide,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::spliceBefore(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_spliceBefore);

	return NULL;
}

static PyObject *sipDo_Nucleotide_spliceAfter(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Nucleotide *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Nucleotide,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::spliceAfter(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_spliceAfter);

	return NULL;
}

static PyObject *sipDo_Nucleotide_splice(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		Nucleotide *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Nucleotide,&a0obj))
		{
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,&a0,1,&iserr);

			if (iserr)
				return NULL;

			ptr -> Nucleotide::splice(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_splice);

	return NULL;
}

static PyObject *sipDo_Nucleotide_isTerminal(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::isTerminal();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_isTerminal);

	return NULL;
}

static PyObject *sipDo_Nucleotide_is3Prime(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::is3Prime();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_is3Prime);

	return NULL;
}

static PyObject *sipDo_Nucleotide_is5Prime(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::is5Prime();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_is5Prime);

	return NULL;
}

static PyObject *sipDo_Nucleotide_isValid(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_Nucleotide)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			Nucleotide *ptr;

			if ((ptr = (Nucleotide *)sipGetCppPtr(sipThis,sipClass_Nucleotide)) == NULL)
				return NULL;

			res = ptr -> Nucleotide::isValid();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_Nucleotide,sipName_BALL_isValid);

	return NULL;
}

// Cast a pointer to a type somewhere in its superclass hierachy.

const void *sipCast_Nucleotide(const void *ptr,PyObject *targetClass)
{
	const void *res;

	if (targetClass == sipClass_Nucleotide)
		return ptr;

	if ((res = sipCast_Fragment((Fragment *)(Nucleotide *)ptr,targetClass)) != NULL)
		return res;

	return NULL;
}

static void sipDealloc_Nucleotide(sipThisType *sipThis)
{
	if (sipThis -> u.cppPtr != NULL)
	{
		if (!sipIsSimple(sipThis))
			((sipNucleotide *)sipThis -> u.cppPtr) -> sipPyThis = NULL;

		if (sipIsPyOwned(sipThis))
			if (sipIsSimple(sipThis))
				delete (Nucleotide *)sipThis -> u.cppPtr;
			else
				delete (sipNucleotide *)sipThis -> u.cppPtr;
	}

	sipDeleteThis(sipThis);
}

PyObject *sipNew_Nucleotide(PyObject *sipSelf,PyObject *sipArgs)
{
	static sipExtraType et = {
		sipCast_Nucleotide
	};

	sipThisType *sipThis = NULL;
	const void *sipNew = NULL;
	int sipFlags = SIP_PY_OWNED;

	// See if there is something pending.

	sipNew = sipGetPending(&sipFlags);

	if (sipNew == NULL)
	{
		if (sipParseArgs(sipArgs,"-"))
		{
			sipNew = new sipNucleotide();
		}
	}

	if (sipNew == NULL)
	{
		const Nucleotide *a0;
		PyObject *a0obj;
		long a1 = true;

		if (sipParseArgs(sipArgs,"-I|l",sipCanConvertTo_Nucleotide,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,(Nucleotide **)&a0,1,&iserr);

			if (iserr)
				return NULL;

			sipNew = new sipNucleotide(* a0, (bool)a1);
		}
	}

	if (sipNew == NULL)
	{
		const String *a0;
		PyObject *a0obj;
		const String *a1 = NULL;
		PyObject *a1obj = NULL;
		char a2 = ' ';

		if (sipParseArgs(sipArgs,"-I|Ic",sipCanConvertTo_String,&a0obj,sipCanConvertTo_String,&a1obj,&a2))
		{
			int iserr = 0;

			int istemp0 = sipConvertTo_String(a0obj,(String **)&a0,1,&iserr);
			int istemp1 = sipConvertTo_String(a1obj,(String **)&a1,1,&iserr);

			if (iserr)
				return NULL;

			sipNew = new sipNucleotide(* a0,* a1, a2);

			if (istemp0)
				delete a0;

			if (istemp1)
				delete a1;
		}
	}

	if (sipNew == NULL)
	{
		const Nucleotide *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"-I",sipCanConvertTo_Nucleotide,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_Nucleotide(a0obj,(Nucleotide **)&a0,1,&iserr);

			if (iserr)
				return NULL;

			sipNew = new sipNucleotide(* a0);
		}
	}

	if (sipNew == NULL)
	{
		sipNoCtor(sipName_BALL_Nucleotide);
		return NULL;
	}

	// Wrap the object.

	if ((sipThis = sipCreateThis(sipSelf,sipNew,&sipType_Nucleotide,sipFlags,&et)) == NULL)
	{
		if (sipFlags & SIP_PY_OWNED)
			if (sipFlags & SIP_SIMPLE)
				delete (Nucleotide *)sipNew;
			else
				delete (sipNucleotide *)sipNew;

		return NULL;
	}

	if (!(sipFlags & SIP_SIMPLE))
		((sipNucleotide *)sipNew) -> sipPyThis = sipThis;

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef sipClassAttrTab_Nucleotide[] = {
	{sipName_BALL_clear, sipDo_Nucleotide_clear, METH_VARARGS, NULL},
	{sipName_BALL_destroy, sipDo_Nucleotide_destroy, METH_VARARGS, NULL},
	{sipName_BALL_set, sipDo_Nucleotide_set, METH_VARARGS, NULL},
	{sipName_BALL_get, sipDo_Nucleotide_get, METH_VARARGS, NULL},
	{sipName_BALL_swap, sipDo_Nucleotide_swap, METH_VARARGS, NULL},
	{sipName_BALL_getNucleicAcid, sipDo_Nucleotide_getNucleicAcid, METH_VARARGS, NULL},
	{sipName_BALL_setID, sipDo_Nucleotide_setID, METH_VARARGS, NULL},
	{sipName_BALL_getID, sipDo_Nucleotide_getID, METH_VARARGS, NULL},
	{sipName_BALL_setInsertionCode, sipDo_Nucleotide_setInsertionCode, METH_VARARGS, NULL},
	{sipName_BALL_getInsertionCode, sipDo_Nucleotide_getInsertionCode, METH_VARARGS, NULL},
	{sipName_BALL_prepend, sipDo_Nucleotide_prepend, METH_VARARGS, NULL},
	{sipName_BALL_append, sipDo_Nucleotide_append, METH_VARARGS, NULL},
	{sipName_BALL_insert, sipDo_Nucleotide_insert, METH_VARARGS, NULL},
	{sipName_BALL_insertBefore, sipDo_Nucleotide_insertBefore, METH_VARARGS, NULL},
	{sipName_BALL_insertAfter, sipDo_Nucleotide_insertAfter, METH_VARARGS, NULL},
	{sipName_BALL_remove, sipDo_Nucleotide_remove, METH_VARARGS, NULL},
	{sipName_BALL_spliceBefore, sipDo_Nucleotide_spliceBefore, METH_VARARGS, NULL},
	{sipName_BALL_spliceAfter, sipDo_Nucleotide_spliceAfter, METH_VARARGS, NULL},
	{sipName_BALL_splice, sipDo_Nucleotide_splice, METH_VARARGS, NULL},
	{sipName_BALL_isTerminal, sipDo_Nucleotide_isTerminal, METH_VARARGS, NULL},
	{sipName_BALL_is3Prime, sipDo_Nucleotide_is3Prime, METH_VARARGS, NULL},
	{sipName_BALL_is5Prime, sipDo_Nucleotide_is5Prime, METH_VARARGS, NULL},
	{sipName_BALL_isValid, sipDo_Nucleotide_isValid, METH_VARARGS, NULL},
	{NULL}
};

int sipCanConvertTo_Nucleotide(PyObject *sipPy)
{
	return sipIsSubClassInstance(sipPy,sipClass_Nucleotide);
}

void sipConvertTo_Nucleotide(PyObject *sipPy,Nucleotide **sipCppPtr,int sipNoNull,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return;

	if (sipPy == Py_None)
	{
		if (sipNoNull)
			sipNullArgument(sipName_BALL_Nucleotide);
		else
			*sipCppPtr = NULL;

		return;
	}

	*sipCppPtr = (Nucleotide *)sipConvertToCpp(sipPy,sipClass_Nucleotide,sipIsErr);
}

Nucleotide *sipForceConvertTo_Nucleotide(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_Nucleotide(valobj))
	{
		Nucleotide *val;

		sipConvertTo_Nucleotide(valobj,&val,0,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_Nucleotide);
	*iserrp = 1;

	return NULL;
}
