// C++ wrapper class header file.
//
// Generated by SIP v0.11.1 on Wed May  3 23:13:54 2000

#ifndef _BALLString_H
#define	_BALLString_H


#line 4 "string.sip"
#include <BALL/DATATYPE/string.h>
using namespace BALL;
#line 13 "./sipBALLString.h"

extern SIP_EXPORT PyObject *sipClass_String;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_String[];

extern SIP_EXPORT const void *sipCast_String Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_String Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_String Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_String Py_PROTO((PyObject *,String **,int *));
extern SIP_EXPORT String *sipForceConvertTo_String Py_PROTO((PyObject *,int *));

#endif
