// C++ wrapper class header file.
//
// Generated by SIP v0.11.1 on Wed May  3 23:13:53 2000

#ifndef _BALLOptions_H
#define	_BALLOptions_H

#include "sipBALLString.h"
#include "sipBALLVector3.h"

#line 4 "options.sip"
#include <BALL/DATATYPE/options.h>
using namespace BALL;
#line 15 "./sipBALLOptions.h"

extern SIP_EXPORT PyObject *sipClass_Options;
extern SIP_EXPORT PyMethodDef sipClassAttrTab_Options[];

extern SIP_EXPORT const void *sipCast_Options Py_PROTO((const void *,PyObject *));
extern SIP_EXPORT PyObject *sipNew_Options Py_PROTO((PyObject *,PyObject *));

extern SIP_EXPORT int sipCanConvertTo_Options Py_PROTO((PyObject *));
extern SIP_EXPORT void sipConvertTo_Options Py_PROTO((PyObject *,Options **,int *));
extern SIP_EXPORT Options *sipForceConvertTo_Options Py_PROTO((PyObject *,int *));

#endif
