// C++ class wrapper code.
//
// Generated by SIP v0.11.1 on Wed May  3 23:13:53 2000

#include "sipBALLDeclBALL.h"
#include "sipBALLPeriodicBoundary.h"



PyObject *sipClass_PeriodicBoundary;

static void sipDealloc_PeriodicBoundary(sipThisType *);

static PyTypeObject sipType_PeriodicBoundary = {
	PyObject_HEAD_INIT(&PyType_Type)
	0,
	sipName_BALL_PeriodicBoundary,
	sizeof (sipThisType),
	0,
	(destructor)sipDealloc_PeriodicBoundary,
	0,
	0,
	0,
	0,
	0,
};

static PyObject *sipDo_PeriodicBoundary_setup(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			res = ptr -> PeriodicBoundary::setup();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_setup);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_generateMoleculesVector(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			int res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			res = ptr -> PeriodicBoundary::generateMoleculesVector();

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_generateMoleculesVector);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_enable(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			ptr -> PeriodicBoundary::enable();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_enable);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_disable(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			ptr -> PeriodicBoundary::disable();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_disable);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_getBox(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			Box3 *res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			res = new Box3(ptr -> PeriodicBoundary::getBox());

			return sipNewCppToSelf(res,sipClass_Box3,SIP_SIMPLE | SIP_PY_OWNED);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_getBox);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_setBox(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		const Box3 *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_Box3,&a0obj))
		{
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_Box3(a0obj,(Box3 **)&a0,&iserr);

			if (iserr)
				return NULL;

			ptr -> PeriodicBoundary::setBox(* a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_setBox);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_addSolvent(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		const String *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"I",sipCanConvertTo_String,&a0obj))
		{
			int res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			int iserr = 0;

			sipConvertTo_String(a0obj,(String **)&a0,&iserr);

			if (iserr)
				return NULL;

			res = ptr -> PeriodicBoundary::addSolvent(* a0);

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_addSolvent);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_removeSolvent(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			int res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			res = ptr -> PeriodicBoundary::removeSolvent();

			return PyInt_FromLong((long)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_removeSolvent);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_isEnabled(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			bool res;
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			res = ptr -> PeriodicBoundary::isEnabled();

			return sipConvertFromBool((int)res);
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_isEnabled);

	return NULL;
}

static PyObject *sipDo_PeriodicBoundary_updateMolecules(PyObject *sipThisObj,PyObject *sipArgs)
{
	sipThisType *sipThis;

	if ((sipThis = sipGetThis(sipThisObj,&sipArgs,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	{
		if (sipParseArgs(sipArgs,""))
		{
			PeriodicBoundary *ptr;

			if ((ptr = (PeriodicBoundary *)sipGetCppPtr(sipThis,sipClass_PeriodicBoundary)) == NULL)
				return NULL;

			ptr -> PeriodicBoundary::updateMolecules();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	// Report an error if the arguments couldn't be parsed.

	sipNoMethod(sipName_BALL_PeriodicBoundary,sipName_BALL_updateMolecules);

	return NULL;
}

// Cast a pointer to a type somewhere in its superclass hierachy.

const void *sipCast_PeriodicBoundary(const void *ptr,PyObject *targetClass)
{
	if (targetClass == sipClass_PeriodicBoundary)
		return ptr;

	return NULL;
}

static void sipDealloc_PeriodicBoundary(sipThisType *sipThis)
{
	if (sipThis -> u.cppPtr != NULL)
	{
		if (sipIsPyOwned(sipThis))
			delete (PeriodicBoundary *)sipThis -> u.cppPtr;
	}

	sipDeleteThis(sipThis);
}

PyObject *sipNew_PeriodicBoundary(PyObject *sipSelf,PyObject *sipArgs)
{
	static sipExtraType et = {
		sipCast_PeriodicBoundary
	};

	sipThisType *sipThis = NULL;
	const void *sipNew = NULL;
	int sipFlags = SIP_PY_OWNED;

	// See if there is something pending.

	sipNew = sipGetPending(&sipFlags);

	if (sipNew == NULL)
	{
		if (sipParseArgs(sipArgs,"-"))
		{
			sipNew = new PeriodicBoundary();
		}
	}

	if (sipNew == NULL)
	{
		const ForceField *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"-I",sipCanConvertTo_ForceField,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_ForceField(a0obj,(ForceField **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new PeriodicBoundary(* a0);
		}
	}

	if (sipNew == NULL)
	{
		const PeriodicBoundary *a0;
		PyObject *a0obj;
		long a1;

		if (sipParseArgs(sipArgs,"-Il",sipCanConvertTo_PeriodicBoundary,&a0obj,&a1))
		{
			int iserr = 0;

			sipConvertTo_PeriodicBoundary(a0obj,(PeriodicBoundary **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new PeriodicBoundary(* a0, (bool)a1);
		}
	}

	if (sipNew == NULL)
	{
		const PeriodicBoundary *a0;
		PyObject *a0obj;

		if (sipParseArgs(sipArgs,"-I",sipCanConvertTo_PeriodicBoundary,&a0obj))
		{
			int iserr = 0;

			sipConvertTo_PeriodicBoundary(a0obj,(PeriodicBoundary **)&a0,&iserr);

			if (iserr)
				return NULL;

			sipNew = new PeriodicBoundary(* a0);
		}
	}

	if (sipNew == NULL)
	{
		sipNoCtor(sipName_BALL_PeriodicBoundary);
		return NULL;
	}

	// Wrap the object.

	if ((sipThis = sipCreateThis(sipSelf,sipNew,&sipType_PeriodicBoundary,sipFlags,&et)) == NULL)
	{
		if (sipFlags & SIP_PY_OWNED)
			delete (PeriodicBoundary *)sipNew;

		return NULL;
	}

	Py_INCREF(Py_None);
	return Py_None;
}

static PyObject *sipGetSetVar_PeriodicBoundary_options(PyObject *sipThisObj,PyObject *valobj)
{
	int iserr = 0;
	Options *val;
	PeriodicBoundary *ptr;

	if ((ptr = (PeriodicBoundary *)sipGetCppPtr((sipThisType *)sipThisObj,sipClass_PeriodicBoundary)) == NULL)
		return NULL;

	if (valobj == NULL)
	{
		val = ptr -> options;

		valobj = sipMapCppToSelf(val,sipClass_Options);

		return valobj;
	}

	val = sipForceConvertTo_Options(valobj,&iserr);

	if (iserr)
	{
		sipBadSetType(sipName_BALL_PeriodicBoundary,sipName_BALL_options);
		return NULL;
	}

	ptr -> options = val;

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef sipClassAttrTab_PeriodicBoundary[] = {
	{sipName_BALL_setup, sipDo_PeriodicBoundary_setup, METH_VARARGS, NULL},
	{sipName_BALL_generateMoleculesVector, sipDo_PeriodicBoundary_generateMoleculesVector, METH_VARARGS, NULL},
	{sipName_BALL_enable, sipDo_PeriodicBoundary_enable, METH_VARARGS, NULL},
	{sipName_BALL_disable, sipDo_PeriodicBoundary_disable, METH_VARARGS, NULL},
	{sipName_BALL_getBox, sipDo_PeriodicBoundary_getBox, METH_VARARGS, NULL},
	{sipName_BALL_setBox, sipDo_PeriodicBoundary_setBox, METH_VARARGS, NULL},
	{sipName_BALL_addSolvent, sipDo_PeriodicBoundary_addSolvent, METH_VARARGS, NULL},
	{sipName_BALL_removeSolvent, sipDo_PeriodicBoundary_removeSolvent, METH_VARARGS, NULL},
	{sipName_BALL_isEnabled, sipDo_PeriodicBoundary_isEnabled, METH_VARARGS, NULL},
	{sipName_BALL_updateMolecules, sipDo_PeriodicBoundary_updateMolecules, METH_VARARGS, NULL},
	{NULL}
};

PyMethodDef sipClassVarTab_PeriodicBoundary[] = {
	{sipName_BALL_options, sipGetSetVar_PeriodicBoundary_options, 0, NULL},
	{NULL}
};

PyMethodDef *sipClassVarHierTab_PeriodicBoundary[] = {
	sipClassVarTab_PeriodicBoundary,
	NULL
};

int sipCanConvertTo_PeriodicBoundary(PyObject *sipPy)
{
	return sipIsSubClassInstance(sipPy,sipClass_PeriodicBoundary);
}

void sipConvertTo_PeriodicBoundary(PyObject *sipPy,PeriodicBoundary **sipCppPtr,int *sipIsErr)
{
	if (*sipIsErr || sipPy == NULL)
		return;

	if (sipPy == Py_None)
	{
		*sipCppPtr = NULL;
		return;
	}

	*sipCppPtr = (PeriodicBoundary *)sipConvertToCpp(sipPy,sipClass_PeriodicBoundary,sipIsErr);
}

PeriodicBoundary *sipForceConvertTo_PeriodicBoundary(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL || valobj == Py_None)
		return NULL;

	if (sipCanConvertTo_PeriodicBoundary(valobj))
	{
		PeriodicBoundary *val;

		sipConvertTo_PeriodicBoundary(valobj,&val,iserrp);

		return val;
	}

	sipBadClass(sipName_BALL_PeriodicBoundary);
	*iserrp = 1;

	return NULL;
}
