DIRECTORY=NMR

THISLIB=$(LIBNAME)

XCPP_SOURCES=EFShiftProcessor.C

CPP_SOURCES=\
	anisotropyShiftProcessor.C\
	assignShiftProcessor.C\
	clearShiftProcessor.C\
	createSpectrumProcessor.C\
	EFShiftProcessor.C\
	haighMallionShiftProcessor.C\
	makeSpectrumProcessor.C\
	peak.C\
	shiftModel.C\
	shiftModule.C\
	NMRSpectrum.C\
	johnsonBoveyShiftProcessor.C\
	randomCoilShiftProcessor.C

include ../common.mak
include .Dependencies
