DIRECTORY=NMR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	anisotropyShiftProcessor.C\
	assignShiftProcessor.C\
	clearShiftProcessor.C\
	empiricalHSShiftProcessor.C\
	EFShiftProcessor.C\
	experiment.C\
	HBondShiftProcessor.C\
	haighMallionShiftProcessor.C\
	createSpectrumProcessor.C\
	peak.C\
	peakList.C\
	shiftModel.C\
	shiftModel2D.C\
	shiftModule.C\
	spectrum.C\
	johnsonBoveyShiftProcessor.C\
	randomCoilShiftProcessor.C

include ../common.mak
-include .Dependencies
