DIRECTORY=NMR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	assignShiftProcessor.C\
	LEF.C\
	anisotropy.C\
	haighMallion.C\
	makeSpectrumProcessor.C\
	peak.C\
	shiftModule.C\
	NMRSpectrum.C\
	createSpectrumProcessor.C\
	johnsonBovey.C\
	names.C\
	randomCoil.C

include ../common.mak
include .Dependencies
