DIRECTORY=VIEW/GUI/FUNCTOR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	glObjectCollector.C\
	externalRenderer.C\
	POVRenderer.C

include ../../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)

