DIRECTORY=VIEW/GUI/FUNCTOR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	POVRenderer.C\
	modelProcessor.C\
	colorProcessor.C

include ../../../common.mak
include .Dependencies

BALL_INCLUDES=$(BALLVIEW_INCLUDES)

