// $Id: constants.sip,v 1.3 2001/07/29 17:31:16 oliver Exp $
%HeaderCode
	#include <BALL/PYTHON/pyConstant.h>
	using namespace BALL;
%End
namespace Constant
{
  const double PI;
  const double E;
  const double EPSILON;
  const double ELEMENTARY_CHARGE;     
  const double e0;
  const double ELECTRON_MASS;      
  const double PROTON_MASS;      
  const double NEUTRON_MASS;      
  const double AVOGADRO;
  const double NA;
  const double MOL;
  const double BOLTZMANN;
  const double k;
  const double PLANCK;
  const double h;
  const double GAS_CONSTANT;
  const double R;
  const double FARADAY;
  const double F;
  const double BOHR_RADIUS;
  const double a0;
  const double VACUUM_PERMITTIVITY;
  const double VACUUM_PERMEABILITY;
  const double SPEED_OF_LIGHT;
  const double c;
  const double GRAVITATIONAL_CONSTANT;
  const double FINE_STRUCTURE_CONSTANT;
  const double DEG_PER_RAD;
  const double RAD_PER_DEG;
  const double MM_PER_INCH;
  const double M_PER_FOOT;
  const double JOULE_PER_CAL;
  const double CAL_PER_JOULE;
};
