// $Id: constants.sip,v 1.2 2000/10/05 22:33:36 oliver Exp $
class Constant
{
%HeaderCode
	#include <BALL/PYTHON/pyConstant.h>
	using namespace BALL;
%End
	public:
  static double PI;
  static double E;
  static double EPSILON;
  static double ELEMENTARY_CHARGE;     
  static double e0;
  static double ELECTRON_MASS;      
  static double PROTON_MASS;      
  static double NEUTRON_MASS;      
  static double AVOGADRO;
  static double NA;
  static double MOL;
  static double BOLTZMANN;
  static double k;
  static double PLANCK;
  static double h;
  static double GAS_CONSTANT;
  static double R;
  static double FARADAY;
  static double F;
  static double BOHR_RADIUS;
  static double a0;
  static double VACUUM_PERMITTIVITY;
  static double VACUUM_PERMEABILITY;
  static double SPEED_OF_LIGHT;
  static double c;
  static double GRAVITATIONAL_CONSTANT;
  static double FINE_STRUCTURE_CONSTANT;
  static double DEG_PER_RAD;
  static double RAD_PER_DEG;
  static double MM_PER_INCH;
  static double M_PER_FOOT;
  static double JOULE_PER_CAL;
  static double CAL_PER_JOULE;
};
