DIRECTORY=MOLMEC/PARAMETER

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atomTypes.C\
	charmmEEF1.C\
	cosineTorsion.C\
	forceFieldParameters.C\
	lennardJones.C\
	potential1210.C\
	quadraticAngleBend.C\
	quadraticBondStretch.C\
	quadraticImproperTorsion.C\
	residueTorsions.C\
	templates.C

include ../../common.mak
include .Dependencies
