DIRECTORY=MOLMEC/PARAMETER

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atomTypes.C\
	forceFieldParameters.C\
	FFParameterSection.C\
	cosineTorsion.C\
	lennardJones.C\
	potential1210.C\
	quadraticAngleBend.C\
	quadraticBondStretch.C

include ../../common.mak
