SET(CPACK_PACKAGE_NAME "BALL")
SET(CPACK_PACKAGE_VENDOR "ball-project.org")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "BALL - The Biochemical Algorithms Library")
SET(CPACK_PACKAGE_VERSION "${CF_BALL_PACKAGE_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${BALL_PACKAGE_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${BALL_PACKAGE_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${BALL_PACKAGE_VERSION_PATCH}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "BALL-${CPACK_PACKAGE_VERSION}")
SET(CPACK_PACKAGE_DESCRIPTION_FILE ${PROJECT_SOURCE_DIR}/cmake/BALLPackageDescriptionFile.cmake)

SET(CPACK_NSIS_MUI_ICON "${PROJECT_SOURCE_DIR}/data/graphics/ballview.ico")
#SET(CPACK_PACKAGE_ICON "${PROJECT_SOURCE_DIR}/data/graphics/logo.bmp")

INCLUDE(CPack)

