SET(BALL_sources CACHE INTERNAL "This variable should hold all BALL sources at the end of the config step")

INCLUDE(source/CONCEPT/sources.cmake)
INCLUDE(source/COMMON/sources.cmake)
INCLUDE(source/DATATYPE/sources.cmake)
INCLUDE(source/ENERGY/sources.cmake)
INCLUDE(source/FORMAT/sources.cmake)
INCLUDE(source/KERNEL/sources.cmake)
INCLUDE(source/MATHS/sources.cmake)
INCLUDE(source/MOLMEC/sources.cmake)
INCLUDE(source/NMR/sources.cmake)
INCLUDE(source/PLUGIN/sources.cmake)
INCLUDE(source/PYTHON/sources.cmake)
INCLUDE(source/QSAR/sources.cmake)
INCLUDE(source/SCORING/sources.cmake)
INCLUDE(source/SOLVATION/sources.cmake)
INCLUDE(source/STRUCTURE/sources.cmake)
INCLUDE(source/SYSTEM/sources.cmake)
