FIND_PACKAGE(Boost COMPONENTS system thread iostreams asio)

IF (NOT Boost_VERSION) ## we cannot test for Boost_FOUND since this requires all components
	MESSAGE(SEND_ERROR "Could not find a suitable boost installation! This is a required dependency for BALL! Try setting BOOST_ROOT in ccmake!")
ELSE()
	IF (Boost_SYSTEM_FOUND)
		SET(BALL_HAS_BOOST_SYSTEM TRUE)
	ENDIF()
	IF (Boost_THREAD_FOUND)
		SET(BALL_HAS_BOOST_THREAD TRUE)
	ENDIF()
	IF (Boost_IOSTREAMS_FOUND)
		SET(BALL_HAS_BOOST_IOSTREAMS TRUE)
	ENDIF()
	IF (Boost_ASIO_FOUND)
		SET(BALL_HAS_BOOST_ASIO TRUE)
		SET(BALL_HAS_ASIO TRUE)
		SET(BALL_ASIO_NAMESPACE "boost::asio")
	ELSE()
		## Try to find asio as a standalone lib
		FIND_PATH(ASIO_INCLUDE_DIR NAMES asio.hpp)
		IF (ASIO_INCLUDE_DIR)
			SET(BALL_HAS_ASIO TRUE)
			SET(BALL_HAS_BOOST_ASIO FALSE)
			SET(BALL_ASIO_NAMESPACE "asio")
		ENDIF()
	ENDIF()
	SET(BOOST_INCLUDE_DIRS ${BOOST_INCLUDE_DIRS} ${ASIO_INCLUDE_DIR})
ENDIF()

