## libraries
SET(COMPONENT_LIBBALL "libBALL-${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}")
SET(COMPONENT_LIBVIEW "libVIEW-${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}")

## development
SET(COMPONENT_LIBBALL_DEV "libBALL-${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}-dev")
SET(COMPONENT_LIBVIEW_DEV "libVIEW-${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}-dev")

## applications
SET(COMPONENT_BALLVIEW "BALLView-${BALL_PACKAGE_VERSION_MAJOR}.${BALL_PACKAGE_VERSION_MINOR}")
