#
# $Id: Makefile,v 1.15 2005/07/16 21:00:41 oliver Exp $
#

DIRECTORY=MOLMEC/COMMON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	assignTypes.C\
	atomVector.C\
	chargeRuleProcessor.C\
	forceField.C\
	forceFieldComponent.C\
	gradient.C\
	periodicBoundary.C\
	radiusRuleProcessor.C\
	ruleEvaluator.C\
	ruleProcessor.C\
	snapShot.C\
	snapShotManager.C\
	support.C\
	typenameRuleProcessor.C\
	typeRuleProcessor.C

include ../../common.mak
-include .Dependencies
