#
# $Id: Makefile,v 1.13.14.1 2006/02/14 15:02:26 amoll Exp $
#

DIRECTORY=MOLMEC/COMMON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	assignTypes.C\
	atomVector.C\
	chargeRuleProcessor.C\
	forceField.C\
	forceFieldComponent.C\
	gradient.C\
	periodicBoundary.C\
	radiusRuleProcessor.C\
	ruleEvaluator.C\
	ruleProcessor.C\
	snapShot.C\
	snapShotManager.C\
	support.C\
	typenameRuleProcessor.C\
	typeRuleProcessor.C

include ../../common.mak
-include .Dependencies
