DIRECTORY=MOLMEC/COMMON

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	assignTypes.C\
	atomVector.C\
	chargeRuleProcessor.C
	forceField.C\
	forceFieldComponent.C\
	gradient.C\
	periodicBoundary.C\
	radiusRuleProcessor.C
	rules.C\
	ruleProcessor.C\
	snapShot.C\
	support.C\
	typenameRuleProcessor.C

include ../../common.mak
include .Dependencies
