DIRECTORY=QSAR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	aromaticityProcessor.C\
	connectivityBase.C\
	connectivityDescriptors.C\
	descriptor.C\
	partialChargeBase.C\
	partialChargeDescriptors.C\
	partialChargeProcessor.C\
	ringPerceptionProcessor.C\
	simpleBase.C\
	simpleDescriptors.C\
	surfaceBase.C\
	surfaceDescriptors.C

include ../common.mak
include .Dependencies
