DIRECTORY=MOLVIEW/FUNCTOR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	ballAndStickModel.C\
	baseModel.C\
	colorCalculator.C\
	findGeometricObject.C\
	lineModel.C\
	removeModel.C\
	vanDerWaalsModel.C

include ../../common.mak

