DIRECTORY=MOLVIEW/FUNCTOR

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	ballAndStickModel.C\
	baseModel.C\
	colorCalculator.C\
	findGeometricObject.C\
	geometricObjectSelector.C\
	lineModel.C\
	removeModel.C\
	standardColorCalculator.C\
	surfaceModel.C\
	vanDerWaalsModel.C

include ../../common.mak
include .Dependencies
