
DIRECTORY=SOLVATION

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	claverieParameter.C\
	molecularSurfaceGrid.C\
	ooiEnergy.C\
	PCMCavFreeEnergyProcessor.C\
	pierottiCavFreeEnergyProcessor.C\
	pair6_12RDFIntegrator.C\
	pairExpInteractionEnergyProcessor.C\
	pairExpRDFIntegrator.C\
	poissonBoltzmann.C\
	reissCavFreeEnergyProcessor.C\
	solventDescriptor.C\
	solventParameter.C\
	uhligCavFreeEnergyProcessor.C

include ../common.mak
include .Dependencies

