DIRECTORY=ENERGY

THISLIB=$(LIBNAME)

CPP_SOURCES=\
	atomicContactEnergy.C\
	composedEnergyProcessor.C\
	coulomb.C\
	distanceCoulomb.C\
	energyProcessor.C\
	fresnoEnergyProcessor.C

include ../common.mak
include .Dependencies
